//! Properties of the two identity families, over generated corpora rather than examples.
//!
//! Every corpus here is generated by a SplitMix64 with a pinned seed, so "random" means the same
//! four thousand cases on every machine and in every run. That is deliberate: a property test that
//! draws fresh entropy proves a different thing each time it runs and cannot be used as evidence
//! that a value is stable.

use std::collections::HashSet;

use mesh_types::{
    derive_id, Absorb, ActorId, ActorSequence, Blake3, CausalParents, ChangeSet, ChangeSetDraft,
    ChangeSetId, ChunkRef, ContentDigest, Digest32, DigestWriter, DirectoryEntry, DirectoryVersion,
    DomainTag, EntityIdError, FileManifest, FileVersion, HeadId, Hlc, ManifestId, NormalizedName,
    ObjectId, PolicyEpoch, PortableMetadata, PublicKey, SessionId, Signature, Uuid, VersionId,
    WorkspaceId,
};

/// SplitMix64. Four lines, no dependency, and identical on every platform because every operation
/// is defined on wrapping `u64`.
struct SplitMix64(u64);

impl SplitMix64 {
    const fn new(seed: u64) -> Self {
        Self(seed)
    }

    fn next(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    fn bytes(&mut self, len: usize) -> Vec<u8> {
        (0..len).map(|_| (self.next() & 0xff) as u8).collect()
    }

    fn digest(&mut self) -> Digest32 {
        let mut bytes = [0u8; 32];
        for slot in &mut bytes {
            *slot = (self.next() & 0xff) as u8;
        }
        Digest32::from_bytes(bytes)
    }

    fn u10(&mut self) -> [u8; 10] {
        let mut bytes = [0u8; 10];
        for slot in &mut bytes {
            *slot = (self.next() & 0xff) as u8;
        }
        bytes
    }

    fn below(&mut self, bound: u64) -> u64 {
        self.next() % bound
    }
}

const CORPUS: usize = 4096;

// ---------------------------------------------------------------------------------------------
// The hash the record identifiers rest on, folded to one number the reference implementation
// agrees with.
// ---------------------------------------------------------------------------------------------

/// The BLAKE3 of 4096 pseudorandom inputs, folded in order into one aggregate digest.
///
/// Produced by the `blake3` crate 1.8.6 in a throwaway program outside this repository, over the
/// same SplitMix64 corpus this test walks. One constant that moves if any of the 4096 individual
/// digests moves.
const REFERENCE_HASH_AGGREGATE: &str =
    "06d96d1a21abe492d8eed94c0cce4168b961ec2cb9574b0c9fc5196e5e881640";

#[test]
fn the_hash_agrees_with_the_reference_implementation_over_the_whole_corpus() {
    let mut rng = SplitMix64::new(0x0123_4567_89AB_CDEF);
    let mut aggregate = <Blake3 as ContentDigest>::hasher();
    let mut distinct = HashSet::new();

    for _ in 0..CORPUS {
        let len = rng.below(4201) as usize;
        let input = rng.bytes(len);
        let digest = Blake3::digest_bytes(&input);
        distinct.insert(digest);
        mesh_types::DigestHasher::update(&mut aggregate, digest.as_bytes());
    }

    assert_eq!(
        distinct.len(),
        CORPUS,
        "the corpus produced a repeated digest"
    );
    assert_eq!(
        mesh_types::DigestHasher::finalize(aggregate).to_hex(),
        REFERENCE_HASH_AGGREGATE
    );
}

// ---------------------------------------------------------------------------------------------
// Record identifiers: derived, stable, collision-free over the corpus.
// ---------------------------------------------------------------------------------------------

fn manifest(rng: &mut SplitMix64) -> FileManifest {
    let count = rng.below(6) as usize;
    let mut offset = 0u64;
    let mut chunks = Vec::with_capacity(count);
    for _ in 0..count {
        let length = rng.below(4096) + 1;
        chunks.push(ChunkRef::new(rng.digest(), offset, length));
        offset += length;
    }
    FileManifest::new(offset, rng.digest(), chunks)
}

fn file_version(rng: &mut SplitMix64) -> FileVersion {
    let parents = (0..rng.below(4))
        .map(|_| VersionId::from_digest(rng.digest()))
        .collect();
    FileVersion::new(
        ObjectId::mint(rng.next(), rng.u10()),
        parents,
        ManifestId::from_digest(rng.digest()),
        PortableMetadata::new(rng.next() & 1 == 1),
        ChangeSetId::from_digest(rng.digest()),
    )
}

fn directory_version(rng: &mut SplitMix64) -> DirectoryVersion {
    let mut entries = std::collections::BTreeMap::new();
    for index in 0..rng.below(6) {
        let name = NormalizedName::new(format!("entry-{}-{index}", rng.next()))
            .expect("generated names are structurally valid");
        entries.insert(
            name,
            DirectoryEntry::new(
                ObjectId::mint(rng.next(), rng.u10()),
                VersionId::from_digest(rng.digest()),
            ),
        );
    }
    DirectoryVersion::new(ObjectId::mint(rng.next(), rng.u10()), entries)
}

fn changeset(rng: &mut SplitMix64) -> ChangeSet<()> {
    let parents = if rng.next() & 1 == 0 {
        CausalParents::genesis()
    } else {
        CausalParents::after(
            ChangeSetId::from_digest(rng.digest()),
            (0..rng.below(3))
                .map(|_| ChangeSetId::from_digest(rng.digest()))
                .collect(),
        )
    };
    let mut signature = [0u8; 64];
    for slot in &mut signature {
        *slot = (rng.next() & 0xff) as u8;
    }
    ChangeSetDraft::<()>::new(
        WorkspaceId::mint(rng.next(), rng.u10()),
        ActorId::from_digest(rng.digest()),
        SessionId::mint(rng.next(), rng.u10()),
        ActorSequence::new(rng.next()),
        Hlc::new(rng.next(), rng.next() as u32),
    )
    .causal_parents(parents)
    .base_head(HeadId::from_digest(rng.digest()))
    .policy_epoch(PolicyEpoch::new(rng.next()))
    .seal(
        vec![(); rng.below(4) as usize],
        HeadId::from_digest(rng.digest()),
        Signature::from_bytes(signature),
    )
}

/// The identifiers of the whole generated corpus, folded in order into one aggregate.
///
/// This constant is the cross-process, cross-machine claim in its strongest checkable form. It was
/// computed by one process on one machine and checked in; every later run recomputes it from
/// scratch. Drift of any kind — a field order changed, a domain tag edited, an integer written
/// little-endian on a different target, the hasher behaving differently under a new compiler —
/// moves it. It is not evidence that the derivation is *correct*; the reference vectors above are
/// that. It is evidence that whatever it is, it does not change.
const RECORD_ID_AGGREGATE: &str =
    "4136aa1af9ed2cbf687393aa15ad0f9b11c0d7da9419327203703af230285574";

#[test]
fn record_identifiers_are_stable_across_processes_and_machines() {
    let mut rng = SplitMix64::new(0xFEED_FACE_CAFE_BEEF);
    let mut aggregate = <Blake3 as ContentDigest>::hasher();

    for _ in 0..CORPUS {
        let manifest = manifest(&mut rng);
        let file = file_version(&mut rng);
        let directory = directory_version(&mut rng);
        let changeset = changeset(&mut rng);

        for digest in [
            *derive_id::<Blake3, _>(&manifest).digest(),
            *derive_id::<Blake3, _>(&file).digest(),
            *derive_id::<Blake3, _>(&directory).digest(),
            *derive_id::<Blake3, _>(&changeset).digest(),
        ] {
            mesh_types::DigestHasher::update(&mut aggregate, digest.as_bytes());
        }
    }

    assert_eq!(
        mesh_types::DigestHasher::finalize(aggregate).to_hex(),
        RECORD_ID_AGGREGATE,
        "a record identifier moved: this is a compatibility event, not a test to update"
    );
}

#[test]
fn deriving_the_same_record_twice_gives_the_same_identifier() {
    let mut rng = SplitMix64::new(0x00C0_FFEE_0BAD_F00D);
    for _ in 0..CORPUS {
        let manifest = manifest(&mut rng);
        assert_eq!(
            derive_id::<Blake3, _>(&manifest),
            derive_id::<Blake3, _>(&manifest)
        );

        let file = file_version(&mut rng);
        assert_eq!(derive_id::<Blake3, _>(&file), derive_id::<Blake3, _>(&file));

        let changeset = changeset(&mut rng);
        assert_eq!(
            derive_id::<Blake3, _>(&changeset),
            derive_id::<Blake3, _>(&changeset)
        );
    }
}

#[test]
fn distinct_records_never_collide_within_the_corpus() {
    let mut rng = SplitMix64::new(0x5EED_1234_5678_9ABC);
    let mut manifests = HashSet::new();
    let mut files = HashSet::new();
    let mut directories = HashSet::new();
    let mut changesets = HashSet::new();
    let mut everything = HashSet::new();

    for _ in 0..CORPUS {
        let manifest_id: ManifestId = derive_id::<Blake3, _>(&manifest(&mut rng));
        let file_id: VersionId = derive_id::<Blake3, _>(&file_version(&mut rng));
        let directory_id: VersionId = derive_id::<Blake3, _>(&directory_version(&mut rng));
        let changeset_id: ChangeSetId = derive_id::<Blake3, _>(&changeset(&mut rng));

        manifests.insert(manifest_id);
        files.insert(file_id);
        directories.insert(directory_id);
        changesets.insert(changeset_id);
        for digest in [
            *manifest_id.digest(),
            *file_id.digest(),
            *directory_id.digest(),
            *changeset_id.digest(),
        ] {
            everything.insert(digest);
        }
    }

    assert_eq!(manifests.len(), CORPUS);
    assert_eq!(files.len(), CORPUS);
    assert_eq!(directories.len(), CORPUS);
    assert_eq!(changesets.len(), CORPUS);
    assert_eq!(
        everything.len(),
        CORPUS * 4,
        "two records of different types share an identifier"
    );
}

/// Framing, not formatting: a length prefix is what stops two different field sequences producing
/// one byte stream. Without it, `("ab", "c")` and `("a", "bc")` would be the same record.
#[test]
fn field_framing_is_unambiguous() {
    fn digest_of(fields: &[&str]) -> Digest32 {
        let mut writer = DigestWriter::new(
            DomainTag::new("test.framing"),
            <Blake3 as ContentDigest>::hasher(),
        );
        for field in fields {
            writer.text(field);
        }
        writer.finish()
    }

    assert_ne!(digest_of(&["ab", "c"]), digest_of(&["a", "bc"]));
    assert_ne!(digest_of(&["", "abc"]), digest_of(&["abc", ""]));
    assert_ne!(digest_of(&["abc"]), digest_of(&["abc", ""]));
    assert_eq!(digest_of(&["ab", "c"]), digest_of(&["ab", "c"]));
}

/// Two records with byte-identical fields in different domains must not share an identifier.
#[test]
fn domain_tags_separate_otherwise_identical_records() {
    fn digest_in(domain: &'static str) -> Digest32 {
        let mut writer =
            DigestWriter::new(DomainTag::new(domain), <Blake3 as ContentDigest>::hasher());
        writer.u64(7);
        writer.finish()
    }

    assert_ne!(
        digest_in("mesh.v0.file-version"),
        digest_in("mesh.v0.directory-version")
    );
    assert_ne!(
        digest_in("mesh.v0.changeset"),
        digest_in("mesh.v0.file-manifest")
    );
}

/// A directory version is a map, so the same entries inserted in a different order are the same
/// record — and must derive the same identifier without the caller sorting anything.
#[test]
fn directory_entry_insertion_order_does_not_change_the_identifier() {
    let mut rng = SplitMix64::new(0x0BAD_CAFE_0BAD_CAFE);
    let object = ObjectId::mint(rng.next(), rng.u10());
    let names: Vec<NormalizedName> = ["zeta", "alpha", "mu", "beta"]
        .iter()
        .map(|name| NormalizedName::new(*name).expect("literal names are valid"))
        .collect();
    let entries: Vec<DirectoryEntry> = names
        .iter()
        .map(|_| {
            DirectoryEntry::new(
                ObjectId::mint(rng.next(), rng.u10()),
                VersionId::from_digest(rng.digest()),
            )
        })
        .collect();

    let mut forward = std::collections::BTreeMap::new();
    for (name, entry) in names.iter().zip(entries.iter()) {
        forward.insert(name.clone(), *entry);
    }
    let mut backward = std::collections::BTreeMap::new();
    for (name, entry) in names.iter().zip(entries.iter()).rev() {
        backward.insert(name.clone(), *entry);
    }

    let forward: VersionId = derive_id::<Blake3, _>(&DirectoryVersion::new(object, forward));
    let backward: VersionId = derive_id::<Blake3, _>(&DirectoryVersion::new(object, backward));
    assert_eq!(forward, backward);
}

/// An actor identifier is the digest of the key and nothing else, so the mutable parts of an
/// actor record cannot rename it.
#[test]
fn actor_identifiers_depend_only_on_the_key() {
    let mut rng = SplitMix64::new(0xA11C_E000_B0B0_1234);
    let mut seen = HashSet::new();
    for _ in 0..CORPUS {
        let mut key_bytes = [0u8; 32];
        for slot in &mut key_bytes {
            *slot = (rng.next() & 0xff) as u8;
        }
        let key = PublicKey::from_bytes(key_bytes);
        assert_eq!(key.actor_id::<Blake3>(), key.actor_id::<Blake3>());
        seen.insert(key.actor_id::<Blake3>());
    }
    assert_eq!(seen.len(), CORPUS, "two keys produced one actor identifier");
}

// ---------------------------------------------------------------------------------------------
// Entity identifiers: minted, version 7, never derived.
// ---------------------------------------------------------------------------------------------

#[test]
fn every_minted_entity_identifier_is_a_version_7_uuid() {
    let mut rng = SplitMix64::new(0x7777_7777_7777_7777);
    for _ in 0..CORPUS {
        let millis = rng.next() & 0x0000_FFFF_FFFF_FFFF;
        let workspace = WorkspaceId::mint(millis, rng.u10());
        assert_eq!(workspace.uuid().version(), 7);
        assert!(workspace.uuid().is_rfc_variant());
        assert_eq!(workspace.unix_millis(), millis);

        let round_tripped =
            WorkspaceId::parse(&workspace.to_string()).expect("a minted identifier parses");
        assert_eq!(round_tripped, workspace);
    }
}

/// The millisecond field is 48 bits wide, so a larger value must truncate rather than corrupt the
/// version nibble that sits immediately after it.
#[test]
fn an_oversized_millisecond_truncates_without_corrupting_the_version() {
    let mut rng = SplitMix64::new(0x1248_1632_6412_8256);
    for _ in 0..CORPUS {
        let millis = rng.next();
        let session = SessionId::mint(millis, rng.u10());
        assert_eq!(session.uuid().version(), 7);
        assert!(session.uuid().is_rfc_variant());
        assert_eq!(session.unix_millis(), millis & 0x0000_FFFF_FFFF_FFFF);
    }
}

/// Minting is time-ordered: later milliseconds sort later, whatever the random tail is.
#[test]
fn minted_identifiers_sort_by_their_millisecond() {
    let mut rng = SplitMix64::new(0x3141_5926_5358_9793);
    for _ in 0..CORPUS {
        let earlier = rng.below(1 << 40);
        let later = earlier + 1 + rng.below(1 << 20);
        let first = ObjectId::mint(earlier, rng.u10());
        let second = ObjectId::mint(later, rng.u10());
        assert!(first < second, "{first} should sort before {second}");
    }
}

/// A UUID of any other version is refused. This is the runtime half of the guarantee; the
/// type-level half is that no constructor accepts a digest at all.
#[test]
fn every_non_version_7_uuid_is_refused() {
    let mut rng = SplitMix64::new(0x4444_4444_4444_4444);
    for _ in 0..CORPUS {
        let mut bytes = [0u8; 16];
        for slot in &mut bytes {
            *slot = (rng.next() & 0xff) as u8;
        }
        // Every version except 7, with the RFC variant bits set so version is the only fault.
        let version = (rng.below(15) as u8 + 1) % 16;
        let version = if version == 7 { 4 } else { version };
        bytes[6] = (version << 4) | (bytes[6] & 0x0f);
        bytes[8] = 0x80 | (bytes[8] & 0x3f);

        assert_eq!(
            WorkspaceId::from_uuid(Uuid::from_bytes(bytes)),
            Err(EntityIdError::WrongVersion { found: version })
        );
    }
}

#[test]
fn a_version_7_uuid_with_the_wrong_variant_is_refused() {
    let mut rng = SplitMix64::new(0x5555_5555_5555_5555);
    for _ in 0..CORPUS {
        let mut bytes = *WorkspaceId::mint(rng.next(), rng.u10()).uuid().as_bytes();
        // Anything but the RFC 9562 variant.
        bytes[8] = if rng.next() & 1 == 0 {
            bytes[8] & 0x3f
        } else {
            0xc0 | (bytes[8] & 0x3f)
        };
        assert_eq!(
            WorkspaceId::from_uuid(Uuid::from_bytes(bytes)),
            Err(EntityIdError::WrongVariant)
        );
    }
}

/// A record identifier's hex form is not a UUID and must never be accepted as one, which is the
/// concrete shape the "never derived from content" rule takes at a parsing boundary.
#[test]
fn a_record_identifier_is_not_accepted_as_an_entity_identifier() {
    let mut rng = SplitMix64::new(0x6666_6666_6666_6666);
    for _ in 0..CORPUS {
        let record = VersionId::from_digest(rng.digest());
        assert!(WorkspaceId::parse(&record.to_string()).is_err());
        assert!(SessionId::parse(&record.to_string()).is_err());
        assert!(ObjectId::parse(&record.to_string()).is_err());
    }
}

/// Both identifier families round-trip through their text form for every case in the corpus.
#[test]
fn both_identifier_families_round_trip_through_text() {
    let mut rng = SplitMix64::new(0x9999_9999_9999_9999);
    for _ in 0..CORPUS {
        let entity = WorkspaceId::mint(rng.next(), rng.u10());
        let text = entity.to_string();
        assert_eq!(text.len(), 36);
        assert_eq!(WorkspaceId::parse(&text).expect("round trip"), entity);

        let record = ChangeSetId::from_digest(rng.digest());
        let text = record.to_string();
        assert_eq!(text.len(), 64);
        assert_eq!(ChangeSetId::parse_hex(&text).expect("round trip"), record);
    }
}

/// Absorbing a ChangeSet must reach every bound field. Mutating any one of the ten must move the
/// identifier; the signature is the eleventh member and must not.
#[test]
fn every_bound_changeset_field_moves_the_identifier() {
    let mut rng = SplitMix64::new(0xABCD_EF01_2345_6789);
    let base = changeset(&mut rng);
    let baseline: ChangeSetId = derive_id::<Blake3, _>(&base);

    let head_a = HeadId::from_digest(Digest32::from_bytes([1; 32]));
    let head_b = HeadId::from_digest(Digest32::from_bytes([2; 32]));

    let field_changed: Vec<ChangeSet<()>> = vec![
        rebuild(&base, |draft| draft, |ops| ops, |_| head_a),
        rebuild(&base, |draft| draft, |ops| ops, |_| head_b),
    ];
    // The two differ only in the resulting head, so their identifiers must differ from each other
    // and at least one must differ from the baseline.
    assert_ne!(
        derive_id::<Blake3, _>(&field_changed[0]),
        derive_id::<Blake3, _>(&field_changed[1])
    );

    // The signature is not bound: replacing it leaves the identifier alone.
    let resigned = ChangeSetDraft::<()>::new(
        base.workspace_id(),
        base.actor_id(),
        base.session_id(),
        base.actor_sequence(),
        base.hybrid_logical_time(),
    )
    .causal_parents(base.causal_parents().clone())
    .base_head(base.base_head())
    .policy_epoch(base.policy_epoch())
    .seal(
        base.operations().to_vec(),
        base.resulting_head(),
        Signature::from_bytes([0xff; 64]),
    );
    assert_ne!(base.signature(), resigned.signature());
    assert_eq!(derive_id::<Blake3, _>(&resigned), baseline);
}

fn rebuild(
    base: &ChangeSet<()>,
    draft: impl Fn(
        ChangeSetDraft<(), CausalParents, HeadId, PolicyEpoch>,
    ) -> ChangeSetDraft<(), CausalParents, HeadId, PolicyEpoch>,
    operations: impl Fn(Vec<()>) -> Vec<()>,
    resulting_head: impl Fn(HeadId) -> HeadId,
) -> ChangeSet<()> {
    draft(
        ChangeSetDraft::<()>::new(
            base.workspace_id(),
            base.actor_id(),
            base.session_id(),
            base.actor_sequence(),
            base.hybrid_logical_time(),
        )
        .causal_parents(base.causal_parents().clone())
        .base_head(base.base_head())
        .policy_epoch(base.policy_epoch()),
    )
    .seal(
        operations(base.operations().to_vec()),
        resulting_head(base.resulting_head()),
        *base.signature(),
    )
}

/// The unit operation absorbs nothing, so a length-prefixed sequence of them must still be
/// distinguishable by its length alone.
#[test]
fn an_operation_sequence_is_distinguished_by_its_length() {
    fn digest_of(count: usize) -> Digest32 {
        let mut writer = DigestWriter::new(
            DomainTag::new("test.sequence"),
            <Blake3 as ContentDigest>::hasher(),
        );
        writer.sequence(&vec![(); count], |writer, unit| unit.absorb(writer));
        writer.finish()
    }
    let digests: HashSet<Digest32> = (0..8).map(digest_of).collect();
    assert_eq!(digests.len(), 8);
}
