/** Reviewed UI copy only. Paths, file contents, protocol values and native diagnostics are never translated. */
export const hebrew: Readonly<Record<string, string>> = Object.freeze({
"Saved history restored; resume when ready":"ההיסטוריה השמורה שוחזרה; אפשר לחדש את הלכידה כשמוכנים",
"Project or history needs reconciliation":"יש לאמת מחדש את הפרויקט או ההיסטוריה",
"Saved version unavailable until history is verified":"הגרסה השמורה אינה זמינה עד לאימות ההיסטוריה",
"Retry capture":"ניסיון לכידה נוסף",
"Registered projects return when Mesh opens. Recovered projects remain stopped until you resume capture.":"הפרויקטים הרשומים חוזרים כשפותחים את Mesh. פרויקטים ששוחזרו נשארים עצורים עד לחידוש הלכידה.",
"Restoring saved comparisons…":"משחזר השוואות שמורות…",
"Saving comparison selections…":"שומר בחירות להשוואה…",
"Comparison selections saved":"בחירות ההשוואה נשמרו",
"Retry saving or loading pins":"ניסיון נוסף לשמירה או לטעינה של השוואות נעוצות",
"Replace open pins with saved set":"החלפת ההשוואות הפתוחות בקבוצה השמורה",
"Saved comparison unavailable. Its selection is retained.":"ההשוואה השמורה אינה זמינה. הבחירה שלה נשמרת.",
"Retry saved comparison":"ניסיון נוסף לטעינת ההשוואה השמורה",
"Each pin keeps its own version pair, page and file selection. Saved selections return when Mesh opens; content is verified again from history.":"כל השוואה נעוצה שומרת על זוג הגרסאות, העמוד ובחירת הקובץ שלה. הבחירות השמורות חוזרות עם פתיחת Mesh; התוכן מאומת מחדש מתוך ההיסטוריה.",
"Saved pins could not be loaded. Their stored record has not been replaced.":"לא ניתן לטעון את ההשוואות הנעוצות. הרשומה השמורה שלהן לא הוחלפה.",
"Pin changes are not confirmed saved. Current views remain open; retry saving or reload the saved set.":"שמירת השינויים בהשוואות הנעוצות לא אושרה. התצוגות הנוכחיות נשארות פתוחות; נסו לשמור שוב או לטעון את הקבוצה השמורה.",
"Saved pins changed or remain unavailable. Reload the saved set to reconcile; local views have not been overwritten.":"ההשוואות השמורות השתנו או עדיין אינן זמינות. טענו מחדש את הקבוצה השמורה; התצוגות המקומיות לא הוחלפו.",
"Pinned comparisons":"השוואות נעוצות",
"Close comparison":"סגירת השוואה",
"Pin comparison alongside others":"נעיצת השוואה לצד השוואות אחרות",
"Eight comparisons pinned; close one to add another":"שמונה השוואות נעוצות; סגרו אחת כדי להוסיף אחרת",
"Each pin keeps its own version pair, page and file selection. Pins are retained during this desktop session.":"כל השוואה נעוצה שומרת על זוג הגרסאות, העמוד ובחירת הקובץ שלה. ההשוואות הנעוצות נשמרות במהלך הפעלה זו של היישום.",
"Selected comparison base:":"הבסיס שנבחר להשוואה:",
"Use as base":"בחירה כבסיס",
"Compare with base":"השוואה לבסיס",
"Content changed":"התוכן השתנה",
"Executable mode changed":"מצב ההרצה השתנה",
"File/folder type changed":"סוג הפריט השתנה בין קובץ לתיקייה",
"Not executable":"אינו ניתן להרצה",
"Saved version comparison":"השוואת גרסאות שמורות",
"Compare saved versions":"השוואת גרסאות שמורות",
"changed paths":"נתיבים שהשתנו",
"Base:":"בסיס:",
"Compared version:":"הגרסה המושווית:",
"These versions have the same paths, content and executable modes.":"לגרסאות האלה יש אותם נתיבים, תוכן ומצבי הרצה.",
"More changes":"שינויים נוספים",
"Absent in this version":"אינו קיים בגרסה זו",
"This comparison stays on these saved versions while work continues. It does not approve or apply changes.":"ההשוואה נשארת על הגרסאות השמורות האלה בזמן שהעבודה נמשכת. היא אינה מאשרת או מחילה שינויים.",
"Binary file; no text preview":"קובץ בינארי; אין תצוגת טקסט",
"File exceeds the 256 KiB preview limit":"הקובץ חורג ממגבלת התצוגה של 256 KiB",
"This history page stays fixed while capture continues.":"עמוד ההיסטוריה נשאר קבוע בזמן שהלכידה נמשכת.",
"Saved version files":"קבצי הגרסה השמורה",
"Files in saved version":"קבצים בגרסה השמורה",
"This saved version has no files or folders.":"בגרסה השמורה הזו אין קבצים או תיקיות.",
"More files":"קבצים נוספים",
"Binary file. Text preview is unavailable.":"קובץ בינארי. תצוגת טקסט אינה זמינה.",
"This file exceeds the 256 KiB text preview limit.":"הקובץ חורג ממגבלת תצוגת הטקסט של 256 KiB.",
"Read-only saved content. Edits in your working folder do not change this view.":"תוכן שמור לקריאה בלבד. עריכות בתיקיית העבודה אינן משנות תצוגה זו.",
"Show latest versions":"הצגת הגרסאות האחרונות",
"Saved versions for":"גרסאות שמורות עבור",
"Saved versions · newest first":"גרסאות שמורות · החדשות תחילה",
"Older versions":"גרסאות קודמות",
"This history page stays fixed while capture continues. File previews and review are not available here yet.":"עמוד ההיסטוריה נשאר קבוע בזמן שהלכידה נמשכת. תצוגה מקדימה של קבצים וסקירה אינן זמינות כאן עדיין.",
"Separate workspace":"סביבת עבודה נפרדת",
"Create a working copy":"יצירת עותק עבודה",
"Attached projects":"פרויקטים מחוברים",
"Use your existing project":"שימוש בפרויקט הקיים",
"Keep your folder, editor, Git workflow and agent sessions where they are. Mesh saves history in separate storage while you work.":"התיקייה, העורך, תהליך העבודה ב־Git ושיחות הסוכנים נשארים במקומם. Mesh שומר היסטוריה באחסון נפרד בזמן העבודה.",
"Choose project to attach":"בחירת פרויקט לחיבור",
"Existing project path":"נתיב הפרויקט הקיים",
"Attach existing project":"חיבור פרויקט קיים",
"Attachment requires the native Mesh desktop.":"חיבור פרויקט זמין ביישום Mesh למחשב.",
"Refresh status":"רענון מצב",
"Updating…":"מעדכן…",
"Status may be out of date":"ייתכן שהמצב אינו עדכני",
"Starting capture":"מתחיל לכידה",
"Checking changes":"בודק שינויים",
"Saving a version":"שומר גרסה",
"Watching for changes":"ממתין לשינויים",
"Stopping capture":"עוצר לכידה",
"Capture stopped":"הלכידה נעצרה",
"Capture needs attention":"הלכידה דורשת תשומת לב",
"First capture pending":"ממתין ללכידה הראשונה",
"Version saved":"הגרסה נשמרה",
"No new changes":"אין שינויים חדשים",
"Capture incomplete":"הלכידה אינה מלאה",
"Project folder unavailable":"תיקיית הפרויקט אינה זמינה",
"History storage unavailable":"אחסון ההיסטוריה אינו זמין",
"Version could not be saved":"לא ניתן היה לשמור גרסה",
"Capture cancelled":"הלכידה בוטלה",
"Latest saved version:":"הגרסה האחרונה שנשמרה:",
"No saved version yet":"עדיין אין גרסה שמורה",
"No complete capture in this session":"אין עדיין לכידה מלאה בהפעלה זו",
"Last complete capture started":"הלכידה המלאה האחרונה התחילה לפני",
"seconds ago":"שניות",
"Change author unknown.":"זהות מבצע השינוי אינה ידועה.",
"Capture now":"לכידה כעת",
"Resume capture":"חידוש הלכידה",
"Stop capture":"עצירת הלכידה",
"After reopening Mesh, attach the same project to resume capture. Saved history is retained.":"לאחר פתיחה מחדש של Mesh, חברו שוב את אותו הפרויקט לחידוש הלכידה. ההיסטוריה השמורה נשמרת.",
"Attachment status is unavailable. Your existing tools can keep working. Retry to refresh.":"מצב החיבור אינו זמין. אפשר להמשיך לעבוד בכלים הקיימים. נסו לרענן שוב.",
"Workspaces":"סביבות עבודה", "Import":"ייבוא", "Current":"נוכחי", "Files":"קבצים", "Changes":"שינויים", "Review":"סקירה", "Versions":"גרסאות", "Update destination":"עדכון תיקיית היעד", "Restore":"שחזור",
"Local workspace":"סביבת עבודה מקומית", "Primary pages":"עמודים ראשיים", "Skip to workspace":"דילוג לסביבת העבודה", "· Local only · No network listener":"· מקומי בלבד · ללא האזנה לרשת",
"NATIVE WORKSPACE":"סביבת עבודה", "LOCAL WORKSPACE":"סביבת עבודה מקומית", "Your folder, with a private history.":"התיקייה שלכם, עם היסטוריה פרטית.", "Work in your folder. Mesh remembers.":"עובדים בתיקייה שלכם. Mesh זוכר.",
"Choose a folder":"בחירת תיקייה", "Import another folder":"ייבוא תיקייה נוספת", "Preview this folder":"תצוגה מקדימה של התיקייה", "Retry verification":"ניסיון אימות נוסף", "Refresh":"רענון", "Your original folder stays untouched.":"התיקייה המקורית נשארת ללא שינוי.", "Import or switch to another workspace":"ייבוא או מעבר לסביבת עבודה אחרת", "Bring in an ordinary project folder":"ייבוא תיקיית פרויקט רגילה", "Return to a recent Mesh workspace":"חזרה לסביבת עבודה אחרונה", "Already use Mesh? Open a managed workspace":"כבר משתמשים ב־Mesh? פתיחת סביבת עבודה מנוהלת",
"Choose managed workspace":"בחירת סביבת עבודה מנוהלת", "Or enter its path":"או הזנת הנתיב שלה", "Open path":"פתיחת נתיב", "Recent workspaces":"סביבות עבודה אחרונות", "No recent workspace yet":"אין עדיין סביבות עבודה אחרונות", "Forget from list":"הסרה מהרשימה", "Open selected workspace":"פתיחת סביבת העבודה שנבחרה", "Open recent workspace":"פתיחת סביבת עבודה אחרונה",
"Bring in a folder":"ייבוא תיקייה", "Start with your folder":"מתחילים עם התיקייה שלכם", "Keep working in ordinary files":"ממשיכים לעבוד בקבצים רגילים", "Mesh verifies the folder before creating a private workspace. Your original stays untouched.":"Mesh מאמת את התיקייה לפני יצירת סביבת עבודה פרטית. המקור נשאר ללא שינוי.", "Absolute folder path":"נתיב מלא לתיקייה", "Preview folder":"תצוגה מקדימה של התיקייה", "or use a path":"או שימוש בנתיב", "Verified copy":"עותק מאומת", "Verified folder preview":"תצוגה מקדימה מאומתת", "Creating private workspace":"יוצר סביבת עבודה פרטית", "Ready to create":"מוכן ליצירה", "Review what Mesh will bring in":"סקירת התוכן ש־Mesh ייבא", "Folders":"תיקיות", "Size":"גודל", "Review included files":"סקירת הקבצים הכלולים", "Verified summary":"סיכום מאומת", "Use a custom private location":"שימוש במיקום פרטי אחר", "Custom location":"מיקום מותאם", "Leave blank for Mesh-managed storage":"להשאיר ריק לאחסון בניהול Mesh", "Choose parent":"בחירת תיקיית אב", "Choose another folder":"בחירת תיקייה אחרת", "The original folder is never opened for writing.":"Mesh אינו פותח את התיקייה המקורית לכתיבה.", "Create private workspace":"יצירת סביבת עבודה פרטית", "Create workspace":"יצירת סביבת עבודה", "Keep Mesh open. Large projects can take several minutes; the original folder remains unchanged.":"יש להשאיר את Mesh פתוח. פרויקטים גדולים עשויים להימשך כמה דקות; התיקייה המקורית נשארת ללא שינוי.", "Choose an ordinary folder. Mesh verifies every included file before it creates a private working copy.":"בחרו תיקייה רגילה. Mesh מאמת כל קובץ כלול לפני יצירת עותק עבודה פרטי.",
"Ready":"מוכן", "Checking":"בודק", "Available":"זמין", "Selected":"נבחר", "Status":"מצב", "Details":"פרטים", "Folder":"תיקייה", "File":"קובץ", "Path":"נתיב", "Type":"סוג", "History":"היסטוריה", "History:":"היסטוריה:", "Private history":"היסטוריה פרטית", "Saved locally":"נשמר מקומית", "Current workspace":"סביבת עבודה נוכחית", "Current workspace details":"פרטי סביבת העבודה הנוכחית", "Working folder":"תיקיית עבודה", "Working copy":"עותק עבודה", "Workspace details":"פרטי סביבת העבודה", "Workspace overview":"סקירת סביבת העבודה", "Workspace details and recovery":"פרטי סביבת העבודה ושחזור", "Support and recovery":"תמיכה ושחזור", "Copy safe diagnostics":"העתקת אבחון בטוח", "Refresh workspace state":"רענון מצב סביבת העבודה", "Switch workspace":"החלפת סביבת עבודה",
"Explorer":"סייר", "Workspace file explorer":"סייר קבצי סביבת העבודה", "Workspace files":"קבצי סביבת העבודה", "Files and folders":"קבצים ותיקיות", "Browse and open the exact working files.":"עיון ופתיחה של קבצי העבודה המדויקים.", "Filter workspace files":"סינון קבצי סביבת העבודה", "Go to file…":"מעבר לקובץ…", "Collapse all":"כיווץ הכול", "File details":"פרטי קובץ", "File type":"סוג קובץ", "Selected path":"הנתיב שנבחר", "Select an item from Files":"בחרו פריט מתוך הקבצים", "Choose a file":"בחירת קובץ", "Open in default app":"פתיחה ביישום ברירת המחדל", "Reveal in Finder":"הצגה ב־Finder", "Open folder":"פתיחת תיקייה", "Open working folder":"פתיחת תיקיית העבודה", "Relative path":"נתיב יחסי", "New relative path":"נתיב יחסי חדש", "Rename or move":"שינוי שם או העברה", "Delete selected item":"מחיקת הפריט שנבחר", "Folder selected":"נבחרה תיקייה", "Parent":"תיקיית אב", "New":"חדש",
"Working changes":"שינויים בעבודה", "Folder changes":"שינויים בתיקייה", "Find changes":"איתור שינויים", "Find folder changes":"איתור שינויים בתיקייה", "Save privately":"שמירה פרטית", "Save all privately":"שמירת הכול באופן פרטי", "Save version":"שמירת גרסה", "Changes and text editor":"שינויים ועורך טקסט", "Change summary":"סיכום שינויים", "Changed files":"קבצים שהשתנו", "Search changed files":"חיפוש בקבצים שהשתנו", "All statuses":"כל המצבים", "All types":"כל הסוגים", "Current file":"קובץ נוכחי", "Before":"לפני", "After":"אחרי", "Working tree diff":"השוואת קבצי העבודה", "No text changes":"אין שינויי טקסט", "The working copy matches the saved version exactly.":"עותק העבודה תואם בדיוק לגרסה השמורה.", "Saved baseline cannot be displayed":"לא ניתן להציג את גרסת הבסיס השמורה", "Comparison is too large to display":"ההשוואה גדולה מדי להצגה", "Selected change comparison":"השוואת השינוי שנבחר", "Inline text comparison":"השוואת טקסט רציפה", "Split text comparison":"השוואת טקסט מפוצלת", "Unchanged text comparison":"השוואת טקסט ללא שינוי", "No newline":"ללא ירידת שורה", "No current line":"אין שורה נוכחית", "No earlier line":"אין שורה קודמת", "line":"שורה", "lines":"שורות", "added":"נוסף", "modified":"שונה", "deleted":"נמחק", "changed":"השתנה", "removed":"הוסר", "addition":"תוספת", "additions":"תוספות", "deletion":"מחיקה", "deletions":"מחיקות", "of":"מתוך", "page":"עמוד",
"Saved version":"גרסה שמורה", "Current saved version":"הגרסה השמורה הנוכחית", "Earlier saved version":"גרסה שמורה קודמת", "Saved file":"קובץ שמור", "Saved workspace":"סביבת עבודה שמורה", "Saved points":"נקודות שמירה", "Saved workspace points":"נקודות שמירה של סביבת העבודה", "Workspace versions":"גרסאות סביבת העבודה", "Workspaces and agents":"סביבות עבודה וסוכנים", "Find a workspace or agent":"חיפוש סביבת עבודה או סוכן", "Search by name, state, or path…":"חיפוש לפי שם, מצב או נתיב…", "No active agent":"אין סוכן פעיל", "No assigned agent":"אין סוכן משויך", "Agent assigned":"סוכן משויך", "Agent running":"סוכן פועל", "Workspace or assigned agent":"סביבת עבודה או סוכן משויך", "Open an exact saved point":"פתיחת נקודת שמירה מדויקת", "Switch without losing agent context":"מעבר בלי לאבד את הקשר הסוכן", "Selected version preview":"תצוגה מקדימה של הגרסה שנבחרה", "Private version":"גרסה פרטית", "Shared version":"גרסה משותפת", "Exact copy":"עותק מדויק", "Concurrent history":"היסטוריה מקבילה", "Find a saved file":"חיפוש קובץ שמור", "Find an earlier saved version":"חיפוש גרסה שמורה קודמת", "Filter saved files…":"סינון קבצים שמורים…", "Filter saved versions…":"סינון גרסאות שמורות…", "No saved files available":"אין קבצים שמורים זמינים",
"Review work":"סקירת העבודה", "Start review":"התחלת סקירה", "Saved review":"סקירה שמורה", "Live agent work":"עבודה חיה של סוכן", "Live agent work review":"סקירת עבודה חיה של סוכן", "Review workbench":"מרחב סקירה", "Review workspace summary":"סקירת סיכום סביבת העבודה", "Review status":"מצב סקירה", "Review decision":"החלטת סקירה", "Decision":"החלטה", "Review bundle":"חבילת סקירה", "Review this exact saved version":"סקירת הגרסה השמורה המדויקת", "Understand exactly what changed":"להבין בדיוק מה השתנה", "Comparison view":"תצוגת השוואה", "Load visual comparison":"טעינת השוואה חזותית", "Reload visual comparison":"טעינה מחדש של ההשוואה החזותית", "Try visual comparison again":"ניסיון נוסף להשוואה חזותית", "Rendering exact versions…":"מציג את הגרסאות המדויקות…", "Text comparison unavailable":"השוואת טקסט אינה זמינה", "Content comparison could not be loaded":"לא ניתן לטעון את השוואת התוכן", "Artifact content comparison unavailable":"השוואת תוכן המסמך אינה זמינה", "Load the exact versions to compare their content":"יש לטעון את הגרסאות המדויקות כדי להשוות את תוכנן", "Previous":"הקודם", "Next":"הבא", "Previous page":"העמוד הקודם", "Next page":"העמוד הבא", "Confirm review complete":"אישור השלמת הסקירה", "Approve exact version":"אישור הגרסה המדויקת", "Open copy folder":"פתיחת תיקיית העותק", "Inspect exact copies":"בדיקת העותקים המדויקים", "Not present":"לא קיים", "Read-only monitor":"מעקב לקריאה בלבד", "Monitoring":"במעקב", "Mutable":"ניתן לשינוי", "Unrecorded":"טרם נשמר", "Inspect work without finishing the handoff":"בדיקת העבודה בלי לסיים את ההעברה לסוכן",
"Restore an earlier file version":"שחזור גרסה קודמת של קובץ", "Find a retained file":"חיפוש קובץ שנשמר בהיסטוריה", "Filter retained files…":"סינון קבצים בהיסטוריה…", "Choose a file first":"יש לבחור קובץ תחילה", "Version to restore":"גרסה לשחזור", "Preview restore":"תצוגה מקדימה של השחזור", "Restore in working copy":"שחזור בעותק העבודה", "Ready to restore":"מוכן לשחזור", "No retained file history":"אין היסטוריית קבצים שמורה", "Working copy only":"עותק העבודה בלבד",
"Update saved work in an ordinary folder":"עדכון עבודה שמורה בתיקייה רגילה", "Original or destination folder":"תיקיית המקור או היעד", "Selected destination":"היעד שנבחר", "No destination selected":"לא נבחר יעד", "Or type a destination folder":"או הזנת תיקיית יעד", "Use typed destination":"שימוש ביעד שהוזן", "One saved file":"קובץ שמור אחד", "Choose a saved file":"בחירת קובץ שמור", "Verified preview":"תצוגה מקדימה מאומתת", "Preview verified":"התצוגה המקדימה אומתה", "Exact destination plan":"תוכנית מדויקת לתיקיית היעד", "Explicit and staged":"מפורש ובשלבים", "Mesh previews and rechecks saved content before any destination write.":"Mesh מציג ובודק מחדש תוכן שמור לפני כל כתיבה לתיקיית היעד.",
"Confirm exact action":"אישור הפעולה המדויקת", "What changes:":"מה משתנה:", "Undo:":"ביטול:", "Cancel":"ביטול", "Confirm":"אישור", "Close":"סגירה", "Recommended next":"השלב הבא המומלץ", "Recommended next action":"הפעולה הבאה המומלצת",
"Bring in an ordinary project folder. Mesh verifies every file before it creates a private working copy, the original stays untouched, and your recent validated workspaces remain available across restarts.":"בחרו תיקיית פרויקט רגילה. Mesh מאמת כל קובץ לפני יצירת עותק עבודה פרטי. המקור נשאר ללא שינוי, וסביבות העבודה המאומתות האחרונות נשמרות גם לאחר הפעלה מחדש.",
"This preview contains no ordinary project files or folders. Creating it will produce an empty workspace. Choose another folder unless an empty workspace is intentional.":"בתצוגה זו אין קבצים או תיקיות רגילים של הפרויקט. יצירתה תיצור סביבת עבודה ריקה. בחרו תיקייה אחרת, אלא אם רציתם להתחיל בסביבת עבודה ריקה.",
"Counts cover the files Mesh will bring into the native working folder. Mesh applies this project's .gitignore and .meshignore. The source .git directory is never copied as workspace content; for Git projects, Mesh separately recreates independently owned history, branch, and index state in the new working folder. Excluded paths stay only in the original folder.":"הספירה כוללת את הקבצים ש־Mesh ייבא לתיקיית העבודה. כללי .gitignore ו־.meshignore של הפרויקט חלים. תיקיית .git המקורית אינה מועתקת כתוכן; בפרויקטי Git, ההיסטוריה, הענף והאינדקס נוצרים בנפרד בתיקייה החדשה. נתיבים שהוחרגו נשארים רק במקור.",
"Create empty workspace":"יצירת סביבת עבודה ריקה",
"Create workspace and open folder":"יצירת סביבת עבודה ופתיחת התיקייה",
"Creating private workspace…":"יוצר סביבת עבודה פרטית…",
"Connecting original folder…":"מחבר את תיקיית המקור…",
"Connect original folder":"חיבור תיקיית המקור",
"Checking local service":"בודק את השירות המקומי",
"Local service ready":"השירות המקומי מוכן",
"Local service needs attention":"השירות המקומי דורש טיפול",
"Start Codex on this version":"הפעלת Codex על גרסה זו",
"Finish agent handoff":"סיום העבודה עם הסוכן",
"Keep agent assigned":"השארת הסוכן משויך",
"Open in working folder":"פתיחה בתיקיית העבודה",
"Start Codex on this point":"הפעלת Codex מנקודה זו",
"Start another agent from this point":"הפעלת סוכן נוסף מנקודה זו",
"Independent agent folder":"תיקייה עצמאית לסוכן",
"Agent folder":"תיקיית הסוכן",
"Create text file":"יצירת קובץ טקסט",
"Create folder":"יצירת תיקייה",
"Move or rename":"העברה או שינוי שם",
"Delete entry":"מחיקת פריט",
"Open":"פתיחה",
"Reveal":"הצגה ב־Finder",
"Open file":"פתיחת קובץ",
"Preserve edit":"שמירת העריכה",
"Record move or deletion":"שמירת העברה או מחיקה",
"Refresh safely":"רענון בטוח",
"Review conditions":"סקירת התנאים",
"Return to the edit":"חזרה לעריכה",
"Inspect changes":"בדיקת השינויים",
"Create working folder":"יצירת תיקיית עבודה",
"Choose saved version":"בחירת גרסה שמורה",
"Inspect review":"בדיקת הסקירה",
"Setting up approvals…":"מגדיר אישורים…",
"Review approval":"סקירת האישור",
"Choose export folder":"בחירת תיקיית ייצוא",
"Approval unavailable":"האישור אינו זמין",
"Set up approvals":"הגדרת אישורים",
"Preview original update":"תצוגה מקדימה לעדכון המקור",
"Choose folder":"בחירת תיקייה",
"Preview one file":"תצוגה מקדימה לקובץ אחד",
"Replace existing file":"החלפת קובץ קיים",
"Create file":"יצירת קובץ",
"Preview saved workspace":"תצוגה מקדימה לסביבת העבודה השמורה",
"Undo last restore":"ביטול השחזור האחרון",
"Replace saved file":"החלפת קובץ שמור",
"Create saved file":"יצירת קובץ שמור",
"Keep destination unchanged":"השארת היעד ללא שינוי",
"Roll back managed copy":"ביטול העותק המנוהל",
"Keep workspace":"השארת סביבת העבודה",
"Delete file":"מחיקת קובץ",
"Delete folder":"מחיקת תיקייה",
"Keep entry":"השארת הפריט",
"Preparing workspace controls…":"מכין את בקרי סביבת העבודה…",
"Preparing folder import…":"מכין ייבוא תיקייה…",
"Preparing workspace summary…":"מכין סיכום סביבת עבודה…",
"Preparing current workspace…":"מכין את סביבת העבודה הנוכחית…",
"Preparing files…":"מכין קבצים…",
"Preparing changes…":"מכין שינויים…",
"Preparing review…":"מכין סקירה…",
"Preparing versions…":"מכין גרסאות…",
"Preparing destination…":"מכין יעד…",
"Preparing restore…":"מכין שחזור…",
"Import folder":"ייבוא תיקייה",
"Choose a file and a saved version, then inspect the change before replacing the file in your working folder. Private history is not rewritten.":"בחרו קובץ וגרסה שמורה ובדקו את השינוי לפני החלפת הקובץ בתיקיית העבודה. ההיסטוריה הפרטית אינה משתנה.",
"Deletion accepts files and empty folders and requires confirmation. Saved file content remains in immutable history.":"ניתן למחוק קבצים ותיקיות ריקות בלבד, לאחר אישור. תוכן קבצים שנשמר נשאר בהיסטוריה שאינה ניתנת לשינוי.",
"Review the working set, compare exact bytes, then save selected work privately.":"סקרו את קבצי העבודה, השוו את התוכן המדויק ושמרו את העבודה שנבחרה באופן פרטי.",
"Before and after are exact immutable saved sides. They are not the writable workspace.":"התצוגות לפני ואחרי הן גרסאות שמורות מדויקות שאינן ניתנות לשינוי, ולא סביבת העבודה הניתנת לעריכה.",
"This stable path follows the version opened in Mesh.":"הנתיב הקבוע הזה עוקב אחר הגרסה שנפתחה ב־Mesh.",
"Existing editors and agents keep their current directory handle. Reopen them only when they should follow the newly selected working folder.":"עורכים וסוכנים שכבר פועלים נשארים מחוברים לתיקייה שלהם. פתחו אותם מחדש רק כדי שיעבדו בתיקיית העבודה החדשה שנבחרה.",
"Mesh verifies the complete point before it can open an independent native folder. The workspace you leave stays untouched.":"Mesh מאמת את נקודת השמירה כולה לפני פתיחת תיקייה עצמאית. סביבת העבודה שממנה עוברים נשארת ללא שינוי.",
"Type an absolute folder path, then choose Use typed destination or press Enter. The selected destination above is the value Mesh will preview.":"הזינו נתיב מלא לתיקייה ובחרו שימוש ביעד שהוזן או לחצו Enter. Mesh יציג תצוגה מקדימה עבור היעד הנבחר שמופיע למעלה.",
"Preview the selected file against the destination, then create or replace it only if the exact preview remains current.":"השוו בתצוגה מקדימה את הקובץ שנבחר ליעד. יצירה או החלפה תתאפשר רק כל עוד התצוגה המדויקת עדיין עדכנית.",
"Preview folders and files together. Mesh creates reviewed missing folders first, then automatically re-previews the files and updates only the verified changed set after confirmation.":"הציגו תיקיות וקבצים יחד בתצוגה מקדימה. Mesh יוצר תחילה תיקיות חסרות שאושרו, בודק שוב את הקבצים ומעדכן רק את השינויים המאומתים לאחר אישור.",
"Mesh remembers and prefills the original folder used for an import, including after you switch to an older saved version. For a workspace opened manually, choose a destination once. Choose one saved file or the complete saved workspace; Mesh verifies the destination and shows the exact create, replace, or removal plan before a separate confirmation can write anything. Every file is rechecked and installed atomically.":"Mesh זוכר וממלא את תיקיית המקור גם לאחר מעבר לגרסה שמורה קודמת. בסביבת עבודה שנפתחה ידנית, בחרו יעד פעם אחת. בחרו קובץ שמור או סביבת עבודה שלמה; Mesh מאמת את היעד ומציג תוכנית מדויקת ליצירה, החלפה או הסרה לפני אישור נפרד לכתיבה. כל קובץ נבדק שוב ומותקן באופן אטומי.",
"Mesh creates folders and updates current files first. After current paths are installed, Mesh derives former saved paths for a separate reviewed removal step. Only paths proven to come from the original import or an exact durable update receipt are eligible; recursive deletion is unavailable. Private-only, changed, replaced, or unrelated destination entries are preserved, and Mesh never removes a destination entry silently. A batch never rolls back an earlier completed prefix.":"Mesh יוצר תחילה תיקיות ומעדכן קבצים נוכחיים. לאחר מכן מוצגים נתיבים קודמים להסרה בשלב נפרד. רק נתיבים שהוכח שהגיעו מהייבוא המקורי או מעדכון מתועד זכאים להסרה; מחיקה רקורסיבית אינה זמינה. פריטים פרטיים, שהשתנו, שהוחלפו או שאינם קשורים נשמרים. אין הסרה שקטה, ופעולות שכבר הושלמו אינן מתבטלות אם האצווה נעצרת.",
"Diagnostics exclude file contents and paths. Rollback succeeds only while the managed copy matches its receipt.":"האבחון אינו כולל תוכן קבצים או נתיבים. הביטול מצליח רק כל עוד העותק המנוהל תואם לתיעוד שלו.",
"Native preview required":"נדרשת תצוגה מקדימה מקומית",
"Inline preview unavailable":"תצוגה מקדימה בתוך Mesh אינה זמינה",
"Loading exact file preview…":"טוען תצוגה מקדימה של הקובץ המדויק…",
"Mesh is verifying the current working bytes before showing content.":"Mesh מאמת את תוכן קובץ העבודה לפני הצגתו.",
"Use Open in Finder to browse this exact folder, or expand it in Explorer.":"בחרו פתיחה ב־Finder כדי לעיין בתיקייה המדויקת, או הרחיבו אותה בסייר.",
"In custody":"באחסון מוגן",
"Repository actions":"פעולות הפרויקט",
"Navigate inspectable changes":"ניווט בשינויים שניתן לבדוק",
"How Mesh handles working changes":"איך Mesh מטפל בשינויי עבודה",
"Identity and working-tree state":"זהות ומצב קבצי העבודה",
"Auto-save safe changes":"שמירה אוטומטית של שינויים בטוחים",
"Choose a file or folder":"בחירת קובץ או תיקייה",
"Check the working folder":"בדיקת תיקיית העבודה",
"Checking folder…":"בודק את התיקייה…",
"Source control":"ניהול שינויים",
"Source control collapsed":"ניהול השינויים מכווץ",
"WORKING":"בעבודה",
"Working tree":"קבצי העבודה",
"Show Changes":"הצגת שינויים",
"Hide":"הסתרה",
"Review current folder changes":"סקירת שינויים בתיקייה הנוכחית",
"Search working changes":"חיפוש שינויי עבודה",
"No working changes":"אין שינויי עבודה",
"No matching changes":"אין שינויים תואמים",
"No changed files match these filters.":"אין קבצים שהשתנו התואמים לסינון.",
"No files match this filter.":"אין קבצים התואמים לסינון.",
"Adjust the search or status filter.":"שנו את החיפוש או את סינון המצב.",
"Select a working change":"בחירת שינוי בעבודה",
"Filter changed files…":"סינון קבצים שהשתנו…",
"Filter changes by status":"סינון שינויים לפי מצב",
"Folder check incomplete":"בדיקת התיקייה לא הושלמה",
"Retry the folder check before saving or review.":"יש לנסות שוב את בדיקת התיקייה לפני שמירה או סקירה.",
"Run a folder check to compare current bytes with private history.":"הפעילו בדיקת תיקייה כדי להשוות את התוכן הנוכחי להיסטוריה הפרטית.",
"Mesh is comparing current bytes with private history.":"Mesh משווה את התוכן הנוכחי להיסטוריה הפרטית.",
"Mesh could not complete an exact comparison. Retry before trusting or saving this view.":"Mesh לא הצליח להשלים השוואה מדויקת. נסו שוב לפני שמירה או הסתמכות על תצוגה זו.",
"The native folder matches private history exactly.":"תיקיית העבודה תואמת בדיוק להיסטוריה הפרטית.",
"The native folder matches the latest private version. Edit a file in your usual app, then check again.":"תיקיית העבודה תואמת לגרסה הפרטית האחרונה. ערכו קובץ ביישום הרגיל שלכם ובדקו שוב.",
"Check the native folder, then select a changed file to see its exact inline or split diff here.":"בדקו את תיקיית העבודה ובחרו קובץ שהשתנה כדי לראות כאן השוואה מדויקת, רציפה או מפוצלת.",
"Choose an inspectable file from Source control to see its exact inline or split diff.":"בחרו קובץ שניתן לבדוק מתוך ניהול השינויים כדי לראות השוואה מדויקת, רציפה או מפוצלת.",
"This workspace has no files or folders yet.":"בסביבת עבודה זו אין עדיין קבצים או תיקיות.",
"Binary or large content stays outside the text editor. Mesh still tracks and saves it by exact identity.":"תוכן בינארי או גדול אינו מוצג בעורך הטקסט. Mesh עדיין עוקב אחריו ושומר אותו לפי זהותו המדויקת.",
"Use Files to inspect an exact workspace entry.":"השתמשו בקבצים כדי לבדוק פריט מדויק בסביבת העבודה.",
"Inspected working text":"טקסט עבודה שנבדק",
"Text workspace view":"תצוגת טקסט בסביבת העבודה",
"Content diff layout":"פריסת השוואת תוכן",
"Preview unavailable":"התצוגה המקדימה אינה זמינה",
"Previewing the first":"מציג תצוגה מקדימה של",
"lines. Open the exact file for the complete content.":"השורות הראשונות. פתחו את הקובץ המדויק לתוכן המלא.",
"Showing changes":"מציג שינויים",
"Showing the first":"מציג את הפריטים הראשונים מתוך",
" shown":" מוצגים",
"Missing tracked file":"קובץ במעקב חסר",
"Resolve missing file":"טיפול בקובץ חסר",
"Find a missing tracked file":"חיפוש קובץ חסר במעקב",
"Filter missing files…":"סינון קבצים חסרים…",
"Find a possible destination":"חיפוש יעד אפשרי",
"Filter possible destinations…":"סינון יעדים אפשריים…",
"Resolution":"פתרון",
"It was deleted":"הקובץ נמחק",
"Agent folder assigned":"תיקייה משויכת לסוכן",
"Agent folder available":"תיקיית סוכן זמינה",
"No workspace or agent matches this search.":"אין סביבת עבודה או סוכן התואמים לחיפוש.",
"No reported conditions.":"לא דווחו מצבים הדורשים טיפול.",
"Open another version":"פתיחת גרסה אחרת",
"Return to previous workspace":"חזרה לסביבת העבודה הקודמת",
"Files in this point":"קבצים בנקודת שמירה זו",
"No destination selected.":"לא נבחר יעד.",
"Choose a destination and preview one file or the saved workspace. No destination entry changes until you review a plan and confirm it.":"בחרו יעד והציגו קובץ או סביבת עבודה שמורה בתצוגה מקדימה. שום פריט ביעד לא ישתנה עד לסקירת התוכנית ואישורה.",
"Select an earlier saved version and preview it. Mesh will verify the exact retained bytes and the current working file before Restore becomes available.":"בחרו גרסה שמורה קודמת והציגו אותה בתצוגה מקדימה. Mesh יאמת את התוכן השמור המדויק ואת קובץ העבודה לפני שהשחזור יתאפשר.",
"Restore is currently unavailable.":"השחזור אינו זמין כרגע.",
"Resolve the active workspace condition before applying this verified preview.":"יש לטפל במצב הפעיל בסביבת העבודה לפני החלת התצוגה המאומתת.",
"Custom private location":"מיקום פרטי מותאם",
"No":"לא",
"Yes":"כן",
"Bytes":"בתים",
"Executable":"ניתן להרצה",
"Digest":"סיכום אימות",
"Exact file metadata":"נתונים מדויקים על הקובץ",
"Saved file metadata comparison":"השוואת נתוני קבצים שמורים",
"Inert":"ללא הרצה",
"document":"מסמך",
"image":"תמונה",
"All sections":"כל החלקים",
"Artifact section":"חלק במסמך",
"Document section comparison":"השוואת חלקי מסמך",
"Section":"חלק",
"Previous section":"החלק הקודם",
"Next section":"החלק הבא",
"Load content comparison":"טעינת השוואת תוכן",
"Try content comparison again":"ניסיון נוסף להשוואת תוכן",
"Reading exact versions…":"קורא את הגרסאות המדויקות…",
"Reading…":"קורא…",
"PDF page comparison":"השוואת עמודי PDF",
"PDF page content comparison":"השוואת תוכן עמודי PDF",
"Earlier recorded reviews":"סקירות קודמות שנשמרו",
"Earlier saved reviews":"סקירות שמורות קודמות",
"Approve and create Git branch":"אישור ויצירת ענף Git",
"Create Git branch":"יצירת ענף Git",
"Filter live changes":"סינון שינויים חיים",
"Live changed files":"קבצים שהשתנו בעבודה חיה",
"No live changes match this filter.":"אין שינויים חיים התואמים לסינון.",
"No live file changes are currently visible.":"אין כרגע שינויי קבצים חיים להצגה.",
"Stable live file snapshot":"תמונת מצב יציבה של קובץ חי",
"Stable snapshot unavailable":"תמונת מצב יציבה אינה זמינה",
"Inspect stable snapshot":"בדיקת תמונת מצב יציבה",
"Retry snapshot":"ניסיון נוסף לתמונת מצב",
"Mutable working file · exact snapshot required":"קובץ עבודה משתנה · נדרשת תמונת מצב מדויקת",
"Choose Inspect stable snapshot to read this changing file twice under exact agent custody.":"בחרו בדיקת תמונת מצב יציבה כדי לקרוא את הקובץ המשתנה פעמיים תוך אימות השליטה של הסוכן.",
"Choose an assigned workspace above, or start an agent from Current. Saved Review remains available separately.":"בחרו סביבת עבודה משויכת למעלה או הפעילו סוכן מתוך נוכחי. סקירת גרסאות שמורות זמינה בנפרד.",
"This saved path is currently missing. There are no live bytes to preview.":"הנתיב השמור חסר כעת. אין תוכן חי לתצוגה מקדימה.",
"This is a new folder. Finish agent handoff will authoritatively inspect its complete descendants.":"זוהי תיקייה חדשה. סיום העבודה עם הסוכן יבדוק את כל תוכנה.",
"Mesh will not follow or preview this unsupported entry. Remove or replace it with a regular file, then retry.":"Mesh לא יעקוב אחר פריט זה ולא יציג אותו, כי סוגו אינו נתמך. הסירו אותו או החליפו אותו בקובץ רגיל ונסו שוב.",
"Wait for the current write to finish, then retry. Nothing was recorded or saved.":"המתינו לסיום הכתיבה הנוכחית ונסו שוב. דבר לא תועד או נשמר.",
"Read-only snapshot from the assigned agent folder. Selecting the file again refreshes it; Mesh never saves from this preview.":"תמונת מצב לקריאה בלבד מתיקיית הסוכן המשויך. בחירה חוזרת בקובץ מרעננת אותה; Mesh אינו שומר מתוך תצוגה זו.",
"Monitoring never saves or approves work. Finish agent handoff still performs the authoritative complete scan before the work enters private history and Review.":"המעקב אינו שומר או מאשר עבודה. סיום העבודה עם הסוכן מבצע את הסריקה המלאה לפני שהעבודה נכנסת להיסטוריה הפרטית ולסקירה.",
"This folder has no importable files or folders. Choose another folder containing project content. No workspace can be created from this preview.":"בתיקייה זו אין קבצים או תיקיות שניתן לייבא. בחרו תיקייה אחרת המכילה תוכן של פרויקט. לא ניתן ליצור סביבת עבודה מתצוגה מקדימה זו.",
"Choose a folder with content":"בחירת תיקייה עם תוכן",
"Finish this agent handoff?":"לסיים את העבודה עם הסוכן?",
"Mark this agent folder finished only after every Codex session, terminal agent, and editor using its pinned path has stopped. Mesh will inspect the complete folder and privately save unambiguous file and folder changes. Renames, deletions, and unsupported entries will remain for your review.":"סמנו את העבודה בתיקיית הסוכן כהסתיימה רק לאחר שכל הפעלות Codex, סוכני המסוף והעורכים המשתמשים בנתיב הקבוע שלה נעצרו. Mesh יבדוק את כל התיקייה וישמור באופן פרטי שינויים חד־משמעיים בקבצים ובתיקיות. שינויי שם, מחיקות ופריטים לא נתמכים יישארו לסקירתכם.",
"Reopen this assigned Codex folder?":"לפתוח מחדש את תיקיית Codex המשויכת?",
"Reopen this assigned agent terminal?":"לפתוח מחדש מסוף לסוכן המשויך?",
"Reopen Codex folder":"פתיחה מחדש של תיקיית Codex",
"Reopen agent terminal":"פתיחה מחדש של מסוף הסוכן",
"This exact writable folder was already handed to an agent. Two agents in one folder can overwrite each other. Use Start another agent copy for concurrent work. Reopen this folder only if the prior agent has stopped. Reopen assigned Codex folder?":"תיקיית העבודה הזו כבר נמסרה לסוכן. שני סוכנים באותה תיקייה עלולים לדרוס זה את עבודתו של זה. לעבודה במקביל, הפעילו עותק נוסף לסוכן. פתחו תיקייה זו מחדש רק אם הסוכן הקודם נעצר. לפתוח מחדש את תיקיית Codex המשויכת?",
"This exact writable folder was already handed to an agent. Two agents in one folder can overwrite each other. Use Start another agent copy for concurrent work. Reopen this folder only if the prior agent has stopped. Reopen an agent terminal?":"תיקיית העבודה הזו כבר נמסרה לסוכן. שני סוכנים באותה תיקייה עלולים לדרוס זה את עבודתו של זה. לעבודה במקביל, הפעילו עותק נוסף לסוכן. פתחו תיקייה זו מחדש רק אם הסוכן הקודם נעצר. לפתוח מחדש מסוף לסוכן?",
"Remove this managed workspace?":"להסיר סביבת עבודה מנוהלת זו?",
"Edit here or work normally in the stable native folder with a local editor. Give Terminal or a long-running agent the independent agent folder shown under Current; it starts at the selected durable version and then remains writable even if Mesh switches elsewhere. Returning to Mesh automatically inspects the selected folder; selecting a different recent agent folder inspects it immediately, while inactive agent folders are not continuously watched. Find folder changes retries the read explicitly.":"ערכו כאן או עבדו כרגיל בתיקיית העבודה הקבועה עם עורך מקומי. למסוף או לסוכן ממושך תנו את תיקיית הסוכן העצמאית המוצגת תחת נוכחי; היא מתחילה מהגרסה השמורה שנבחרה ונשארת ניתנת לעריכה גם אם Mesh עובר למקום אחר. החזרה ל־Mesh בודקת אוטומטית את התיקייה שנבחרה. בחירת תיקיית סוכן אחרונה אחרת בודקת אותה מיד; תיקיות סוכן לא פעילות אינן במעקב רציף. איתור שינויים בתיקייה מבצע קריאה מפורשת נוספת.",
"Inspect re-reads exact operating-system bytes; binary and large files stay outside the text editor but remain savable. Choose Save privately to sign and append one inspected file. Mesh reviews a complete new folder tree and admits its folders parent-first. Outside the confirmed agent-finish flow, saving remains an explicit authenticated action. Choose Save all privately for the complete inspected queue. Automatic save uses the same complete scan, reinspection, signature, and post-save verification. It pauses for deletions, renames, symbolic links, special entries, active agent handoffs, or files that keep changing. Mesh stops on the first mismatch.":"הבדיקה קוראת מחדש את תוכן הקבצים המדויק ממערכת ההפעלה; קבצים בינאריים וגדולים אינם מוצגים בעורך הטקסט אך ניתן לשמור אותם. שמירה פרטית חותמת ושומרת קובץ שנבדק. Mesh בודק עץ תיקיות חדש במלואו ומוסיף תיקיות אב לפני ילדיהן. מחוץ לתהליך המאושר של סיום עבודת סוכן, השמירה היא פעולה מפורשת ומאומתת. שמירת הכול באופן פרטי שומרת את כל התור שנבדק. שמירה אוטומטית משתמשת באותה סריקה מלאה, בדיקה חוזרת, חתימה ואימות לאחר שמירה. היא נעצרת במחיקות, בשינויי שם, בקישורים סמליים, בפריטים מיוחדים, בזמן עבודה עם סוכן או כשקבצים ממשיכים להשתנות. Mesh עוצר באי־ההתאמה הראשונה.",
"Exporting a separate copy, confirming review, and approving are independent actions. It does not approve or change the original folder. Agents and web content cannot skip the native user-presence approval ceremony.":"ייצוא עותק נפרד, אישור השלמת סקירה ואישור מוגן הם פעולות עצמאיות. הייצוא אינו מאשר או משנה את תיקיית המקור. סוכנים ותוכן אינטרנט אינם יכולים לעקוף את תהליך האישור המקומי הדורש נוכחות משתמש.",
"Use the stable folder for Finder and editors, or the independent real folder for Terminal and agents. The independent folder is writable and does not move when Mesh switches elsewhere. Return here to inspect changes, save a private version, open another version, or update the original folder from saved work.":"השתמשו בתיקייה הקבועה עבור Finder ועורכים, או בתיקייה העצמאית למסוף ולסוכנים. התיקייה העצמאית ניתנת לעריכה ואינה עוברת מקום כאשר Mesh עובר לגרסה אחרת. חזרו לכאן לבדיקת שינויים, שמירת גרסה פרטית, פתיחת גרסה אחרת או עדכון תיקיית המקור מתוך עבודה שמורה.",
"Keep reviewing":"המשך סקירה",
"Update changed files":"עדכון קבצים שהשתנו"
});
