/** Reviewed UI copy only. Paths, file contents, protocol values and native diagnostics are never translated. */
export const hebrew: Readonly<Record<string, string>> = Object.freeze({
"Read recorded execution": "קריאת היסטוריית הביצוע",
"Last recorded execution": "מצב הביצוע האחרון שנרשם",
"Recorded revision": "גרסה מתועדת",
"Launch recorded; progress unknown": "נרשמה הפעלה; ההתקדמות אינה ידועה",
"Worker setup incomplete": "הכנת סביבת הסוכן לא הושלמה",
"Agent launch recorded": "נרשמה הפעלת סוכן",
"Agent activity recorded": "נרשמה פעילות סוכן",
"Waiting for input or dependencies": "ממתין לקלט או לתלויות",
"Execution needs reconciliation": "נדרשת בדיקת מצב הביצוע",
"Stop requested; termination unconfirmed": "התבקשה עצירה; סיום התהליך לא אומת",
"Successful completion recorded": "נרשם סיום מוצלח",
"Failed completion recorded": "נרשם סיום בכישלון",
"Cancellation completion recorded": "נרשם סיום בעקבות ביטול",
"Execution state unavailable": "מצב הביצוע אינו זמין",
"This is saved execution history. It does not confirm current process activity, release capacity, or authorize another attempt.": "זו היסטוריית ביצוע שמורה. היא אינה מאמתת פעילות נוכחית של התהליך, משחררת קיבולת או מתירה ניסיון נוסף.",

"Recover original worker workspace": "שחזור סביבת העבודה המקורית של הסוכן",
"Recover the original saved input after interrupted setup. This may start its assigned agent once setup is recovered. Existing or uncertain execution cannot be restarted here.": "שחזור הקלט המקורי שנשמר לאחר שההכנה נקטעה. פעולה זו עשויה להפעיל את הסוכן שהוקצה לאחר השלמת ההכנה. לא ניתן להפעיל מחדש מכאן ביצוע קיים או שמצבו אינו ודאי.",
"The original workspace setup was recovered. Read worker status to check execution; recovery does not prove that the agent is running.": "הכנת סביבת העבודה המקורית שוחזרה. קראו את מצב הסוכן כדי לבדוק את הביצוע; השחזור אינו מוכיח שהסוכן פועל.",
"Recovery could not be confirmed. Keep this attempt and read worker status before another action.": "לא ניתן לאמת את השחזור. שמרו את הניסיון הזה וקראו את מצב הסוכן לפני פעולה נוספת.",

  "Original input inspection": "בדיקת הקלט המקורי",
  "Inspect original input": "בדיקת הקלט המקורי",
  "Check the original saved input on the worker. This can take time for large inputs and does not resume or restart work.": "בדיקת הקלט המקורי שנשמר אצל הסוכן. בדיקת קלט גדול עשויה לקחת זמן ואינה מחדשת או מפעילה מחדש עבודה.",
  "The original input was verified at the observation time. This does not establish that an agent is running or can be restarted.": "הקלט המקורי אומת בזמן התצפית. אין בכך הוכחה שסוכן פועל או שניתן להפעילו מחדש.",
  "The worker has no retained input record. This does not prove that no work was started.": "לסוכן אין רשומת קלט שמורה. אין בכך הוכחה שלא התחילה עבודה.",
  "The worker could not verify the original input. Preserve the existing attempt for reconciliation.": "הסוכן לא הצליח לאמת את הקלט המקורי. יש לשמור את הניסיון הקיים לצורך בירור.",

"Saved remote reviews":"סקירות מרוחקות שמורות",
"Fleet status has not loaded for these saved reviews.":"מצב הצי טרם נטען עבור הסקירות השמורות האלה.",
"Sending input authorizes the configured worker to begin this attempt. A delivery receipt alone does not prove the agent started successfully.":"שליחת הקלט מאפשרת למחשב המרוחק שהוגדר להתחיל את הניסיון הזה. אישור מסירה לבדו אינו מוכיח שהסוכן התחיל בהצלחה.",
"Prepare new remote work":"הכנת עבודה מרוחקת חדשה",
"Choose saved work and retain its exact request before sending input. No existing attempt is needed. The fixed lease lasts fifteen minutes from preparation.":"בחרו עבודה שמורה ושמרו את הבקשה המדויקת לפני שליחת הקלט. אין צורך בניסיון קיים. ההרשאה הקבועה תקפה לחמש עשרה דקות מרגע ההכנה.",
"Save remote creation request":"שמירת בקשה ליצירת עבודה מרוחקת",
"To prepare a different request, clear and reselect the native setup files. Existing saved requests remain available.":"להכנת בקשה אחרת, נקו ובחרו מחדש את קובצי ההגדרה. בקשות שכבר נשמרו נשארות זמינות.",
"Saved remote creation requests":"בקשות שמורות ליצירת עבודה מרוחקת",
"Load saved requests":"טעינת בקשות שמורות",
"Inspect original creation attempt":"בדיקת ניסיון היצירה המקורי",
"Send saved input to worker":"שליחת הקלט השמור למחשב המרוחק",
"Input delivery was confirmed. This does not establish that an agent is running.":"מסירת הקלט אושרה. אין בכך הוכחה שסוכן פועל.",
"A retained fleet exists. Inspect its selected attempt and resume only the original input transfer if needed.":"קיים צי שמור. בדקו את הניסיון שנבחר והמשיכו רק את העברת הקלט המקורית במידת הצורך.",
"The request is retained. Sending input is a separate explicit action.":"הבקשה נשמרה. שליחת הקלט היא פעולה מפורשת ונפרדת.",
"No saved remote creation requests were returned.":"לא הוחזרו בקשות שמורות ליצירת עבודה מרוחקת.",
"Remote creation could not be confirmed. Load saved requests and inspect the original attempt before another action.":"לא ניתן לאשר את יצירת העבודה המרוחקת. טענו בקשות שמורות ובדקו את הניסיון המקורי לפני פעולה נוספת.",
"Working with the remote connection…":"מבצע פעולה בחיבור המרוחק…",

"Download for review":"הורד לבדיקה",
"Listing a result does not download or accept it. Download creates a private copy for review.":"הצגת תוצאה אינה מורידה או מאשרת אותה. הורדה יוצרת עותק פרטי לבדיקה.",
"Saved downloads":"הורדות שמורות",
"Load saved downloads":"טען הורדות שמורות",
"Recover only the saved download attempt. A completed copy is checked again; interrupted work may resume. This does not start agents or approve work.":"שחזר רק את ניסיון ההורדה השמור. עותק שהושלם נבדק מחדש; עבודה שנקטעה עשויה להתחדש. פעולה זו אינה מפעילה סוכנים או מאשרת עבודה.",
"No saved downloads for this connection.":"אין הורדות שמורות לחיבור זה.",
"Check or resume saved download":"בדוק או המשך הורדה שמורה",
"A private saved copy is ready for review. It has not been approved or applied to the original project.":"עותק פרטי שמור מוכן לבדיקה. הוא לא אושר ולא הוחל על הפרויקט המקורי.",
"Show downloaded reviews":"הצג בדיקות של תוצאות שהורדו",
"Download could not be confirmed. Use saved downloads to check the original attempt. No work was approved or applied.":"לא ניתן לאמת את ההורדה. השתמש בהורדות שמורות לבדיקת הניסיון המקורי. לא אושרה ולא הוחלה עבודה.",
"Saved downloads are unavailable for this connection.":"ההורדות השמורות אינן זמינות לחיבור זה.",

"More saved results exist beyond this page.":"קיימות תוצאות שמורות נוספות מעבר לעמוד זה.",
"Next results":"תוצאות הבאות",
"Previous results":"תוצאות קודמות",
"Result offer":"הצעת תוצאה",
"Result manifest":"מפרט התוצאה",
"Review identity":"זהות הסקירה",
"Result identities":"זהויות התוצאה",
"These results are listed but have not been downloaded or accepted.":"התוצאות מופיעות ברשימה אך עדיין לא הורדו ולא התקבלו.",
"Saved remote results":"תוצאות שמורות מהסוכן המרוחק",
"Resume saved input transfer":"המשך העברת הקלט השמור",
"Resume only the original interrupted input transfer. The worker must still retain its reservation. This does not create another attempt or extend its lease.":"המשיכו רק את העברת הקלט המקורית שנקטעה. ההקצאה המקורית חייבת עדיין להיות שמורה אצל הסוכן. הפעולה אינה יוצרת ניסיון נוסף ואינה מאריכה את תוקף ההקצאה.",
"The saved input is materialized on the worker. This does not establish that an agent is running.":"הקלט השמור נוצר במחשב הסוכן. אין בכך הוכחה שסוכן פועל.",
"The worker retained the saved input. This does not establish that an agent is running.":"הסוכן שמר את הקלט. אין בכך הוכחה שסוכן פועל.",
"Input transfer outcome could not be confirmed. Keep the original assignment, inspect worker status, and resume only explicitly. No new attempt was requested.":"לא ניתן לאמת את תוצאת העברת הקלט. שמרו את ההקצאה המקורית, בדקו את מצב הסוכן והמשיכו רק במפורש. לא התבקש ניסיון חדש.",

"The active selection lasts until Mesh closes. Saved settings must be opened explicitly. Reading observations does not start agents or approve work.":"הבחירה הפעילה נשמרת עד לסגירת Mesh. יש לפתוח הגדרות שמורות במפורש. קריאת המצב אינה מפעילה סוכנים ואינה מאשרת עבודה.",
"Use an existing coordinator identity and SSH files. Mesh does not create keys or enroll host trust. Use Save current connection to keep these settings for later.":"השתמשו בזהות מתאם קיימת ובקובצי SSH קיימים. Mesh אינו יוצר מפתחות ואינו מוסיף אמון במארחים. שמרו את החיבור הנוכחי כדי להשתמש בהגדרות בהמשך.",
"Saved worker connections":"חיבורים שמורים לסוכנים",
"Saved connections":"חיבורים שמורים",
"Load saved connections":"טעינת חיבורים שמורים",
"Recover interrupted settings save":"שחזור שמירת הגדרות שנקטעה",
"Open saved settings":"פתיחת הגדרות שמורות",
"Remove saved settings":"הסרת הגדרות שמורות",
"Connection name":"שם החיבור",
"Save current connection":"שמירת החיבור הנוכחי",
"Open saved settings to use or edit them. Mesh checks the original files and identities again. Opening settings does not contact the worker.":"פתחו הגדרות שמורות כדי להשתמש בהן או לערוך אותן. Mesh בודק שוב את הקבצים והזהויות המקוריים. פתיחת ההגדרות אינה יוצרת קשר עם הסוכן.",
"After opening and editing saved settings, save the current connection to replace that entry. Removing settings keeps the active selection, credentials and work history.":"לאחר פתיחה ועריכה של הגדרות שמורות, שמרו את החיבור הנוכחי כדי לעדכן את הרשומה. הסרת הגדרות משאירה את הבחירה הפעילה, פרטי ההזדהות והיסטוריית העבודה.",

"Connection settings last until Mesh closes. Reading observations does not start agents or approve work.":"הגדרות החיבור נשמרות עד לסגירת Mesh. קריאת המצב אינה מפעילה סוכנים ואינה מאשרת עבודה.",
"Set up a worker connection":"הגדרת חיבור לסוכן",
"Use an existing coordinator identity and SSH files. Mesh does not create keys or enroll host trust. Settings apply to this session only.":"השתמשו בזהות מתאם קיימת ובקובצי SSH קיימים. Mesh אינו יוצר מפתחות ואינו מוסיף אמון במארחים. ההגדרות חלות רק על ההפעלה הנוכחית.",
"Choose coordinator identity folder":"בחירת תיקיית זהות המתאם",
"Choose private SSH identity":"בחירת מפתח SSH פרטי",
"Choose trusted hosts file":"בחירת קובץ מארחים מהימנים",
"Clear selected setup files":"ניקוי בחירת קובצי ההגדרה",
"Worker address":"כתובת הסוכן",
"Connection account":"חשבון החיבור",
"Connection port":"יציאת החיבור",
"Worker public identity":"הזהות הציבורית של הסוכן",
"Choose fleet":"בחירת צי",
"Choose lane with an existing attempt":"בחירת מסלול עם ניסיון הפעלה קיים",
"Use these connection settings":"שימוש בהגדרות החיבור האלה",
"Using settings does not contact the worker. Read its status explicitly after setup; recorded local attempts may not have a remote assignment.":"שימוש בהגדרות אינו יוצר קשר עם הסוכן. קראו את מצבו לאחר ההגדרה; ייתכן שלניסיונות הפעלה מקומיים אין משימה מרוחקת.",
"Not selected":"לא נבחר",
"Inspect a remote worker":"בדיקת סוכן במחשב מרוחק",
"Choose an existing private coordinator configuration. This selection lasts until Mesh closes. Reading observations does not start agents or approve work.":"בחרו קובץ הגדרות פרטי קיים של המתאם. הבחירה נשמרת עד לסגירת Mesh. קריאת המצב אינה מפעילה סוכנים ואינה מאשרת עבודה.",
"Choose connection configuration":"בחירת הגדרות חיבור",
"Forget this selection":"ביטול הבחירה הזו",
"Worker identity":"זהות הסוכן",
"Read worker status":"קריאת מצב הסוכן",
"Find saved remote results":"איתור תוצאות מרוחקות שמורות",
"Reading native connection information…":"קריאת פרטי החיבור…",
"Remote observation is unavailable. Previous observations may be out of date. Check the signed application, private configuration and worker connection.":"הבדיקה המרוחקת אינה זמינה. ייתכן שהמידע הקודם אינו עדכני. בדקו את חתימת היישום, ההגדרות הפרטיות והחיבור לסוכן.",
"Last verified worker observation":"המצב האחרון שאומת עבור הסוכן",
"The worker recorded this assignment.":"הסוכן רשם את המשימה הזו.",
"The worker has no admission record for this assignment.":"לסוכן אין רשומת קבלה למשימה הזו.",
"A launch record exists. This does not establish that the process is still running.":"קיימת רשומת הפעלה. אין בכך אישור שהתהליך עדיין פועל.",
"No launch record was returned.":"לא התקבלה רשומת הפעלה.",
"Observed at":"זמן הבדיקה",
"Lease ends at":"תוקף ההרשאה מסתיים ב־",
"Saved result history is unavailable for this assignment.":"היסטוריית התוצאות השמורות אינה זמינה למשימה הזו.",
"Saved result offers in this page":"תוצאות שמורות שהוצעו בעמוד הזה",
"Result discovery does not download or accept the work. Use the existing result recovery flow to receive it.":"איתור התוצאות אינו מוריד או מקבל את העבודה. השתמשו בתהליך שחזור התוצאות הקיים כדי לקבל אותה.",
"More saved results exist beyond this first page.":"קיימות תוצאות שמורות נוספות מעבר לעמוד הראשון.",
"This is the received result tree. Prepare a private project version to review it against the original project.":"זו תמונת התוצאה שהתקבלה. הכינו גרסה פרטית של הפרויקט כדי לסקור אותה מול הפרויקט המקורי.",
"Prepare for original project":"הכנה לפרויקט המקורי",
"Remote project actions":"פעולות תוצאה מרוחקת בפרויקט",
"Retry inputs are saved before an action. Reopening does not repeat it. Saving a private version does not approve main or replace working files.":"נתוני הניסיון החוזר נשמרים לפני הפעולה. פתיחה מחדש אינה חוזרת עליה. שמירת גרסה פרטית אינה מאשרת את הגרסה הראשית ואינה מחליפה קובצי עבודה.",
"Reload pending project actions":"טעינה מחדש של פעולות הפרויקט הממתינות",
"Verifying the original project…":"הפרויקט המקורי נבדק…",
"Read saved import status":"קריאת מצב הייבוא השמור",
"Remove retry entry":"הסרת רשומת ניסיון חוזר",
"Removing a retry entry does not delete versions or cancel work.":"הסרת רשומת ניסיון חוזר אינה מוחקת גרסאות ואינה מבטלת עבודה.",
"This exact project action could not be confirmed. Its retry inputs are retained; retry or read its status.":"לא ניתן לאמת את הפעולה המדויקת בפרויקט. נתוני הניסיון החוזר נשמרו; נסו שוב או קראו את מצבה.",
"Pending remote project actions could not be loaded. Retry loading before continuing.":"לא ניתן לטעון את הפעולות המרוחקות הממתינות בפרויקט. נסו לטעון שוב לפני ההמשך.",
"Finish or remove a pending project action before preparing another.":"סיימו או הסירו פעולה ממתינה בפרויקט לפני הכנת פעולה נוספת.",
"The original project could not be verified. Refresh before preparing this result.":"לא ניתן לאמת את הפרויקט המקורי. רעננו לפני הכנת התוצאה.",
"Retry inputs could not be removed. Existing work is retained.":"לא ניתן להסיר את נתוני הניסיון החוזר. העבודה הקיימת נשמרה.",

"Remote result": "תוצאה מרוחקת",
"Received saved snapshot": "תמונת מצב שמורה שהתקבלה",
"Pinned remote review": "סקירה מרוחקת מוצמדת",
"Remote saved reviews": "סקירות מרוחקות שמורות",
"Remote saved results": "תוצאות מרוחקות שמורות",
"Show remote saved results": "הצגת תוצאות מרוחקות שמורות",
"This is the received result tree. Comparison and import into the original project are not available here.": "זו תמונת הקבצים שהתקבלה. השוואה לפרויקט המקורי וייבוא אליו אינם זמינים כאן.",
"These panels stay fixed while agents work. Remote selections currently last for this app session; saved results remain in native history.": "החלוניות נשארות קבועות בזמן שהסוכנים עובדים. הבחירות המרוחקות נשמרות כעת רק במהלך הפעלת היישום; התוצאות נשארות בהיסטוריה המקומית.",
"This page stays fixed. Refresh to discover newer results.": "העמוד נשאר קבוע. רעננו כדי לגלות תוצאות חדשות.",
"No retained remote results in this page.": "אין תוצאות מרוחקות שמורות בעמוד זה.",
"Registration interrupted. This result is not ready for review.": "הרישום נקטע. תוצאה זו עדיין אינה מוכנה לסקירה.",
"Remote results could not be verified. Refresh to retry.": "לא ניתן לאמת את התוצאות המרוחקות. רעננו כדי לנסות שוב.",
"This exact remote review is unavailable. Any displayed content is the previously verified snapshot.": "הסקירה המרוחקת המדויקת אינה זמינה. תוכן שמוצג שייך לתמונת המצב שאומתה קודם.",

"Review applying accepted changes": "סקירה לפני החלת השינויים שאושרו",
"Working files may have changed since this comparison. Applying changes requires fresh native checks and complete text confirmation. Groups can create, replace and remove regular files. Directory changes and incomplete or oversized text confirmations remain unavailable.": "ייתכן שקובצי העבודה השתנו מאז ההשוואה. החלת שינויים דורשת בדיקות חדשות ואישור מלא בחלון היישום. קבוצה יכולה ליצור, להחליף ולהסיר קבצים רגילים. שינויי תיקיות ותצוגות אישור חסרות או גדולות מדי עדיין אינם זמינים.",
"Group reference · inspect to verify its members": "מזהה קבוצה · יש לבדוק כדי לאמת את הקבצים שבה",
"Inspect recovery group": "בדיקת קבוצת שחזור",
"Last group outcome:": "התוצאה האחרונה של הקבוצה:",
"Changes observed": "השינויים נצפו",
"Needs reconciliation": "נדרשת בדיקת התאמה",
"observed": "נצפו",
"uncertain": "לא ודאיים",
"not attempted": "לא נוסו",
"Inspect group outcome": "בדיקת תוצאת הקבוצה",
"Group recovery": "שחזור קבוצה",
"Recovery group:": "קבוצת שחזור:",
"These are separate file observations, not an atomic snapshot. Nothing is retried automatically.": "אלה בדיקות נפרדות של קבצים, ולא תמונת מצב בו־זמנית. שום פעולה אינה מתבצעת שוב אוטומטית.",
"Restoration records in this group": "רשומות שחזור בקבוצה הזו",
"Inspect restoration record": "בדיקת רשומת שחזור",
"More restoration records may exist outside this bounded overview.": "ייתכן שיש רשומות שחזור נוספות שאינן נכללות בתצוגה המוגבלת הזו.",
"Exact file recovery reference within this group": "מזהה שחזור מדויק של קובץ בקבוצה הזו",
"Inspect file in this group": "בדיקת קובץ בקבוצה הזו",
"Already present when prepared; not rewritten or reverified by this view:": "כבר היה קיים בזמן ההכנה; לא נכתב או אומת מחדש בתצוגה הזו:",
"Restoring requires native confirmation. An existing current file is retained in a new recovery entry. Restoring an absent path creates a new file and keeps the original retained file available.": "השחזור דורש אישור בחלון היישום. קובץ קיים נשמר ברשומת שחזור חדשה. שחזור לנתיב חסר יוצר קובץ חדש ומשאיר את הקובץ המקורי השמור זמין.",
"The retained snapshot was restored as a new file. The original retained file remains available for later editor writes.": "העותק השמור שוחזר כקובץ חדש. הקובץ המקורי השמור נשאר זמין לכתיבות מאוחרות מהעורך.",
"The file change needs reconciliation. Retained work remains available; inspect recovery before continuing.": "שינוי הקובץ דורש בדיקת התאמה. העבודה השמורה נשארת זמינה; יש לבדוק את השחזור לפני שממשיכים.",
"This recovery group could not be verified. Previous observations may be out of date.": "לא ניתן היה לאמת את קבוצת השחזור הזו. ייתכן שהבדיקות הקודמות אינן עדכניות.",
"The accepted group was observed in the working folder. Recovery records remain available.": "השינויים שאושרו בקבוצה נצפו בתיקיית העבודה. רשומות השחזור נשארות זמינות.",
"The group needs reconciliation. Some files may have changed; remaining changes were stopped. Inspect each member before continuing.": "הקבוצה דורשת בדיקת התאמה. ייתכן שחלק מהקבצים השתנו; יתר השינויים נעצרו. יש לבדוק כל קובץ לפני שממשיכים.",
"The group was not confirmed or was cancelled. Inspect recovery before retrying; some working files may have changed.": "הקבוצה לא אושרה או בוטלה. יש לבדוק את השחזור לפני ניסיון נוסף; ייתכן שחלק מקובצי העבודה השתנו.",
"Recovery could not be refreshed; previous observations may be out of date.": "לא ניתן היה לרענן את השחזור; ייתכן שהבדיקות הקודמות אינן עדכניות.",
"The group file could not be inspected. Previous observations may be out of date.": "לא ניתן היה לבדוק את הקובץ בקבוצה. ייתכן שהבדיקות הקודמות אינן עדכניות.",
"Proposed saved result": "תוצאה שמורה שהוצעה",
"This proposal does not resolve the request or approve the result.": "ההצעה אינה מסיימת את הטיפול בבקשה ואינה מאשרת את התוצאה.",
"Pin proposed result beside this review": "הצמדת התוצאה המוצעת לצד הסקירה הזו",

"Request changes to this saved result": "בקשת שינויים בתוצאה השמורה הזו",
"Requests stay tied to this checkpoint. The originating agent can read them when it next checks its context. Recorded does not mean delivered or addressed, and does not restart a worker.": "הבקשות נשארות משויכות לנקודת השמירה הזו. הסוכן במסלול המקורי יוכל לקרוא אותן בבדיקת ההקשר הבאה שלו. רישום אינו מעיד על מסירה או טיפול ואינו מפעיל סוכן מחדש.",
"Read recorded change requests": "קריאת בקשות שינוי שנרשמו",
"Recording the exact change request…": "רושם את בקשת השינוי המדויקת…",
"Reading recorded requests…": "קורא בקשות שנרשמו…",
"Read recorded change requests to load any earlier feedback for this result.": "קראו את בקשות השינוי שנרשמו כדי לטעון משוב קודם לתוצאה הזו.",
"Recorded request": "בקשה שנרשמה",
"No recorded requests for this result.": "אין בקשות שנרשמו לתוצאה הזו.",
"Pending receipt": "ממתין לאישור רישום",
"Retry this exact change request": "ניסיון נוסף לאותה בקשת שינוי",
"Requested changes": "השינויים המבוקשים",
"Enter non-empty text within 8 KiB, without hidden control or direction characters.": "יש להזין טקסט שאינו ריק, עד 8 KiB, ללא תווי בקרה או כיווניות נסתרים.",
"Up to 8 KiB of text. Saved requests remain available after restart. Closing this panel does not cancel a submitted request.": "עד 8 KiB של טקסט. בקשות שנשמרו נשארות זמינות לאחר הפעלה מחדש. סגירת החלונית אינה מבטלת בקשה שנשלחה.",
"Record change request": "רישום בקשת שינוי",
"Saved change requests could not be verified. Retry reading the same review.": "לא ניתן לאמת את בקשות השינוי השמורות. נסו לקרוא שוב את אותה הסקירה.",
"Recording is unconfirmed. Retry the same request to recover its receipt. Restored fleets require recovery before recording new requests.": "הרישום טרם אושר. נסו שוב את אותה הבקשה כדי לשחזר את אישור הרישום שלה. ציים שנטענו מחדש דורשים שחזור לפני רישום בקשות חדשות.",

"Earlier version": "גרסה קודמת",
"Current version": "גרסה נוכחית",

"This exact saved artifact preview is unavailable. Retry to render it again.": "התצוגה המקדימה של הפריט השמור המדויק אינה זמינה. יש לנסות להציג אותה שוב.",
"This exact saved artifact preview could not be verified. Retry to render it again.": "לא ניתן לאמת את התצוגה המקדימה של הפריט השמור המדויק. יש לנסות להציג אותה שוב.",
"This exact saved preview could not be verified.": "לא ניתן לאמת את התצוגה המקדימה השמורה המדויקת.",

"Saved lane review": "סקירת מסלול שמורה",
"Saved changed-object selection": "בחירת אובייקט ששונה ונשמרה",
"Content must be verified before display.": "יש לאמת את התוכן לפני הצגתו.",
"The saved file selection is unavailable in this review. Showing the first available change; the saved selection is retained.": "בחירת הקובץ השמורה אינה זמינה בסקירה זו. מוצג השינוי הזמין הראשון; הבחירה השמורה נשמרת.",
"Saved selections contain no file content. Reopening rechecks exact history; unavailable lanes remain listed and never restart agents.": "הבחירות השמורות אינן מכילות תוכן קבצים. פתיחה מחדש בודקת שוב את ההיסטוריה המדויקת; מסלולים שאינם זמינים נשארים ברשימה ולעולם אינם מפעילים סוכנים מחדש.",
"Loading saved review selections…": "טוען בחירות סקירה שמורות…",
"Saving review selections…": "שומר בחירות סקירה…",
"Review selections saved.": "בחירות הסקירה נשמרו.",
"Review selections have not loaded yet.": "בחירות הסקירה טרם נטענו.",
"Retry saving or loading review selections": "ניסיון נוסף לשמירה או לטעינה של בחירות סקירה",
"Reload saved review set": "טעינה מחדש של קבוצת הסקירות השמורה",
"Reload replaces local selections with the saved set, including any unsaved local choices.": "טעינה מחדש מחליפה את הבחירות המקומיות בקבוצה השמורה, לרבות בחירות מקומיות שלא נשמרו.",
"Load the saved review set before changing its selections.": "יש לטעון את קבוצת הסקירות השמורה לפני שינוי הבחירות שלה.",

"Independent line of work":"קו עבודה עצמאי",
"Existing project":"פרויקט קיים",
"Lane ancestry could not be verified. Its files and history are retained.":"לא ניתן לאמת את מקור קו העבודה. הקבצים וההיסטוריה שלו נשמרו.",
"Created from:":"נוצר מתוך:",
"Starting saved version:":"גרסה שמורה התחלתית:",
"Use this folder with your editor or harness. No Mesh-managed agent is assigned. Allocation ancestry does not identify who makes later changes.":"אפשר לעבוד בתיקייה זו עם העורך או עם כלי הסוכנים שלכם. לא הוקצה סוכן בניהול Mesh. רישום המקור אינו מזהה מי מבצע שינויים בהמשך.",
"Project main stays in the original project. Integrating this line’s saved result into project main is not available here yet.":"הגרסה הראשית נשארת בפרויקט המקורי. שילוב התוצאה השמורה של קו עבודה זה בגרסה הראשית עדיין אינו זמין כאן.",
"Retry creating this line":"ניסיון חוזר ליצירת קו העבודה",
"Lane review requests describe private saved work. Integration with the original project’s main is still unavailable.":"בקשות הסקירה של קו העבודה מתארות עבודה פרטית שנשמרה. שילוב בגרסה הראשית של הפרויקט המקורי עדיין אינו זמין.",
"Create line from this version":"יצירת קו עבודה מגרסה זו",
"Independent line created. Its folder and history appear below.":"נוצר קו עבודה עצמאי. התיקייה וההיסטוריה שלו מופיעות בהמשך.",
"The line could not be confirmed. Retry the same request to avoid duplicating it. Partial work is retained.":"לא ניתן לאשר שקו העבודה נוצר. נסו שוב את אותה בקשה כדי למנוע כפילות. עבודה חלקית נשמרת.",

"Needs attention":"דורש טיפול",
"Unavailable":"לא זמין",
"Applying main currently supports one existing text file at a time, after native confirmation. Additions, deletions and grouped changes are not available here yet.":"החלת הגרסה הראשית נתמכת כעת בקובץ טקסט קיים אחד בכל פעם, לאחר אישור בחלון של היישום. הוספות, מחיקות ושינויים קבוצתיים עדיין אינם זמינים כאן.",
"Review applying this file":"סקירה לפני החלת הקובץ",
"Working files may have changed since this comparison. Applying a file requires a fresh native check and complete text confirmation. Diverged files, additions, deletions and grouped changes are unavailable.":"ייתכן שקובצי העבודה השתנו מאז ההשוואה. החלת קובץ דורשת בדיקה חדשה של היישום ואישור של הטקסט המלא. קבצים ששונו, הוספות, מחיקות ושינויים קבוצתיים אינם זמינים.",
"Prepared content is retained":"התוכן שהוכן נשמר",
"Installed and retained files match the recorded arrangement":"הקובץ שהוחל והקובץ שנשמר תואמים למצב שתועד",
"Files changed since the recorded operation":"הקבצים השתנו מאז הפעולה שתועדה",
"File identity changed":"זהות הקובץ השתנתה",
"Files could not be fully checked":"לא ניתן היה לבדוק את הקבצים במלואם",
"Outcome record needs attention":"תיעוד התוצאה דורש טיפול",
"Recorded outcome conflicts with current files":"התוצאה המתועדת אינה תואמת לקבצים הנוכחיים",
"Recovery record needs attention":"רשומת השחזור דורשת טיפול",
"Approval history could not be verified":"לא ניתן היה לאמת את היסטוריית האישורים",
"Recovery folder unavailable":"תיקיית השחזור אינה זמינה",
"Unrecognized recovery entry":"פריט שחזור לא מזוהה",
"File details unavailable":"פרטי הקובץ אינם זמינים",
"Recovery reference:":"מזהה שחזור:",
"Restored private work; this does not approve it as Mesh main.":"עבודה פרטית ששוחזרה; פעולה זו אינה מאשרת אותה כגרסה הראשית של Mesh.",
"No outcome was recorded. This does not prove that the working file was unchanged.":"לא תועדה תוצאה. אין בכך הוכחה שקובץ העבודה לא השתנה.",
"Review restoring retained file":"סקירה לפני שחזור הקובץ שנשמר",
"Retained file recovery":"שחזור קבצים שנשמרו",
"Inspect files preserved when applying or restoring work. An open editor may still be writing to a retained file. Nothing is replayed or deleted automatically.":"בדקו קבצים שנשמרו בזמן החלה או שחזור של עבודה. עורך פתוח עשוי עדיין לכתוב לקובץ שנשמר. אף פעולה אינה מבוצעת שוב ושום דבר אינו נמחק אוטומטית.",
"Refresh retained files":"רענון הקבצים שנשמרו",
"Last observed recovery entries":"רשומות השחזור שנבדקו לאחרונה",
"No file recovery entries found.":"לא נמצאו רשומות לשחזור קבצים.",
"More entries exist outside this bounded overview. Use an exact recovery reference to inspect one.":"קיימות רשומות נוספות שאינן כלולות בתצוגה זו. השתמשו במזהה השחזור המדויק כדי לבדוק רשומה מסוימת.",
"Exact recovery reference":"מזהה שחזור מדויק",
"Inspect exact recovery":"בדיקת רשומת השחזור",
"Selected recovery · last observed":"השחזור שנבחר · כפי שנבדק לאחרונה",
"Restoring requires native confirmation. The current working file is retained in a new recovery entry, which can be restored separately to undo the change.":"השחזור דורש אישור בחלון של היישום. קובץ העבודה הנוכחי נשמר ברשומת שחזור חדשה, שאפשר לשחזר בנפרד כדי לבטל את השינוי.",
"The file change was observed. Previous working content is retained; later editor writes may still arrive.":"השינוי בקובץ נצפה. תוכן העבודה הקודם נשמר; ייתכן שהעורך ימשיך לכתוב אליו.",
"The file change needs reconciliation. Both files are retained; inspect recovery before continuing.":"השינוי בקובץ דורש בדיקה ויישוב. שני הקבצים נשמרו; בדקו את השחזור לפני שתמשיכו.",
"The file change was not confirmed or was cancelled. Inspect recovery before retrying; this does not prove the working file is unchanged.":"השינוי בקובץ לא אושר או בוטל. בדקו את השחזור לפני ניסיון נוסף; אין בכך הוכחה שקובץ העבודה לא השתנה.",
"Recovery could not be refreshed. Any previous observation is retained and may be out of date.":"לא ניתן היה לרענן את השחזור. הבדיקה הקודמת נשמרה וייתכן שאינה עדכנית.",
"Compare main with working files":"השוואת הגרסה הראשית לקובצי העבודה",
"Working-folder comparison":"השוואת תיקיית העבודה",
"Working folder compared with Mesh main":"תיקיית העבודה בהשוואה לגרסה הראשית ב-Mesh",
"Matches approved base":"תואם לבסיס שאושר",
"Already matches main":"כבר תואם לגרסה הראשית",
"Keep current work":"שמירת העבודה הנוכחית",
"Blocked by a parent conflict":"חסום עקב התנגשות בתיקיית אב",
"Working content differs from both the base and main.":"תוכן העבודה שונה גם מהבסיס וגם מהגרסה הראשית.",
"This directory contains current work that must be retained.":"תיקייה זו מכילה עבודה נוכחית שיש לשמור.",
"This directory contains entries outside the captured view, including possible ignored content.":"תיקייה זו מכילה פריטים מחוץ לתצוגה שנקלטה, וייתכן שגם תוכן שהוחרג.",
"A parent directory must be resolved first.":"יש לפתור תחילה את ההתנגשות בתיקיית האב.",
"match the approved base":"תואמים לבסיס שאושר",
"already match main":"כבר תואמים לגרסה הראשית",
"current changes to keep":"שינויים נוכחיים לשמירה",
"conflicts":"התנגשויות",
"blocked changes":"שינויים חסומים",
"more entries are omitted from this overview. The counts include all entries.":"פריטים נוספים אינם מוצגים בסקירה זו. הספירות כוללות את כל הפריטים.",
"Read-only observation. Working files may have changed since this comparison; it is not an atomic snapshot or permission to overwrite them. Write-back is not enabled here.":"תצפית לקריאה בלבד. ייתכן שקובצי העבודה השתנו מאז ההשוואה; זו אינה תמונת מצב אטומית או הרשאה לדרוס אותם. כתיבה בחזרה אינה זמינה כאן.",
"A fresh working-folder comparison is unavailable. Any previous observation is retained. Refresh main and retry.":"השוואה עדכנית של תיקיית העבודה אינה זמינה. תצפית קודמת נשמרת. יש לרענן את הגרסה הראשית ולנסות שוב.",
"Mesh main":"הגרסה הראשית ב-Mesh",
"Mesh main · last checked":"הגרסה הראשית ב-Mesh · בבדיקה האחרונה",
"The accepted saved version in Mesh. Your current files and Git branch can keep changing independently.":"הגרסה השמורה שאושרה ב-Mesh. הקבצים הנוכחיים וענף ה-Git יכולים להמשיך להשתנות בנפרד.",
"Main and approval availability have not been verified.":"הגרסה הראשית וזמינות האישורים טרם אומתו.",
"Mesh main cannot currently be verified. Its history is retained.":"לא ניתן לאמת כרגע את הגרסה הראשית ב-Mesh. ההיסטוריה שלה נשמרת.",
"Accepted saved version:":"גרסה שמורה שאושרה:",
"Inspect Mesh main":"בדיקת הגרסה הראשית ב-Mesh",
"No version has been accepted as Mesh main yet.":"עדיין לא אושרה גרסה ראשית ב-Mesh.",
"Refresh main and approval availability":"רענון הגרסה הראשית וזמינות האישורים",
"Approval unavailable:":"אישור אינו זמין:",
"Set up approvals on this Mac":"הגדרת אישורים ב-Mac זה",
"This version is Mesh main":"זו הגרסה הראשית ב-Mesh",
"Approve as Mesh main…":"אישור כגרסה הראשית ב-Mesh…",
"This request stays on its saved version while work continues. Change author unknown. Approval requires native confirmation and Touch ID or your Mac password. Working files and Git remain unchanged.":"בקשה זו נשארת על הגרסה השמורה בזמן שהעבודה נמשכת. מחבר השינוי אינו ידוע. האישור מחייב אישור בחלון המערכת ו-Touch ID או סיסמת ה-Mac. קובצי העבודה ו-Git נשארים ללא שינוי.",
"Writing saved versions back to your working folder is not available here yet.":"כתיבת גרסאות שמורות בחזרה לתיקיית העבודה עדיין אינה זמינה כאן.",
"Mesh main and approval availability could not be checked. Retry when ready.":"לא ניתן היה לבדוק את הגרסה הראשית וזמינות האישורים. אפשר לנסות שוב כשמוכנים.",
"Approval setup was not confirmed. Check availability before retrying.":"הגדרת האישורים לא אושרה. בדקו זמינות לפני ניסיון נוסף.",
"Approval confirmed. Mesh main was refreshed.":"האישור אושר. הגרסה הראשית ב-Mesh רועננה.",
"Approval was not confirmed or was cancelled. Refresh Mesh main before retrying.":"האישור לא אומת או בוטל. רעננו את הגרסה הראשית ב-Mesh לפני ניסיון נוסף.",
"Show review requests":"הצגת בקשות סקירה",
"Review requests use Mesh’s accepted main version as their base, or the empty starting state before its first approval.":"בקשות סקירה מבוססות על הגרסה הראשית שאושרה ב-Mesh, או על מצב התחלתי ריק לפני האישור הראשון.",
"Request review":"בקשת סקירה",
"Saved review requests":"בקשות סקירה שמורות",
"No review requests recorded.":"לא נשמרו בקשות סקירה.",
"Open review":"פתיחת סקירה",
"more requests are outside this page. Request review from a saved version to reopen its exact request.":"בקשות נוספות אינן מוצגות בעמוד זה. בקשו סקירה מתוך גרסה שמורה כדי לפתוח מחדש את הבקשה המדויקת שלה.",
"Selected saved review":"סקירה שמורה שנבחרה",
"Review request recorded":"בקשת הסקירה נשמרה",
"Bundle:":"חבילה:",
"Saved version:":"גרסה שמורה:",
"Presentation:":"תצוגה:",
"Review content is unavailable; the request is retained.":"תוכן הסקירה אינו זמין; הבקשה נשמרת.",
"Saved content verified for this request.":"התוכן השמור אומת עבור בקשה זו.",
"This overview is incomplete; it cannot stand in for complete review.":"סקירה כללית זו אינה מלאה; היא אינה תחליף לסקירה מלאה.",
"changes and":"שינויים ועוד",
"operations omitted from this overview.":"פעולות הושמטו מסקירה כללית זו.",
"Inspect saved result":"בדיקת התוצאה השמורה",
"This request stays on its saved version while work continues. Change author unknown. Approval and main-version integration are not available here yet.":"בקשה זו נשארת על הגרסה השמורה בזמן שהעבודה נמשכת. מחבר השינוי אינו ידוע. אישור ושילוב בגרסה הראשית עדיין אינם זמינים כאן.",
"File-change signals active, with periodic checks for missed changes.":"התראות על שינויי קבצים פעילות, עם בדיקות תקופתיות לאיתור שינויים שהוחמצו.",
"Preparing file-change monitoring; periodic checks continue.":"מעקב שינויי הקבצים בהכנה; הבדיקות התקופתיות נמשכות.",
"File-change monitoring is still stopping.":"עצירת המעקב אחר שינויי הקבצים עדיין מתבצעת.",
"Using periodic checks for file changes.":"שינויים בקבצים נבדקים באופן תקופתי.",
"Detached · saved history retained":"מנותק · ההיסטוריה השמורה נשמרת",
"Reattach to enable capture controls":"חברו מחדש כדי להפעיל את בקרות הלכידה",
"Reattach project":"חיבור הפרויקט מחדש",
"Detach Mesh":"ניתוק Mesh",
"Capture is disabled. Your files, Git workflow and saved history are retained. Reattach, then resume capture when ready.":"הלכידה מושבתת. הקבצים, תהליך העבודה עם Git וההיסטוריה השמורה נשמרים. חברו מחדש, ואז חדשו את הלכידה כשמוכנים.",
"Saved history restored; resume when ready":"ההיסטוריה השמורה שוחזרה; אפשר לחדש את הלכידה כשמוכנים",
"Project or history needs reconciliation":"יש לאמת מחדש את הפרויקט או ההיסטוריה",
"Saved version unavailable until history is verified":"הגרסה השמורה אינה זמינה עד לאימות ההיסטוריה",
"Retry capture":"ניסיון לכידה נוסף",
"Registered projects return when Mesh opens. Recovered projects remain stopped until you resume capture.":"הפרויקטים הרשומים חוזרים כשפותחים את Mesh. פרויקטים ששוחזרו נשארים עצורים עד לחידוש הלכידה.",
"Restoring saved comparisons…":"משחזר השוואות שמורות…",
"Saving comparison selections…":"שומר בחירות להשוואה…",
"Comparison selections saved":"בחירות ההשוואה נשמרו",
"Retry saving or loading pins":"ניסיון נוסף לשמירה או לטעינה של השוואות נעוצות",
"Replace open pins with saved set":"החלפת ההשוואות הפתוחות בקבוצה השמורה",
"Saved comparison unavailable. Its selection is retained.":"ההשוואה השמורה אינה זמינה. הבחירה שלה נשמרת.",
"Retry saved comparison":"ניסיון נוסף לטעינת ההשוואה השמורה",
"Each pin keeps its own version pair, page and file selection. Saved selections return when Mesh opens; content is verified again from history.":"כל השוואה נעוצה שומרת על זוג הגרסאות, העמוד ובחירת הקובץ שלה. הבחירות השמורות חוזרות עם פתיחת Mesh; התוכן מאומת מחדש מתוך ההיסטוריה.",
"Saved pins could not be loaded. Their stored record has not been replaced.":"לא ניתן לטעון את ההשוואות הנעוצות. הרשומה השמורה שלהן לא הוחלפה.",
"Pin changes are not confirmed saved. Current views remain open; retry saving or reload the saved set.":"שמירת השינויים בהשוואות הנעוצות לא אושרה. התצוגות הנוכחיות נשארות פתוחות; נסו לשמור שוב או לטעון את הקבוצה השמורה.",
"Saved pins changed or remain unavailable. Reload the saved set to reconcile; local views have not been overwritten.":"ההשוואות השמורות השתנו או עדיין אינן זמינות. טענו מחדש את הקבוצה השמורה; התצוגות המקומיות לא הוחלפו.",
"Pinned comparisons":"השוואות נעוצות",
"Close comparison":"סגירת השוואה",
"Pin comparison alongside others":"נעיצת השוואה לצד השוואות אחרות",
"Eight comparisons pinned; close one to add another":"שמונה השוואות נעוצות; סגרו אחת כדי להוסיף אחרת",
"Each pin keeps its own version pair, page and file selection. Pins are retained during this desktop session.":"כל השוואה נעוצה שומרת על זוג הגרסאות, העמוד ובחירת הקובץ שלה. ההשוואות הנעוצות נשמרות במהלך הפעלה זו של היישום.",
"Selected comparison base:":"הבסיס שנבחר להשוואה:",
"Use as base":"בחירה כבסיס",
"Compare with base":"השוואה לבסיס",
"Content changed":"התוכן השתנה",
"Executable mode changed":"מצב ההרצה השתנה",
"File/folder type changed":"סוג הפריט השתנה בין קובץ לתיקייה",
"Not executable":"אינו ניתן להרצה",
"Saved version comparison":"השוואת גרסאות שמורות",
"Compare saved versions":"השוואת גרסאות שמורות",
"changed paths":"נתיבים שהשתנו",
"Base:":"בסיס:",
"Compared version:":"הגרסה המושווית:",
"These versions have the same paths, content and executable modes.":"לגרסאות האלה יש אותם נתיבים, תוכן ומצבי הרצה.",
"More changes":"שינויים נוספים",
"Absent in this version":"אינו קיים בגרסה זו",
"This comparison stays on these saved versions while work continues. It does not approve or apply changes.":"ההשוואה נשארת על הגרסאות השמורות האלה בזמן שהעבודה נמשכת. היא אינה מאשרת או מחילה שינויים.",
"Binary file; no text preview":"קובץ בינארי; אין תצוגת טקסט",
"File exceeds the 256 KiB preview limit":"הקובץ חורג ממגבלת התצוגה של 256 KiB",
"This history page stays fixed while capture continues.":"עמוד ההיסטוריה נשאר קבוע בזמן שהלכידה נמשכת.",
"Saved version files":"קבצי הגרסה השמורה",
"Files in saved version":"קבצים בגרסה השמורה",
"This saved version has no files or folders.":"בגרסה השמורה הזו אין קבצים או תיקיות.",
"More files":"קבצים נוספים",
"Binary file. Text preview is unavailable.":"קובץ בינארי. תצוגת טקסט אינה זמינה.",
"This file exceeds the 256 KiB text preview limit.":"הקובץ חורג ממגבלת תצוגת הטקסט של 256 KiB.",
"Read-only saved content. Edits in your working folder do not change this view.":"תוכן שמור לקריאה בלבד. עריכות בתיקיית העבודה אינן משנות תצוגה זו.",
"Show latest versions":"הצגת הגרסאות האחרונות",
"Saved versions for":"גרסאות שמורות עבור",
"Saved versions · newest first":"גרסאות שמורות · החדשות תחילה",
"Older versions":"גרסאות קודמות",
"This history page stays fixed while capture continues. File previews and review are not available here yet.":"עמוד ההיסטוריה נשאר קבוע בזמן שהלכידה נמשכת. תצוגה מקדימה של קבצים וסקירה אינן זמינות כאן עדיין.",
"Separate workspace":"סביבת עבודה נפרדת",
"Create a working copy":"יצירת עותק עבודה",
"Attached projects":"פרויקטים מחוברים",
"Use your existing project":"שימוש בפרויקט הקיים",
"Keep your folder, editor, Git workflow and agent sessions where they are. Mesh saves history in separate storage while you work.":"התיקייה, העורך, תהליך העבודה ב־Git ושיחות הסוכנים נשארים במקומם. Mesh שומר היסטוריה באחסון נפרד בזמן העבודה.",
"Choose project to attach":"בחירת פרויקט לחיבור",
"Existing project path":"נתיב הפרויקט הקיים",
"Attach existing project":"חיבור פרויקט קיים",
"Attachment requires the native Mesh desktop.":"חיבור פרויקט זמין ביישום Mesh למחשב.",
"Refresh status":"רענון מצב",
"Updating…":"מעדכן…",
"Status may be out of date":"ייתכן שהמצב אינו עדכני",
"Starting capture":"מתחיל לכידה",
"Checking changes":"בודק שינויים",
"Saving a version":"שומר גרסה",
"Watching for changes":"ממתין לשינויים",
"Stopping capture":"עוצר לכידה",
"Capture stopped":"הלכידה נעצרה",
"Capture needs attention":"הלכידה דורשת תשומת לב",
"First capture pending":"ממתין ללכידה הראשונה",
"Version saved":"הגרסה נשמרה",
"No new changes":"אין שינויים חדשים",
"Capture incomplete":"הלכידה אינה מלאה",
"Project folder unavailable":"תיקיית הפרויקט אינה זמינה",
"History storage unavailable":"אחסון ההיסטוריה אינו זמין",
"Version could not be saved":"לא ניתן היה לשמור גרסה",
"Capture cancelled":"הלכידה בוטלה",
"Latest saved version:":"הגרסה האחרונה שנשמרה:",
"No saved version yet":"עדיין אין גרסה שמורה",
"No complete capture in this session":"אין עדיין לכידה מלאה בהפעלה זו",
"Last complete capture started":"הלכידה המלאה האחרונה התחילה לפני",
"seconds ago":"שניות",
"Change author unknown.":"זהות מבצע השינוי אינה ידועה.",
"Capture now":"לכידה כעת",
"Resume capture":"חידוש הלכידה",
"Stop capture":"עצירת הלכידה",
"After reopening Mesh, attach the same project to resume capture. Saved history is retained.":"לאחר פתיחה מחדש של Mesh, חברו שוב את אותו הפרויקט לחידוש הלכידה. ההיסטוריה השמורה נשמרת.",
"Attachment status is unavailable. Your existing tools can keep working. Retry to refresh.":"מצב החיבור אינו זמין. אפשר להמשיך לעבוד בכלים הקיימים. נסו לרענן שוב.",
"Workspaces":"סביבות עבודה", "Import":"ייבוא", "Current":"נוכחי", "Files":"קבצים", "Changes":"שינויים", "Review":"סקירה", "Versions":"גרסאות", "Update destination":"עדכון תיקיית היעד", "Restore":"שחזור",
"Local workspace":"סביבת עבודה מקומית", "Primary pages":"עמודים ראשיים", "Skip to workspace":"דילוג לסביבת העבודה", "· Local only · No network listener":"· מקומי בלבד · ללא האזנה לרשת",
"NATIVE WORKSPACE":"סביבת עבודה", "LOCAL WORKSPACE":"סביבת עבודה מקומית", "Your folder, with a private history.":"התיקייה שלכם, עם היסטוריה פרטית.", "Work in your folder. Mesh remembers.":"עובדים בתיקייה שלכם. Mesh זוכר.",
"Choose a folder":"בחירת תיקייה", "Import another folder":"ייבוא תיקייה נוספת", "Preview this folder":"תצוגה מקדימה של התיקייה", "Retry verification":"ניסיון אימות נוסף", "Refresh":"רענון", "Your original folder stays untouched.":"התיקייה המקורית נשארת ללא שינוי.", "Import or switch to another workspace":"ייבוא או מעבר לסביבת עבודה אחרת", "Bring in an ordinary project folder":"ייבוא תיקיית פרויקט רגילה", "Return to a recent Mesh workspace":"חזרה לסביבת עבודה אחרונה", "Already use Mesh? Open a managed workspace":"כבר משתמשים ב־Mesh? פתיחת סביבת עבודה מנוהלת",
"Choose managed workspace":"בחירת סביבת עבודה מנוהלת", "Or enter its path":"או הזנת הנתיב שלה", "Open path":"פתיחת נתיב", "Recent workspaces":"סביבות עבודה אחרונות", "No recent workspace yet":"אין עדיין סביבות עבודה אחרונות", "Forget from list":"הסרה מהרשימה", "Open selected workspace":"פתיחת סביבת העבודה שנבחרה", "Open recent workspace":"פתיחת סביבת עבודה אחרונה",
"Bring in a folder":"ייבוא תיקייה", "Start with your folder":"מתחילים עם התיקייה שלכם", "Keep working in ordinary files":"ממשיכים לעבוד בקבצים רגילים", "Mesh verifies the folder before creating a private workspace. Your original stays untouched.":"Mesh מאמת את התיקייה לפני יצירת סביבת עבודה פרטית. המקור נשאר ללא שינוי.", "Absolute folder path":"נתיב מלא לתיקייה", "Preview folder":"תצוגה מקדימה של התיקייה", "or use a path":"או שימוש בנתיב", "Verified copy":"עותק מאומת", "Verified folder preview":"תצוגה מקדימה מאומתת", "Creating private workspace":"יוצר סביבת עבודה פרטית", "Ready to create":"מוכן ליצירה", "Review what Mesh will bring in":"סקירת התוכן ש־Mesh ייבא", "Folders":"תיקיות", "Size":"גודל", "Review included files":"סקירת הקבצים הכלולים", "Verified summary":"סיכום מאומת", "Use a custom private location":"שימוש במיקום פרטי אחר", "Custom location":"מיקום מותאם", "Leave blank for Mesh-managed storage":"להשאיר ריק לאחסון בניהול Mesh", "Choose parent":"בחירת תיקיית אב", "Choose another folder":"בחירת תיקייה אחרת", "The original folder is never opened for writing.":"Mesh אינו פותח את התיקייה המקורית לכתיבה.", "Create private workspace":"יצירת סביבת עבודה פרטית", "Create workspace":"יצירת סביבת עבודה", "Keep Mesh open. Large projects can take several minutes; the original folder remains unchanged.":"יש להשאיר את Mesh פתוח. פרויקטים גדולים עשויים להימשך כמה דקות; התיקייה המקורית נשארת ללא שינוי.", "Choose an ordinary folder. Mesh verifies every included file before it creates a private working copy.":"בחרו תיקייה רגילה. Mesh מאמת כל קובץ כלול לפני יצירת עותק עבודה פרטי.",
"Ready":"מוכן", "Checking":"בודק", "Available":"זמין", "Selected":"נבחר", "Status":"מצב", "Details":"פרטים", "Folder":"תיקייה", "File":"קובץ", "Path":"נתיב", "Type":"סוג", "History":"היסטוריה", "History:":"היסטוריה:", "Private history":"היסטוריה פרטית", "Saved locally":"נשמר מקומית", "Current workspace":"סביבת עבודה נוכחית", "Current workspace details":"פרטי סביבת העבודה הנוכחית", "Working folder":"תיקיית עבודה", "Working copy":"עותק עבודה", "Workspace details":"פרטי סביבת העבודה", "Workspace overview":"סקירת סביבת העבודה", "Workspace details and recovery":"פרטי סביבת העבודה ושחזור", "Support and recovery":"תמיכה ושחזור", "Copy safe diagnostics":"העתקת אבחון בטוח", "Refresh workspace state":"רענון מצב סביבת העבודה", "Switch workspace":"החלפת סביבת עבודה",
"Explorer":"סייר", "Workspace file explorer":"סייר קבצי סביבת העבודה", "Workspace files":"קבצי סביבת העבודה", "Files and folders":"קבצים ותיקיות", "Browse and open the exact working files.":"עיון ופתיחה של קבצי העבודה המדויקים.", "Filter workspace files":"סינון קבצי סביבת העבודה", "Go to file…":"מעבר לקובץ…", "Collapse all":"כיווץ הכול", "File details":"פרטי קובץ", "File type":"סוג קובץ", "Selected path":"הנתיב שנבחר", "Select an item from Files":"בחרו פריט מתוך הקבצים", "Choose a file":"בחירת קובץ", "Open in default app":"פתיחה ביישום ברירת המחדל", "Reveal in Finder":"הצגה ב־Finder", "Open folder":"פתיחת תיקייה", "Open working folder":"פתיחת תיקיית העבודה", "Relative path":"נתיב יחסי", "New relative path":"נתיב יחסי חדש", "Rename or move":"שינוי שם או העברה", "Delete selected item":"מחיקת הפריט שנבחר", "Folder selected":"נבחרה תיקייה", "Parent":"תיקיית אב", "New":"חדש",
"Working changes":"שינויים בעבודה", "Folder changes":"שינויים בתיקייה", "Find changes":"איתור שינויים", "Find folder changes":"איתור שינויים בתיקייה", "Save privately":"שמירה פרטית", "Save all privately":"שמירת הכול באופן פרטי", "Save version":"שמירת גרסה", "Changes and text editor":"שינויים ועורך טקסט", "Change summary":"סיכום שינויים", "Changed files":"קבצים שהשתנו", "Search changed files":"חיפוש בקבצים שהשתנו", "All statuses":"כל המצבים", "All types":"כל הסוגים", "Current file":"קובץ נוכחי", "Before":"לפני", "After":"אחרי", "Working tree diff":"השוואת קבצי העבודה", "No text changes":"אין שינויי טקסט", "The working copy matches the saved version exactly.":"עותק העבודה תואם בדיוק לגרסה השמורה.", "Saved baseline cannot be displayed":"לא ניתן להציג את גרסת הבסיס השמורה", "Comparison is too large to display":"ההשוואה גדולה מדי להצגה", "Selected change comparison":"השוואת השינוי שנבחר", "Inline text comparison":"השוואת טקסט רציפה", "Split text comparison":"השוואת טקסט מפוצלת", "Unchanged text comparison":"השוואת טקסט ללא שינוי", "No newline":"ללא ירידת שורה", "No current line":"אין שורה נוכחית", "No earlier line":"אין שורה קודמת", "line":"שורה", "lines":"שורות", "added":"נוסף", "modified":"שונה", "deleted":"נמחק", "changed":"השתנה", "removed":"הוסר", "addition":"תוספת", "additions":"תוספות", "deletion":"מחיקה", "deletions":"מחיקות", "of":"מתוך", "page":"עמוד",
"Saved version":"גרסה שמורה", "Current saved version":"הגרסה השמורה הנוכחית", "Earlier saved version":"גרסה שמורה קודמת", "Saved file":"קובץ שמור", "Saved workspace":"סביבת עבודה שמורה", "Saved points":"נקודות שמירה", "Saved workspace points":"נקודות שמירה של סביבת העבודה", "Workspace versions":"גרסאות סביבת העבודה", "Workspaces and agents":"סביבות עבודה וסוכנים", "Find a workspace or agent":"חיפוש סביבת עבודה או סוכן", "Search by name, state, or path…":"חיפוש לפי שם, מצב או נתיב…", "No active agent":"אין סוכן פעיל", "No assigned agent":"אין סוכן משויך", "Agent assigned":"סוכן משויך", "Agent running":"סוכן פועל", "Workspace or assigned agent":"סביבת עבודה או סוכן משויך", "Open an exact saved point":"פתיחת נקודת שמירה מדויקת", "Switch without losing agent context":"מעבר בלי לאבד את הקשר הסוכן", "Selected version preview":"תצוגה מקדימה של הגרסה שנבחרה", "Private version":"גרסה פרטית", "Shared version":"גרסה משותפת", "Exact copy":"עותק מדויק", "Concurrent history":"היסטוריה מקבילה", "Find a saved file":"חיפוש קובץ שמור", "Find an earlier saved version":"חיפוש גרסה שמורה קודמת", "Filter saved files…":"סינון קבצים שמורים…", "Filter saved versions…":"סינון גרסאות שמורות…", "No saved files available":"אין קבצים שמורים זמינים",
"Review work":"סקירת העבודה", "Start review":"התחלת סקירה", "Saved review":"סקירה שמורה", "Live agent work":"עבודה חיה של סוכן", "Live agent work review":"סקירת עבודה חיה של סוכן", "Review workbench":"מרחב סקירה", "Review workspace summary":"סקירת סיכום סביבת העבודה", "Review status":"מצב סקירה", "Review decision":"החלטת סקירה", "Decision":"החלטה", "Review bundle":"חבילת סקירה", "Review this exact saved version":"סקירת הגרסה השמורה המדויקת", "Understand exactly what changed":"להבין בדיוק מה השתנה", "Comparison view":"תצוגת השוואה", "Load visual comparison":"טעינת השוואה חזותית", "Reload visual comparison":"טעינה מחדש של ההשוואה החזותית", "Try visual comparison again":"ניסיון נוסף להשוואה חזותית", "Rendering exact versions…":"מציג את הגרסאות המדויקות…", "Text comparison unavailable":"השוואת טקסט אינה זמינה", "Content comparison could not be loaded":"לא ניתן לטעון את השוואת התוכן", "Artifact content comparison unavailable":"השוואת תוכן המסמך אינה זמינה", "Load the exact versions to compare their content":"יש לטעון את הגרסאות המדויקות כדי להשוות את תוכנן", "Previous":"הקודם", "Next":"הבא", "Previous page":"העמוד הקודם", "Next page":"העמוד הבא", "Confirm review complete":"אישור השלמת הסקירה", "Approve exact version":"אישור הגרסה המדויקת", "Open copy folder":"פתיחת תיקיית העותק", "Inspect exact copies":"בדיקת העותקים המדויקים", "Not present":"לא קיים", "Read-only monitor":"מעקב לקריאה בלבד", "Monitoring":"במעקב", "Mutable":"ניתן לשינוי", "Unrecorded":"טרם נשמר", "Inspect work without finishing the handoff":"בדיקת העבודה בלי לסיים את ההעברה לסוכן",
"Restore an earlier file version":"שחזור גרסה קודמת של קובץ", "Find a retained file":"חיפוש קובץ שנשמר בהיסטוריה", "Filter retained files…":"סינון קבצים בהיסטוריה…", "Choose a file first":"יש לבחור קובץ תחילה", "Version to restore":"גרסה לשחזור", "Preview restore":"תצוגה מקדימה של השחזור", "Restore in working copy":"שחזור בעותק העבודה", "Ready to restore":"מוכן לשחזור", "No retained file history":"אין היסטוריית קבצים שמורה", "Working copy only":"עותק העבודה בלבד",
"Update saved work in an ordinary folder":"עדכון עבודה שמורה בתיקייה רגילה", "Original or destination folder":"תיקיית המקור או היעד", "Selected destination":"היעד שנבחר", "No destination selected":"לא נבחר יעד", "Or type a destination folder":"או הזנת תיקיית יעד", "Use typed destination":"שימוש ביעד שהוזן", "One saved file":"קובץ שמור אחד", "Choose a saved file":"בחירת קובץ שמור", "Verified preview":"תצוגה מקדימה מאומתת", "Preview verified":"התצוגה המקדימה אומתה", "Exact destination plan":"תוכנית מדויקת לתיקיית היעד", "Explicit and staged":"מפורש ובשלבים", "Mesh previews and rechecks saved content before any destination write.":"Mesh מציג ובודק מחדש תוכן שמור לפני כל כתיבה לתיקיית היעד.",
"Confirm exact action":"אישור הפעולה המדויקת", "What changes:":"מה משתנה:", "Undo:":"ביטול:", "Cancel":"ביטול", "Confirm":"אישור", "Close":"סגירה", "Recommended next":"השלב הבא המומלץ", "Recommended next action":"הפעולה הבאה המומלצת",
"Bring in an ordinary project folder. Mesh verifies every file before it creates a private working copy, the original stays untouched, and your recent validated workspaces remain available across restarts.":"בחרו תיקיית פרויקט רגילה. Mesh מאמת כל קובץ לפני יצירת עותק עבודה פרטי. המקור נשאר ללא שינוי, וסביבות העבודה המאומתות האחרונות נשמרות גם לאחר הפעלה מחדש.",
"This preview contains no ordinary project files or folders. Creating it will produce an empty workspace. Choose another folder unless an empty workspace is intentional.":"בתצוגה זו אין קבצים או תיקיות רגילים של הפרויקט. יצירתה תיצור סביבת עבודה ריקה. בחרו תיקייה אחרת, אלא אם רציתם להתחיל בסביבת עבודה ריקה.",
"Counts cover the files Mesh will bring into the native working folder. Mesh applies this project's .gitignore and .meshignore. The source .git directory is never copied as workspace content; for Git projects, Mesh separately recreates independently owned history, branch, and index state in the new working folder. Excluded paths stay only in the original folder.":"הספירה כוללת את הקבצים ש־Mesh ייבא לתיקיית העבודה. כללי .gitignore ו־.meshignore של הפרויקט חלים. תיקיית .git המקורית אינה מועתקת כתוכן; בפרויקטי Git, ההיסטוריה, הענף והאינדקס נוצרים בנפרד בתיקייה החדשה. נתיבים שהוחרגו נשארים רק במקור.",
"Create empty workspace":"יצירת סביבת עבודה ריקה",
"Create workspace and open folder":"יצירת סביבת עבודה ופתיחת התיקייה",
"Creating private workspace…":"יוצר סביבת עבודה פרטית…",
"Connecting original folder…":"מחבר את תיקיית המקור…",
"Connect original folder":"חיבור תיקיית המקור",
"Checking local service":"בודק את השירות המקומי",
"Local service ready":"השירות המקומי מוכן",
"Local service needs attention":"השירות המקומי דורש טיפול",
"Start Codex on this version":"הפעלת Codex על גרסה זו",
"Finish agent handoff":"סיום העבודה עם הסוכן",
"Keep agent assigned":"השארת הסוכן משויך",
"Open in working folder":"פתיחה בתיקיית העבודה",
"Start Codex on this point":"הפעלת Codex מנקודה זו",
"Start another agent from this point":"הפעלת סוכן נוסף מנקודה זו",
"Independent agent folder":"תיקייה עצמאית לסוכן",
"Agent folder":"תיקיית הסוכן",
"Create text file":"יצירת קובץ טקסט",
"Create folder":"יצירת תיקייה",
"Move or rename":"העברה או שינוי שם",
"Delete entry":"מחיקת פריט",
"Open":"פתיחה",
"Reveal":"הצגה ב־Finder",
"Open file":"פתיחת קובץ",
"Preserve edit":"שמירת העריכה",
"Record move or deletion":"שמירת העברה או מחיקה",
"Refresh safely":"רענון בטוח",
"Review conditions":"סקירת התנאים",
"Return to the edit":"חזרה לעריכה",
"Inspect changes":"בדיקת השינויים",
"Create working folder":"יצירת תיקיית עבודה",
"Choose saved version":"בחירת גרסה שמורה",
"Inspect review":"בדיקת הסקירה",
"Setting up approvals…":"מגדיר אישורים…",
"Review approval":"סקירת האישור",
"Choose export folder":"בחירת תיקיית ייצוא",
"Approval unavailable":"האישור אינו זמין",
"Set up approvals":"הגדרת אישורים",
"Preview original update":"תצוגה מקדימה לעדכון המקור",
"Choose folder":"בחירת תיקייה",
"Preview one file":"תצוגה מקדימה לקובץ אחד",
"Replace existing file":"החלפת קובץ קיים",
"Create file":"יצירת קובץ",
"Preview saved workspace":"תצוגה מקדימה לסביבת העבודה השמורה",
"Undo last restore":"ביטול השחזור האחרון",
"Replace saved file":"החלפת קובץ שמור",
"Create saved file":"יצירת קובץ שמור",
"Keep destination unchanged":"השארת היעד ללא שינוי",
"Roll back managed copy":"ביטול העותק המנוהל",
"Keep workspace":"השארת סביבת העבודה",
"Delete file":"מחיקת קובץ",
"Delete folder":"מחיקת תיקייה",
"Keep entry":"השארת הפריט",
"Preparing workspace controls…":"מכין את בקרי סביבת העבודה…",
"Preparing folder import…":"מכין ייבוא תיקייה…",
"Preparing workspace summary…":"מכין סיכום סביבת עבודה…",
"Preparing current workspace…":"מכין את סביבת העבודה הנוכחית…",
"Preparing files…":"מכין קבצים…",
"Preparing changes…":"מכין שינויים…",
"Preparing review…":"מכין סקירה…",
"Preparing versions…":"מכין גרסאות…",
"Preparing destination…":"מכין יעד…",
"Preparing restore…":"מכין שחזור…",
"Import folder":"ייבוא תיקייה",
"Choose a file and a saved version, then inspect the change before replacing the file in your working folder. Private history is not rewritten.":"בחרו קובץ וגרסה שמורה ובדקו את השינוי לפני החלפת הקובץ בתיקיית העבודה. ההיסטוריה הפרטית אינה משתנה.",
"Deletion accepts files and empty folders and requires confirmation. Saved file content remains in immutable history.":"ניתן למחוק קבצים ותיקיות ריקות בלבד, לאחר אישור. תוכן קבצים שנשמר נשאר בהיסטוריה שאינה ניתנת לשינוי.",
"Review the working set, compare exact bytes, then save selected work privately.":"סקרו את קבצי העבודה, השוו את התוכן המדויק ושמרו את העבודה שנבחרה באופן פרטי.",
"Before and after are exact immutable saved sides. They are not the writable workspace.":"התצוגות לפני ואחרי הן גרסאות שמורות מדויקות שאינן ניתנות לשינוי, ולא סביבת העבודה הניתנת לעריכה.",
"This stable path follows the version opened in Mesh.":"הנתיב הקבוע הזה עוקב אחר הגרסה שנפתחה ב־Mesh.",
"Existing editors and agents keep their current directory handle. Reopen them only when they should follow the newly selected working folder.":"עורכים וסוכנים שכבר פועלים נשארים מחוברים לתיקייה שלהם. פתחו אותם מחדש רק כדי שיעבדו בתיקיית העבודה החדשה שנבחרה.",
"Mesh verifies the complete point before it can open an independent native folder. The workspace you leave stays untouched.":"Mesh מאמת את נקודת השמירה כולה לפני פתיחת תיקייה עצמאית. סביבת העבודה שממנה עוברים נשארת ללא שינוי.",
"Type an absolute folder path, then choose Use typed destination or press Enter. The selected destination above is the value Mesh will preview.":"הזינו נתיב מלא לתיקייה ובחרו שימוש ביעד שהוזן או לחצו Enter. Mesh יציג תצוגה מקדימה עבור היעד הנבחר שמופיע למעלה.",
"Preview the selected file against the destination, then create or replace it only if the exact preview remains current.":"השוו בתצוגה מקדימה את הקובץ שנבחר ליעד. יצירה או החלפה תתאפשר רק כל עוד התצוגה המדויקת עדיין עדכנית.",
"Preview folders and files together. Mesh creates reviewed missing folders first, then automatically re-previews the files and updates only the verified changed set after confirmation.":"הציגו תיקיות וקבצים יחד בתצוגה מקדימה. Mesh יוצר תחילה תיקיות חסרות שאושרו, בודק שוב את הקבצים ומעדכן רק את השינויים המאומתים לאחר אישור.",
"Mesh remembers and prefills the original folder used for an import, including after you switch to an older saved version. For a workspace opened manually, choose a destination once. Choose one saved file or the complete saved workspace; Mesh verifies the destination and shows the exact create, replace, or removal plan before a separate confirmation can write anything. Every file is rechecked and installed atomically.":"Mesh זוכר וממלא את תיקיית המקור גם לאחר מעבר לגרסה שמורה קודמת. בסביבת עבודה שנפתחה ידנית, בחרו יעד פעם אחת. בחרו קובץ שמור או סביבת עבודה שלמה; Mesh מאמת את היעד ומציג תוכנית מדויקת ליצירה, החלפה או הסרה לפני אישור נפרד לכתיבה. כל קובץ נבדק שוב ומותקן באופן אטומי.",
"Mesh creates folders and updates current files first. After current paths are installed, Mesh derives former saved paths for a separate reviewed removal step. Only paths proven to come from the original import or an exact durable update receipt are eligible; recursive deletion is unavailable. Private-only, changed, replaced, or unrelated destination entries are preserved, and Mesh never removes a destination entry silently. A batch never rolls back an earlier completed prefix.":"Mesh יוצר תחילה תיקיות ומעדכן קבצים נוכחיים. לאחר מכן מוצגים נתיבים קודמים להסרה בשלב נפרד. רק נתיבים שהוכח שהגיעו מהייבוא המקורי או מעדכון מתועד זכאים להסרה; מחיקה רקורסיבית אינה זמינה. פריטים פרטיים, שהשתנו, שהוחלפו או שאינם קשורים נשמרים. אין הסרה שקטה, ופעולות שכבר הושלמו אינן מתבטלות אם האצווה נעצרת.",
"Diagnostics exclude file contents and paths. Rollback succeeds only while the managed copy matches its receipt.":"האבחון אינו כולל תוכן קבצים או נתיבים. הביטול מצליח רק כל עוד העותק המנוהל תואם לתיעוד שלו.",
"Native preview required":"נדרשת תצוגה מקדימה מקומית",
"Inline preview unavailable":"תצוגה מקדימה בתוך Mesh אינה זמינה",
"Loading exact file preview…":"טוען תצוגה מקדימה של הקובץ המדויק…",
"Mesh is verifying the current working bytes before showing content.":"Mesh מאמת את תוכן קובץ העבודה לפני הצגתו.",
"Use Open in Finder to browse this exact folder, or expand it in Explorer.":"בחרו פתיחה ב־Finder כדי לעיין בתיקייה המדויקת, או הרחיבו אותה בסייר.",
"In custody":"באחסון מוגן",
"Repository actions":"פעולות הפרויקט",
"Navigate inspectable changes":"ניווט בשינויים שניתן לבדוק",
"How Mesh handles working changes":"איך Mesh מטפל בשינויי עבודה",
"Identity and working-tree state":"זהות ומצב קבצי העבודה",
"Auto-save safe changes":"שמירה אוטומטית של שינויים בטוחים",
"Choose a file or folder":"בחירת קובץ או תיקייה",
"Check the working folder":"בדיקת תיקיית העבודה",
"Checking folder…":"בודק את התיקייה…",
"Source control":"ניהול שינויים",
"Source control collapsed":"ניהול השינויים מכווץ",
"WORKING":"בעבודה",
"Working tree":"קבצי העבודה",
"Show Changes":"הצגת שינויים",
"Hide":"הסתרה",
"Review current folder changes":"סקירת שינויים בתיקייה הנוכחית",
"Search working changes":"חיפוש שינויי עבודה",
"No working changes":"אין שינויי עבודה",
"No matching changes":"אין שינויים תואמים",
"No changed files match these filters.":"אין קבצים שהשתנו התואמים לסינון.",
"No files match this filter.":"אין קבצים התואמים לסינון.",
"Adjust the search or status filter.":"שנו את החיפוש או את סינון המצב.",
"Select a working change":"בחירת שינוי בעבודה",
"Filter changed files…":"סינון קבצים שהשתנו…",
"Filter changes by status":"סינון שינויים לפי מצב",
"Folder check incomplete":"בדיקת התיקייה לא הושלמה",
"Retry the folder check before saving or review.":"יש לנסות שוב את בדיקת התיקייה לפני שמירה או סקירה.",
"Run a folder check to compare current bytes with private history.":"הפעילו בדיקת תיקייה כדי להשוות את התוכן הנוכחי להיסטוריה הפרטית.",
"Mesh is comparing current bytes with private history.":"Mesh משווה את התוכן הנוכחי להיסטוריה הפרטית.",
"Mesh could not complete an exact comparison. Retry before trusting or saving this view.":"Mesh לא הצליח להשלים השוואה מדויקת. נסו שוב לפני שמירה או הסתמכות על תצוגה זו.",
"The native folder matches private history exactly.":"תיקיית העבודה תואמת בדיוק להיסטוריה הפרטית.",
"The native folder matches the latest private version. Edit a file in your usual app, then check again.":"תיקיית העבודה תואמת לגרסה הפרטית האחרונה. ערכו קובץ ביישום הרגיל שלכם ובדקו שוב.",
"Check the native folder, then select a changed file to see its exact inline or split diff here.":"בדקו את תיקיית העבודה ובחרו קובץ שהשתנה כדי לראות כאן השוואה מדויקת, רציפה או מפוצלת.",
"Choose an inspectable file from Source control to see its exact inline or split diff.":"בחרו קובץ שניתן לבדוק מתוך ניהול השינויים כדי לראות השוואה מדויקת, רציפה או מפוצלת.",
"This workspace has no files or folders yet.":"בסביבת עבודה זו אין עדיין קבצים או תיקיות.",
"Binary or large content stays outside the text editor. Mesh still tracks and saves it by exact identity.":"תוכן בינארי או גדול אינו מוצג בעורך הטקסט. Mesh עדיין עוקב אחריו ושומר אותו לפי זהותו המדויקת.",
"Use Files to inspect an exact workspace entry.":"השתמשו בקבצים כדי לבדוק פריט מדויק בסביבת העבודה.",
"Inspected working text":"טקסט עבודה שנבדק",
"Text workspace view":"תצוגת טקסט בסביבת העבודה",
"Content diff layout":"פריסת השוואת תוכן",
"Preview unavailable":"התצוגה המקדימה אינה זמינה",
"Previewing the first":"מציג תצוגה מקדימה של",
"lines. Open the exact file for the complete content.":"השורות הראשונות. פתחו את הקובץ המדויק לתוכן המלא.",
"Showing changes":"מציג שינויים",
"Showing the first":"מציג את הפריטים הראשונים מתוך",
" shown":" מוצגים",
"Missing tracked file":"קובץ במעקב חסר",
"Resolve missing file":"טיפול בקובץ חסר",
"Find a missing tracked file":"חיפוש קובץ חסר במעקב",
"Filter missing files…":"סינון קבצים חסרים…",
"Find a possible destination":"חיפוש יעד אפשרי",
"Filter possible destinations…":"סינון יעדים אפשריים…",
"Resolution":"פתרון",
"It was deleted":"הקובץ נמחק",
"Agent folder assigned":"תיקייה משויכת לסוכן",
"Agent folder available":"תיקיית סוכן זמינה",
"No workspace or agent matches this search.":"אין סביבת עבודה או סוכן התואמים לחיפוש.",
"No reported conditions.":"לא דווחו מצבים הדורשים טיפול.",
"Open another version":"פתיחת גרסה אחרת",
"Return to previous workspace":"חזרה לסביבת העבודה הקודמת",
"Files in this point":"קבצים בנקודת שמירה זו",
"No destination selected.":"לא נבחר יעד.",
"Choose a destination and preview one file or the saved workspace. No destination entry changes until you review a plan and confirm it.":"בחרו יעד והציגו קובץ או סביבת עבודה שמורה בתצוגה מקדימה. שום פריט ביעד לא ישתנה עד לסקירת התוכנית ואישורה.",
"Select an earlier saved version and preview it. Mesh will verify the exact retained bytes and the current working file before Restore becomes available.":"בחרו גרסה שמורה קודמת והציגו אותה בתצוגה מקדימה. Mesh יאמת את התוכן השמור המדויק ואת קובץ העבודה לפני שהשחזור יתאפשר.",
"Restore is currently unavailable.":"השחזור אינו זמין כרגע.",
"Resolve the active workspace condition before applying this verified preview.":"יש לטפל במצב הפעיל בסביבת העבודה לפני החלת התצוגה המאומתת.",
"Custom private location":"מיקום פרטי מותאם",
"No":"לא",
"Yes":"כן",
"Bytes":"בתים",
"Executable":"ניתן להרצה",
"Digest":"סיכום אימות",
"Exact file metadata":"נתונים מדויקים על הקובץ",
"Saved file metadata comparison":"השוואת נתוני קבצים שמורים",
"Inert":"ללא הרצה",
"document":"מסמך",
"image":"תמונה",
"All sections":"כל החלקים",
"Artifact section":"חלק במסמך",
"Document section comparison":"השוואת חלקי מסמך",
"Section":"חלק",
"Previous section":"החלק הקודם",
"Next section":"החלק הבא",
"Load content comparison":"טעינת השוואת תוכן",
"Try content comparison again":"ניסיון נוסף להשוואת תוכן",
"Reading exact versions…":"קורא את הגרסאות המדויקות…",
"Reading…":"קורא…",
"PDF page comparison":"השוואת עמודי PDF",
"PDF page content comparison":"השוואת תוכן עמודי PDF",
"Earlier recorded reviews":"סקירות קודמות שנשמרו",
"Earlier saved reviews":"סקירות שמורות קודמות",
"Approve and create Git branch":"אישור ויצירת ענף Git",
"Create Git branch":"יצירת ענף Git",
"Filter live changes":"סינון שינויים חיים",
"Live changed files":"קבצים שהשתנו בעבודה חיה",
"No live changes match this filter.":"אין שינויים חיים התואמים לסינון.",
"No live file changes are currently visible.":"אין כרגע שינויי קבצים חיים להצגה.",
"Stable live file snapshot":"תמונת מצב יציבה של קובץ חי",
"Stable snapshot unavailable":"תמונת מצב יציבה אינה זמינה",
"Inspect stable snapshot":"בדיקת תמונת מצב יציבה",
"Retry snapshot":"ניסיון נוסף לתמונת מצב",
"Mutable working file · exact snapshot required":"קובץ עבודה משתנה · נדרשת תמונת מצב מדויקת",
"Choose Inspect stable snapshot to read this changing file twice under exact agent custody.":"בחרו בדיקת תמונת מצב יציבה כדי לקרוא את הקובץ המשתנה פעמיים תוך אימות השליטה של הסוכן.",
"Choose an assigned workspace above, or start an agent from Current. Saved Review remains available separately.":"בחרו סביבת עבודה משויכת למעלה או הפעילו סוכן מתוך נוכחי. סקירת גרסאות שמורות זמינה בנפרד.",
"This saved path is currently missing. There are no live bytes to preview.":"הנתיב השמור חסר כעת. אין תוכן חי לתצוגה מקדימה.",
"This is a new folder. Finish agent handoff will authoritatively inspect its complete descendants.":"זוהי תיקייה חדשה. סיום העבודה עם הסוכן יבדוק את כל תוכנה.",
"Mesh will not follow or preview this unsupported entry. Remove or replace it with a regular file, then retry.":"Mesh לא יעקוב אחר פריט זה ולא יציג אותו, כי סוגו אינו נתמך. הסירו אותו או החליפו אותו בקובץ רגיל ונסו שוב.",
"Wait for the current write to finish, then retry. Nothing was recorded or saved.":"המתינו לסיום הכתיבה הנוכחית ונסו שוב. דבר לא תועד או נשמר.",
"Read-only snapshot from the assigned agent folder. Selecting the file again refreshes it; Mesh never saves from this preview.":"תמונת מצב לקריאה בלבד מתיקיית הסוכן המשויך. בחירה חוזרת בקובץ מרעננת אותה; Mesh אינו שומר מתוך תצוגה זו.",
"Monitoring never saves or approves work. Finish agent handoff still performs the authoritative complete scan before the work enters private history and Review.":"המעקב אינו שומר או מאשר עבודה. סיום העבודה עם הסוכן מבצע את הסריקה המלאה לפני שהעבודה נכנסת להיסטוריה הפרטית ולסקירה.",
"This folder has no importable files or folders. Choose another folder containing project content. No workspace can be created from this preview.":"בתיקייה זו אין קבצים או תיקיות שניתן לייבא. בחרו תיקייה אחרת המכילה תוכן של פרויקט. לא ניתן ליצור סביבת עבודה מתצוגה מקדימה זו.",
"Choose a folder with content":"בחירת תיקייה עם תוכן",
"Finish this agent handoff?":"לסיים את העבודה עם הסוכן?",
"Mark this agent folder finished only after every Codex session, terminal agent, and editor using its pinned path has stopped. Mesh will inspect the complete folder and privately save unambiguous file and folder changes. Renames, deletions, and unsupported entries will remain for your review.":"סמנו את העבודה בתיקיית הסוכן כהסתיימה רק לאחר שכל הפעלות Codex, סוכני המסוף והעורכים המשתמשים בנתיב הקבוע שלה נעצרו. Mesh יבדוק את כל התיקייה וישמור באופן פרטי שינויים חד־משמעיים בקבצים ובתיקיות. שינויי שם, מחיקות ופריטים לא נתמכים יישארו לסקירתכם.",
"Reopen this assigned Codex folder?":"לפתוח מחדש את תיקיית Codex המשויכת?",
"Reopen this assigned agent terminal?":"לפתוח מחדש מסוף לסוכן המשויך?",
"Reopen Codex folder":"פתיחה מחדש של תיקיית Codex",
"Reopen agent terminal":"פתיחה מחדש של מסוף הסוכן",
"This exact writable folder was already handed to an agent. Two agents in one folder can overwrite each other. Use Start another agent copy for concurrent work. Reopen this folder only if the prior agent has stopped. Reopen assigned Codex folder?":"תיקיית העבודה הזו כבר נמסרה לסוכן. שני סוכנים באותה תיקייה עלולים לדרוס זה את עבודתו של זה. לעבודה במקביל, הפעילו עותק נוסף לסוכן. פתחו תיקייה זו מחדש רק אם הסוכן הקודם נעצר. לפתוח מחדש את תיקיית Codex המשויכת?",
"This exact writable folder was already handed to an agent. Two agents in one folder can overwrite each other. Use Start another agent copy for concurrent work. Reopen this folder only if the prior agent has stopped. Reopen an agent terminal?":"תיקיית העבודה הזו כבר נמסרה לסוכן. שני סוכנים באותה תיקייה עלולים לדרוס זה את עבודתו של זה. לעבודה במקביל, הפעילו עותק נוסף לסוכן. פתחו תיקייה זו מחדש רק אם הסוכן הקודם נעצר. לפתוח מחדש מסוף לסוכן?",
"Remove this managed workspace?":"להסיר סביבת עבודה מנוהלת זו?",
"Edit here or work normally in the stable native folder with a local editor. Give Terminal or a long-running agent the independent agent folder shown under Current; it starts at the selected durable version and then remains writable even if Mesh switches elsewhere. Returning to Mesh automatically inspects the selected folder; selecting a different recent agent folder inspects it immediately, while inactive agent folders are not continuously watched. Find folder changes retries the read explicitly.":"ערכו כאן או עבדו כרגיל בתיקיית העבודה הקבועה עם עורך מקומי. למסוף או לסוכן ממושך תנו את תיקיית הסוכן העצמאית המוצגת תחת נוכחי; היא מתחילה מהגרסה השמורה שנבחרה ונשארת ניתנת לעריכה גם אם Mesh עובר למקום אחר. החזרה ל־Mesh בודקת אוטומטית את התיקייה שנבחרה. בחירת תיקיית סוכן אחרונה אחרת בודקת אותה מיד; תיקיות סוכן לא פעילות אינן במעקב רציף. איתור שינויים בתיקייה מבצע קריאה מפורשת נוספת.",
"Inspect re-reads exact operating-system bytes; binary and large files stay outside the text editor but remain savable. Choose Save privately to sign and append one inspected file. Mesh reviews a complete new folder tree and admits its folders parent-first. Outside the confirmed agent-finish flow, saving remains an explicit authenticated action. Choose Save all privately for the complete inspected queue. Automatic save uses the same complete scan, reinspection, signature, and post-save verification. It pauses for deletions, renames, symbolic links, special entries, active agent handoffs, or files that keep changing. Mesh stops on the first mismatch.":"הבדיקה קוראת מחדש את תוכן הקבצים המדויק ממערכת ההפעלה; קבצים בינאריים וגדולים אינם מוצגים בעורך הטקסט אך ניתן לשמור אותם. שמירה פרטית חותמת ושומרת קובץ שנבדק. Mesh בודק עץ תיקיות חדש במלואו ומוסיף תיקיות אב לפני ילדיהן. מחוץ לתהליך המאושר של סיום עבודת סוכן, השמירה היא פעולה מפורשת ומאומתת. שמירת הכול באופן פרטי שומרת את כל התור שנבדק. שמירה אוטומטית משתמשת באותה סריקה מלאה, בדיקה חוזרת, חתימה ואימות לאחר שמירה. היא נעצרת במחיקות, בשינויי שם, בקישורים סמליים, בפריטים מיוחדים, בזמן עבודה עם סוכן או כשקבצים ממשיכים להשתנות. Mesh עוצר באי־ההתאמה הראשונה.",
"Exporting a separate copy, confirming review, and approving are independent actions. It does not approve or change the original folder. Agents and web content cannot skip the native user-presence approval ceremony.":"ייצוא עותק נפרד, אישור השלמת סקירה ואישור מוגן הם פעולות עצמאיות. הייצוא אינו מאשר או משנה את תיקיית המקור. סוכנים ותוכן אינטרנט אינם יכולים לעקוף את תהליך האישור המקומי הדורש נוכחות משתמש.",
"Use the stable folder for Finder and editors, or the independent real folder for Terminal and agents. The independent folder is writable and does not move when Mesh switches elsewhere. Return here to inspect changes, save a private version, open another version, or update the original folder from saved work.":"השתמשו בתיקייה הקבועה עבור Finder ועורכים, או בתיקייה העצמאית למסוף ולסוכנים. התיקייה העצמאית ניתנת לעריכה ואינה עוברת מקום כאשר Mesh עובר לגרסה אחרת. חזרו לכאן לבדיקת שינויים, שמירת גרסה פרטית, פתיחת גרסה אחרת או עדכון תיקיית המקור מתוך עבודה שמורה.",
"Keep reviewing":"המשך סקירה",
"Update changed files":"עדכון קבצים שהשתנו",
"Coordinator provider": "ספק הסוכן המתאם",
  "Allowed providers": "ספקים מורשים",
  "Provider choices unavailable. Refresh before starting agents.": "בחירת הספקים אינה זמינה. רעננו לפני הפעלת סוכנים.",
  "Agent fleets":"ציי סוכנים",
"Optional agents work in independent lanes created from a saved version. Keep using your original project and harness as usual.":"סוכנים אופציונליים עובדים במסלולים עצמאיים שנוצרו מגרסה שמורה. המשיכו להשתמש בפרויקט המקורי ובכלי הסוכנים שלכם כרגיל.",
"Provision a fleet from saved work":"הכנת צי מתוך עבודה שמורה",
"Choose project":"בחירת פרויקט",
"Starting saved version":"גרסה שמורה להתחלה",
"Choose exact saved version":"בחירת גרסה שמורה מדויקת",
"retained selection":"בחירה שנשמרה",
"Use “Show latest versions” on the project below to make older versions available here.":"השתמשו בהצגת גרסאות אחרונות בפרויקט למטה כדי לאפשר בחירה בגרסאות קודמות כאן.",
"What should the agents accomplish?":"מה על הסוכנים להשיג?",
"Maximum lanes, including coordinator":"מספר מסלולים מרבי, כולל המתאם",
"Agents running at once":"סוכנים הפועלים בו־זמנית",
"Delegation depth":"עומק האצלה",
"All selected providers need an installed executable and account. Provisioning creates the lane; Start agents begins provider usage. Failed or uncertain attempts are not retried automatically.":"כל ספק שנבחר דורש תוכנה מותקנת וחשבון. הכנת הצי יוצרת את המסלול; הפעלת סוכנים מתחילה שימוש בספק. ניסיונות שנכשלו או שתוצאתם אינה ודאית אינם חוזרים אוטומטית.",
"Provision fleet":"הכנת צי",
"Provisioning not yet confirmed. This request keeps the same starting version and limits.":"ההכנה טרם אושרה. בקשה זו שומרת על אותה גרסת התחלה ואותן מגבלות.",
"lanes":"מסלולים",
"agents at once":"סוכנים בו־זמנית",
"depth":"עומק",
"Retry this provisioning request":"ניסיון נוסף לאותה בקשת הכנה",
"Refresh fleets":"רענון ציים",
"Saved fleets could not be loaded.":"לא ניתן לטעון את הציים השמורים.",
"No fleets yet. Manual work and externally run harnesses remain available below.":"עדיין אין ציים. עבודה ידנית וכלי סוכנים חיצוניים נשארים זמינים למטה.",
"Retained fleet":"צי שנשמר",
"Fleet identity":"זהות הצי",
"Saved state · workers need recovery before execution":"מצב שמור · נדרש שחזור של הסוכנים לפני הפעלה",
"Fleet unavailable · retained work needs recovery":"הצי אינו זמין · העבודה שנשמרה דורשת שחזור",
"Stopped scheduling · worker ownership retained":"התזמון נעצר · השליטה בסוכנים נשמרת",
"Needs attention · new agents will not start":"נדרשת בדיקה · סוכנים חדשים לא יופעלו",
"Stop requested":"התבקשה עצירה",
"Monitoring agents":"מעקב אחר סוכנים",
"Lane allocation incomplete":"הקצאת המסלול אינה שלמה",
"Saved run status · no live observations":"מצב הפעלה שמור · אין תצפיות חיות",
"Provisioned · agents have not started":"הצי הוכן · הסוכנים טרם הופעלו",
"Start agents":"הפעלת סוכנים",
"Stop agents":"עצירת סוכנים",
"No worker observations in this app session":"אין תצפיות על סוכנים בהפעלה זו של היישום",
"Observed":"נצפה לפני",
"Observation time unavailable":"זמן התצפית אינו זמין",
"Worker lane":"מסלול סוכן",
"Coordinator lane":"מסלול מתאם",
"Last saved state":"מצב שמור אחרון",
"Saved lane · recovery required":"מסלול שמור · נדרש שחזור",
"Waiting to start":"ממתין להפעלה",
"Allocation needs attention":"ההקצאה דורשת בדיקה",
"No activity reported":"לא דווחה פעילות",
"events":"אירועים",
"Lane and starting version":"מסלול וגרסת התחלה",
"Lane":"מסלול",
"Parent lane":"מסלול אב",
"Starting version":"גרסת התחלה",
"No attached source":"אין מקור מחובר",
"Agent completion does not approve changes to main. Fleet result review and recovery are not available yet.":"סיום עבודת סוכן אינו מאשר שינויים לגרסה הראשית. סקירת תוצאות הצי ושחזורו עדיין אינם זמינים.",
"Starting":"מתחיל",
"Working":"עובד",
"Waiting":"ממתין",
"Needs recovery":"נדרש שחזור",
"Stop requested · ownership reserved":"התבקשה עצירה · השליטה נשמרת",
"Execution completed":"ההרצה הסתיימה",
"Execution failed":"ההרצה נכשלה",
"Cancelled":"בוטל",
"Fleet status could not be confirmed. Existing work is retained. Refresh before starting more work.":"לא ניתן לאמת את מצב הצי. העבודה הקיימת נשמרת. רעננו לפני הפעלת עבודה נוספת.",
"Fleet provisioned. Review it below, then choose Start agents.":"הצי הוכן. בדקו אותו למטה ולאחר מכן בחרו בהפעלת סוכנים.",
"Start could not yet be confirmed. Check the selected providers and accounts and fleet status before retrying.":"ההפעלה טרם אומתה. בדקו את הספקים והחשבונות שנבחרו ואת מצב הצי לפני ניסיון נוסף.",
"Stop could not yet be confirmed. Refresh and retry the stop request for this fleet.":"העצירה טרם אומתה. רעננו ונסו שוב את בקשת העצירה של צי זה.",
"Start requested. Activity appears below.":"התבקשה הפעלה. הפעילות מוצגת למטה.",
"Stop requested. Ownership remains reserved until worker recovery is verified.":"התבקשה עצירה. השליטה נשמרת עד לאימות שחזור הסוכנים.",
"Fleet lane":"מסלול צי",
"Pinned saved result":"תוצאה שמורה מוצמדת",
"Read-only saved result. Approval and integration into the original project's main are not available here.":"תוצאה שמורה לקריאה בלבד. אישור ושילוב בגרסה הראשית של הפרויקט המקורי אינם זמינים כאן.",
"changes in this saved review":"שינויים בסקירה שמורה זו",
"Review already recorded":"הסקירה כבר נשמרה",
"This panel shows an existing immutable review.":"חלונית זו מציגה סקירה שמורה שאינה משתנה.",
"Pinned fleet review":"סקירת צי מוצמדת",
"Close review":"סגירת סקירה",
"Comparison base: this review's recorded lane base. Comparison with the lane's starting input is not available yet.":"בסיס ההשוואה: בסיס המסלול שנשמר בסקירה זו. השוואה לתוכן ההתחלתי של המסלול עדיין אינה זמינה.",
"Exact saved selection and base":"בחירה ובסיס שמורים מדויקים",
"Fleet":"צי",
"Checkpoint":"נקודת שמירה",
"Saved operation":"פעולה שמורה",
"Recorded base head":"ראש הבסיס השמור",
"Lane starting input":"תוכן התחלתי של המסלול",
"Reading the exact saved result…":"קורא את התוצאה השמורה המדויקת…",
"Any content below is the previously verified cached result.":"התוכן המוצג למטה הוא התוצאה הקודמת שנשמרה במטמון ואומתה.",
"Retry exact saved result":"ניסיון נוסף לתוצאה השמורה המדויקת",
"This review is incomplete or unavailable.":"סקירה זו אינה שלמה או שאינה זמינה.",
"operations are not listed. No complete comparison is shown.":"פעולות אינם מוצגים. לא מוצגת השוואה מלאה.",
"The saved comparison could not be safely displayed. Its exact selection is retained.":"לא ניתן להציג את ההשוואה השמורה באופן מאומת. הבחירה המדויקת נשמרת.",
"No file changes in this recorded comparison.":"אין שינויים בקבצים בהשוואה שמורה זו.",
"Pinned fleet reviews":"סקירות צי מוצמדות",
"Panels keep independent file selections and comparison layouts while agents continue working. Pins currently stay in this app view; they are not restored after an app reload.":"החלוניות שומרות על בחירת קבצים ותצוגות השוואה עצמאיות בזמן שהסוכנים ממשיכים לעבוד. ההצמדות נשמרות כרגע בתצוגה זו בלבד; הן אינן משוחזרות לאחר טעינה מחדש של היישום.",
"Saved lane results":"תוצאות מסלול שמורות",
"Refresh saved results":"רענון תוצאות שמורות",
"Show saved results":"הצגת תוצאות שמורות",
"Close result list":"סגירת רשימת תוצאות",
"Reading saved results…":"קורא תוצאות שמורות…",
"recorded results. This page stays fixed while agents work; refresh to discover more.":"תוצאות שמורות. דף זה נשאר קבוע בזמן עבודת הסוכנים; רעננו להצגת תוצאות נוספות.",
"No submitted saved reviews yet.":"עדיין אין סקירות שמורות שהוגשו.",
"End of the saved-result list.":"סוף רשימת התוצאות השמורות.",
"Result identity":"זהות התוצאה",
"Run":"הרצה",
"Pin saved review":"הצמדת סקירה שמורה",
"Next saved results":"התוצאות השמורות הבאות",
"Close a saved-result list before opening another.":"סגרו רשימת תוצאות שמורות לפני פתיחת רשימה נוספת.",
"Saved results could not be loaded. The previous page is retained.":"לא ניתן לטעון תוצאות שמורות. הדף הקודם נשמר.",
"This exact saved result could not be verified. Its selection is retained.":"לא ניתן לאמת את התוצאה השמורה המדויקת. הבחירה נשמרת.",
"This exact result is already pinned.":"תוצאה מדויקת זו כבר מוצמדת.",
"Close a review panel before opening another. Eight can stay pinned together.":"סגרו חלונית סקירה לפני פתיחת חלונית נוספת. ניתן להצמיד שמונה חלוניות יחד.",
"Agent completion does not approve changes to main. Saved reviews can be pinned above. Starting-input comparison, approval and worker recovery are not available yet.":"סיום עבודת סוכן אינו מאשר שינויים לגרסה הראשית. ניתן להצמיד סקירות שמורות למעלה. השוואה לתוכן ההתחלתי, אישור ושחזור סוכנים עדיין אינם זמינים.",
"Comparison base: the recorded review uses its original lane review base. Use the starting-version comparison below to inspect what this lane changed.":"בסיס ההשוואה: הסקירה השמורה משתמשת בבסיס הסקירה המקורי של המסלול. השתמשו בהשוואה לגרסת ההתחלה למטה כדי לבדוק מה השתנה במסלול.",
"Recorded review against its original review base":"סקירה שמורה מול בסיס הסקירה המקורי שלה",
"Agent completion does not approve changes to main. Saved reviews can be pinned above. Approval and worker recovery are not available yet.":"סיום עבודת סוכן אינו מאשר שינויים לגרסה הראשית. ניתן להצמיד סקירות שמורות למעלה. אישור ושחזור סוכנים עדיין אינם זמינים.",
"A saved side is unavailable as bounded text. Inspect its metadata below.":"אחד הצדדים השמורים אינו זמין כטקסט בגודל הנתמך. בדקו את נתוני הקובץ למטה.",
"Inspect the saved side previews below.":"בדקו את תצוגות הצדדים השמורים למטה.",
"These saved texts are identical. Paths and executable modes may differ.":"הטקסטים השמורים האלה זהים. הנתיבים והרשאות ההרצה עשויים להיות שונים.",
"Lane starting version":"גרסת ההתחלה של המסלול",
"Pinned result":"תוצאה מוצמדת",
"Content identity":"זהות התוכן",
"File exceeds the 256 KiB text preview limit.":"הקובץ חורג ממגבלת תצוגת הטקסט של 256 KiB.",
"Binary or unsafe text content; text preview unavailable.":"תוכן בינארי או טקסט שאינו בטוח לתצוגה; תצוגת טקסט אינה זמינה.",
"Changes since lane start":"שינויים מאז תחילת המסלול",
"Changes since this lane started":"שינויים מאז תחילת מסלול זה",
"Compares the verified starting version with this pinned saved result. Current working files do not enter this comparison.":"משווה את גרסת ההתחלה המאומתת לתוצאה השמורה המוצמדת הזו. קובצי העבודה הנוכחיים אינם חלק מהשוואה זו.",
"First page of changes":"הדף הראשון של השינויים",
"Compare with starting version":"השוואה לגרסת ההתחלה",
"Reading the exact starting-version comparison… The previous selection remains below.":"קורא את ההשוואה המדויקת לגרסת ההתחלה… הבחירה הקודמת נשארת למטה.",
"Retry this comparison request":"ניסיון נוסף לאותה בקשת השוואה",
"changed objects":"פריטים שהשתנו",
"on this page":"בדף זה",
"Exact comparison versions":"גרסאות ההשוואה המדויקות",
"Local starting version":"גרסת התחלה מקומית",
"No path, content or executable-mode changes since this lane started.":"אין שינויים בנתיב, בתוכן או בהרשאות הרצה מאז תחילת מסלול זה.",
"Moved; content may also differ":"הועבר; ייתכן שגם התוכן השתנה",
"Content or metadata changed":"התוכן או נתוני הקובץ השתנו",
"Next changed objects":"הפריטים שהשתנו הבאים",
"Use inline comparison":"השוואה בתצוגה משולבת",
"Use side-by-side comparison":"השוואה זה לצד זה",
"Read-only comparison. It does not approve or apply changes to main.":"השוואה לקריאה בלבד. היא אינה מאשרת או מחילה שינויים על הגרסה הראשית.",
"This starting-version comparison could not be verified. Any displayed content is the previously verified result.":"לא ניתן לאמת את ההשוואה לגרסת ההתחלה. התוכן המוצג הוא התוצאה הקודמת שאומתה.",
"bytes":"בתים",
"Waiting for the native decision confirmation…":"ממתין לאישור ההחלטה בחלון המערכת…",
"Keep the original decision retry, or read the latest state to choose again. Reloading does not cancel a native confirmation already in progress.":"אפשר לנסות שוב את אותה החלטה, או לקרוא את המצב העדכני ולבחור מחדש. טעינה מחדש אינה מבטלת אישור שכבר מתבצע בחלון המערכת.",
"Retry this exact decision":"ניסיון נוסף לאותה החלטה",
"Read latest state and choose again":"קריאת המצב העדכני ובחירה מחדש",
"Request marked addressed. This is not approval or integration into main.":"הבקשה סומנה כטופלה. פעולה זו אינה אישור או שילוב בגרסה הראשית.",
"Reopen change request":"פתיחת בקשת השינוי מחדש",
"Request open.":"הבקשה פתוחה.",
"Read the current decision before choosing a result.":"יש לקרוא את ההחלטה הנוכחית לפני בחירת תוצאה.",
"Mark request addressed by this result":"סימון הבקשה כטופלה באמצעות תוצאה זו",
"Latest request decisions loaded.":"ההחלטות העדכניות על הבקשות נטענו.",
"Confirmation cancelled. The current recorded decision is shown.":"האישור בוטל. ההחלטה הרשומה כעת מוצגת.",
"Decision receipt verified. The current recorded decision is shown.":"רישום ההחלטה אומת. ההחלטה הרשומה כעת מוצגת.",
"Decision is unconfirmed. Retry the same operation or read the latest state before choosing again.":"ההחלטה לא אומתה. נסו שוב את אותה פעולה או קראו את המצב העדכני לפני בחירה מחדש.",

"Fixed project comparison":"השוואת פרויקט קבועה",
"Compare this result with project main":"השוואת התוצאה לגרסה הראשית של הפרויקט",
"Shows the complete proposed project, including inherited work. Preparation fixes the main version and preserves the request before copying saved content.":"מציג את הפרויקט המוצע במלואו, כולל עבודה ממסלולים קודמים. ההכנה מקבעת את הגרסה הראשית ושומרת את הבקשה לפני העתקת תוכן שמור.",
"Prepare comparison with current main":"הכנת השוואה לגרסה הראשית הנוכחית",
"Fixed main":"גרסה ראשית קבועה",
"Initial empty main":"גרסה ראשית התחלתית ריקה",
"Saved preparation inputs":"נתוני הכנה שמורים",
"Request":"בקשה",
"Read fixed comparison from first page":"קריאת ההשוואה הקבועה מהדף הראשון",
"Retry preparing these exact inputs":"ניסיון הכנה נוסף עם אותם נתונים בדיוק",
"Verifying the fixed project comparison…":"מאמת את השוואת הפרויקט הקבועה…",
"Any content below is the previously verified result.":"התוכן המוצג למטה הוא התוצאה הקודמת שאומתה.",
"Retry the last comparison request":"ניסיון נוסף לבקשת ההשוואה האחרונה",
"Main matched this base when last checked.":"הגרסה הראשית תאמה לבסיס זה בבדיקה האחרונה.",
"Main has advanced. This comparison remains pinned to its original base.":"הגרסה הראשית התקדמה. השוואה זו נשארת צמודה לבסיס המקורי שלה.",
"Exact comparison identity":"הזהות המדויקת של ההשוואה",
"Comparison":"השוואה",
"Saved result":"תוצאה שמורה",
"Last observed main":"הגרסה הראשית שנצפתה לאחרונה",
"No content, path or executable-mode changes against this main version.":"אין שינויים בתוכן, בנתיב או בהרשאות הרצה ביחס לגרסה ראשית זו.",
"Next changed paths":"הנתיבים שהשתנו הבאים",
"Fixed project main":"הגרסה הראשית הקבועה של הפרויקט",
"Preparation and inspection do not approve changes, advance main, or replace working files. Reopening only reads saved content and never restarts workers.":"הכנה ובדיקה אינן מאשרות שינויים, מקדמות את הגרסה הראשית או מחליפות קובצי עבודה. פתיחה מחדש קוראת תוכן שמור בלבד ואינה מפעילה עובדים מחדש.",
"Preparation is unconfirmed. Keep the saved request and retry its exact inputs. Resolve any saved-selection error first.":"ההכנה לא אומתה. יש לשמור את הבקשה ולנסות שוב עם אותם נתונים בדיוק. תחילה יש לפתור שגיאות בשמירת הבחירה.",
"This fixed comparison is unavailable. Its saved inputs and any previously verified content are retained. Preparing missing content requires an explicit retry.":"השוואה קבועה זו אינה זמינה. הנתונים השמורים והתוכן שאומת קודם נשמרים. הכנת תוכן חסר דורשת ניסיון נוסף מפורש.",
"Saved project version and review":"גרסת פרויקט שמורה ובדיקה",
"Project version and review":"גרסת פרויקט ובדיקה",
"Refresh saved version and review":"רענון הגרסה השמורה והבדיקה",
"Retry saving this project version":"ניסיון נוסף לשמירת גרסת הפרויקט",
"Save as a project version":"שמירה כגרסת פרויקט",
"Verifying this saved version and review…":"אימות הגרסה השמורה והבדיקה…",
"Retry the exact request":"ניסיון נוסף לאותה בקשה בדיוק",
"A signed save is pending. Refresh only reads its status; an explicit retry resumes it.":"שמירה חתומה ממתינה להשלמה. רענון קורא רק את מצבה; ניסיון נוסף מפורש ממשיך אותה.",
"A private project version is saved.":"גרסת פרויקט פרטית נשמרה.",
"Saved version identity":"זהות הגרסה השמורה",
"Create project review":"יצירת בדיקת פרויקט",
"Project review is ready for inspection.":"בדיקת הפרויקט מוכנה לעיון.",
"Main has advanced. This review keeps its original base.":"הגרסה הראשית התקדמה. בדיקה זו שומרת על הבסיס המקורי שלה.",
"Exact project review":"בדיקת הפרויקט המדויקת",
"Review evidence is incomplete; approval is unavailable.":"הראיות לבדיקה אינן שלמות; האישור אינו זמין.",
"additional changes are not listed here.":"שינויים נוספים אינם מוצגים כאן.",
"This exact review is also available in the project's Reviews. Approval remains a separate human action.":"בדיקה מדויקת זו זמינה גם בבדיקות הפרויקט. אישור נשאר פעולה אנושית נפרדת.",
"The saved version or its review could not be confirmed. Keep these exact inputs and retry, or refresh to inspect retained progress.":"לא ניתן היה לאמת את הגרסה השמורה או את הבדיקה שלה. יש לשמור את הנתונים המדויקים ולנסות שוב, או לרענן כדי לבדוק את ההתקדמות שנשמרה.",
"Open this project review":"פתיחת בדיקת פרויקט זו",
"Pending review operations":"פעולות בדיקה ממתינות",
"Saved inputs survive closed panels and restarts. Refresh reads only; retry submits the exact saved request.":"הנתונים השמורים נשארים לאחר סגירת חלוניות והפעלה מחדש. רענון קורא בלבד; ניסיון נוסף שולח את הבקשה השמורה המדויקת.",
"Refresh pending operations":"רענון הפעולות הממתינות",
"Exact pending inputs":"הנתונים המדויקים הממתינים",
"Retry this exact operation":"ניסיון נוסף לאותה פעולה בדיוק",
"Read current decisions and stop retrying this operation":"קריאת ההחלטות הנוכחיות והפסקת הניסיונות לפעולה זו",
"No pending operations were returned by the last successful read.":"בקריאה המוצלחת האחרונה לא הוחזרו פעולות ממתינות.",
"Request decision":"החלטה על בקשה",
"Expected decision revision":"מהדורת ההחלטה הצפויה",
"Proposed checkpoint":"נקודת השמירה המוצעת",
"Proposed version":"הגרסה המוצעת",
"Proposed review":"הבדיקה המוצעת",
"Pending review inputs could not be confirmed. Refresh or retry the exact operation.":"לא ניתן היה לאמת את נתוני הבדיקה הממתינים. יש לרענן או לנסות שוב את אותה פעולה בדיוק.",
"Saved group execution":"רישום ביצוע הקבוצה שנשמר",
"Saved execution evidence is unavailable in this view.":"רישומי הביצוע שנשמרו אינם זמינים בתצוגה זו.",
"Execution records are unreadable or inconsistent. Use the independent file observations below; no group outcome is verified.":"רישומי הביצוע אינם קריאים או אינם עקביים. יש להיעזר בתצפיות הקבצים הנפרדות שלהלן; לא אומתה תוצאת הקבוצה.",
"Execution records changed during inspection. Inspect the group again before relying on its saved outcome.":"רישומי הביצוע השתנו במהלך הבדיקה. יש לבדוק שוב את הקבוצה לפני הסתמכות על התוצאה שנשמרה.",
"No final group outcome record was found. This does not prove that files were unchanged.":"לא נמצא רישום תוצאה סופית של הקבוצה. אין בכך הוכחה שהקבצים לא השתנו.",
"This is the saved execution record, not a fresh verification of the working folder.":"זהו רישום הביצוע שנשמר, ולא אימות עדכני של תיקיית העבודה.",
"Attempt record found":"נמצא רישום ניסיון",
"No attempt record found":"לא נמצא רישום ניסיון",
"Recorded result:":"התוצאה שנרשמה:",
"change observed":"נצפה שינוי",
"An attempt record alone does not prove a file changed. Missing records never authorize retry.":"רישום ניסיון לבדו אינו מוכיח שקובץ השתנה. רישומים חסרים לעולם אינם מתירים ניסיון חוזר.",
"Working files may have changed since this comparison. Applying changes requires fresh native checks and complete text confirmation. Groups can create complete new folders and create, replace or remove regular files. Removing folders, changing between files and folders, and incomplete or oversized text confirmations remain unavailable.":"ייתכן שקובצי העבודה השתנו מאז ההשוואה. החלת שינויים מחייבת בדיקות מקוריות עדכניות ואישור טקסט מלא. קבוצות יכולות ליצור תיקיות חדשות שלמות וליצור, להחליף או להסיר קבצים רגילים. הסרת תיקיות, שינוי בין קבצים לתיקיות ואישורי טקסט חסרים או גדולים מדי עדיין אינם זמינים.",
"These are separate file and directory observations, not an atomic snapshot. Nothing is retried automatically.":"אלו תצפיות נפרדות על קבצים ותיקיות, ולא תמונת מצב אטומית. אין ניסיון חוזר אוטומטי.",
"Directory contents changed since preparation":"תוכן התיקייה השתנה מאז ההכנה",
"The containing folder was replaced":"התיקייה המכילה הוחלפה",
"The containing folder permissions changed":"הרשאות התיקייה המכילה השתנו",
"New directory tree. No existing work was displaced by this operation; these observations never authorize replay or removal.":"עץ תיקיות חדש. הפעולה לא הזיזה עבודה קיימת; תצפיות אלו לעולם אינן מתירות ביצוע חוזר או הסרה.",
"The containing folder no longer has its recorded identity.":"זהות התיקייה המכילה אינה תואמת עוד לזהות שנרשמה.",
"The containing folder permissions differ from preparation.":"הרשאות התיקייה המכילה שונות מאלו שבהכנה.",
"Prepared tree":"העץ שהוכן",
"entries observed":"רשומות נצפו",
"absent":"חסר",
"unavailable":"לא זמין",
"(tree root)":"(שורש העץ)",
"Working files may have changed since this comparison. Applying changes requires fresh native checks and complete text confirmation. Groups can create complete new folders, move removed folders to recovery, and create, replace or remove regular files. Changing between files and folders and incomplete or oversized text confirmations remain unavailable.":"ייתכן שקובצי העבודה השתנו מאז ההשוואה. החלת שינויים מחייבת בדיקות מקוריות עדכניות ואישור טקסט מלא. קבוצות יכולות ליצור תיקיות חדשות שלמות, להעביר תיקיות שהוסרו לשחזור וליצור, להחליף או להסיר קבצים רגילים. שינוי בין קבצים לתיקיות ואישורי טקסט חסרים או גדולים מדי עדיין אינם זמינים.",
"Directory removal retains the complete original tree. Open file and directory handles may still be writing there. These observations never authorize replay, cleanup or automatic restoration.":"הסרת תיקייה שומרת את העץ המקורי בשלמותו. ידיות פתוחות לקבצים ולתיקיות עשויות עדיין לכתוב בו. תצפיות אלו לעולם אינן מתירות ביצוע חוזר, ניקוי או שחזור אוטומטי.",
"Retained tree":"העץ שנשמר",
"Working files may have changed since this comparison. Applying changes requires fresh native checks and complete text confirmation. Groups can create folders, retain removed folders, convert files and folders, and change regular files. Incomplete or oversized text confirmations remain unavailable.":"ייתכן שקובצי העבודה השתנו מאז ההשוואה. החלת שינויים מחייבת בדיקות מקוריות עדכניות ואישור טקסט מלא. קבוצות יכולות ליצור תיקיות, לשמור תיקיות שהוסרו, להמיר קבצים ותיקיות ולשנות קבצים רגילים. אישורי טקסט חסרים או גדולים מדי עדיין אינם זמינים.",
"Folder to file":"מתיקייה לקובץ",
"File to folder":"מקובץ לתיקייה",
"The original entry and open handles remain in recovery. These observations never authorize replay, cleanup or automatic restoration.":"הפריט המקורי והידיות הפתוחות נשארים באזור השחזור. תצפיות אלו לעולם אינן מתירות ביצוע חוזר, ניקוי או שחזור אוטומטי.",
"Retained entry":"הפריט שנשמר",
"The retained entry was restored as a fresh copy. Original and displaced work remain in recovery; Mesh main is unchanged.":"הפריט שנשמר שוחזר כעותק חדש. העבודה המקורית והעבודה שהוחלפה נשארות באזור השחזור; הגרסה הראשית של Mesh לא השתנתה.",
"Entry restoration needs reconciliation. Inspect recovery before continuing; retained work remains available.":"שחזור הפריט דורש בדיקה. יש לבדוק את אזור השחזור לפני שממשיכים; העבודה שנשמרה עדיין זמינה.",
"Entry restoration or its inspection was not confirmed. Refresh recovery before retrying; working entries may have changed.":"שחזור הפריט או בדיקתו לא אושרו. יש לרענן את אזור השחזור לפני ניסיון נוסף; ייתכן שפריטי העבודה השתנו.",
"Entry restoration was not confirmed or was cancelled. No automatic retry was attempted.":"שחזור הפריט לא אושר או בוטל. לא בוצע ניסיון חוזר אוטומטי.",
"The original retained entry changed since preparation":"הפריט המקורי שנשמר השתנה מאז ההכנה",
"Restoration installs a fresh copy. The original retained entry and any displaced work remain separate; these observations do not authorize replay or cleanup.":"השחזור מתקין עותק חדש. הפריט המקורי שנשמר והעבודה שהוחלפה נשארים בנפרד; תצפיות אלו אינן מתירות ביצוע חוזר או ניקוי.",
"Working entry":"הפריט בתיקיית העבודה",
"New recovery entry":"פריט השחזור החדש",
"Original retained entry":"הפריט המקורי שנשמר",
"Review undoing this restoration":"סקירה לפני ביטול השחזור הזה",
"Review restoring retained entry":"סקירה לפני שחזור הפריט שנשמר",
"File and folder recovery references":"הפניות לשחזור קבצים ותיקיות",
"Inspect a reference before requesting restoration. A reference alone does not verify retained work.":"יש לבדוק הפניה לפני בקשת שחזור. הפניה לבדה אינה מאמתת את העבודה שנשמרה.",
"Inspect retained entry":"בדיקת הפריט שנשמר",
"File and folder restorations in this group":"שחזורי קבצים ותיקיות בקבוצה זו",
"Retained work recovery":"שחזור עבודה שנשמרה",
"Inspect files and folders preserved when applying or restoring work. Open handles may still be writing to retained objects. Nothing is replayed or deleted automatically.":"בדיקת קבצים ותיקיות שנשמרו בעת החלת עבודה או שחזורה. ידיות פתוחות עשויות עדיין לכתוב לפריטים שנשמרו. דבר אינו מופעל שוב או נמחק אוטומטית.",
"Refresh retained work":"רענון העבודה שנשמרה",
"Exact recovery reference within this group":"הפניה מדויקת לשחזור בקבוצה זו",
"Inspect entry in this group":"בדיקת פריט בקבוצה זו",
"Restoring requires complete native confirmation. Current work is preserved in a new recovery entry. Whole-entry restoration keeps the original retained objects available. Undo also requires a new review; nothing is reversed automatically.":"שחזור מחייב אישור מלא בחלון היישום. העבודה הנוכחית נשמרת בפריט שחזור חדש. שחזור פריט שלם משאיר את הפריטים המקוריים שנשמרו זמינים. גם ביטול השחזור מחייב סקירה חדשה; דבר אינו מבוטל אוטומטית.",
});
