//! The equality witness: one digest per generated workload.
//!
//! "The same seed produces the same workload on a different machine" is only a
//! claim if there is something to compare. That something is a digest, and it
//! has to be **unambiguous**: two different item streams must never fold to the
//! same value because their fields happened to concatenate identically. So
//! every field is framed — a tag byte for the variant, a length prefix for every
//! string, fixed little-endian width for every integer — and the framing is
//! part of the contract. `("ab", "c")` and `("a", "bc")` digest differently
//! here, which a bare concatenation would not manage.
//!
//! FNV-1a/64 does the folding, the same function the harness already uses as
//! its correctness witness. It is not a cryptographic hash and is not used as
//! one: nothing here defends against an adversary choosing a corpus to collide,
//! only against a generator drifting. A drifting generator changes many bytes,
//! and 64 bits is an ample witness for that.
//!
//! # Two digests, because they cost different amounts
//!
//! * [`plan_digest`] folds the **description**: paths, sizes, profiles, edits,
//!   faults, actor changes. It never generates a byte of content, so it runs
//!   over a hundred-gigabyte workload in seconds.
//! * [`content_digest`] folds the description **and every generated byte**. It
//!   is the stronger claim and it costs what the corpus costs.
//!
//! Both are published. Where only the plan digest has been measured at a scale,
//! `benchmarks/workloads/manifest.json` says so rather than implying the other.

use super::content;
use super::plan::{content_tag, fault_tag, EditOp, Item};
use crate::workloads::digest::Fnv1a;

/// A framed fold over an item stream.
#[derive(Clone, Debug)]
pub struct StreamDigest {
    digest: Fnv1a,
    items: u64,
    with_content: bool,
}

impl StreamDigest {
    /// A digest over descriptions only.
    #[must_use]
    pub fn plan() -> Self {
        StreamDigest {
            digest: Fnv1a::new(),
            items: 0,
            with_content: false,
        }
    }

    /// A digest that also folds every generated byte.
    #[must_use]
    pub fn with_content() -> Self {
        StreamDigest {
            digest: Fnv1a::new(),
            items: 0,
            with_content: true,
        }
    }

    /// How many items have been folded in.
    #[must_use]
    pub const fn items(&self) -> u64 {
        self.items
    }

    /// Folds one item in.
    pub fn update(&mut self, item: &Item) {
        self.items += 1;
        self.byte(item.tag());
        match item {
            Item::File(file) => {
                self.text(&file.path);
                self.number(file.bytes);
                self.byte(content_tag(file.kind));
                self.number(file.stream);
                if self.with_content {
                    let mut digest = self.digest;
                    content::generate(file, &mut |chunk| digest.update(chunk));
                    self.digest = digest;
                }
            }
            Item::Access { path } => self.text(path),
            Item::Activity { name } => self.text(name),
            Item::Change(change) => {
                self.text(&change.actor);
                self.text(&change.path);
                self.byte(u8::from(change.shared));
                self.number(change.bytes);
            }
            Item::Checkpoint(checkpoint) => {
                self.text(&checkpoint.actor);
                self.number(checkpoint.covers_changes);
            }
            Item::Edit { path, op, stream } => {
                self.text(path);
                self.edit(*op);
                self.number(*stream);
                if self.with_content {
                    let mut digest = self.digest;
                    content::write_stream(
                        super::plan::ContentKind::Binary,
                        *stream,
                        op.length(),
                        &mut |chunk| digest.update(chunk),
                    );
                    self.digest = digest;
                }
            }
            Item::Fault(fault) => {
                self.number(fault.step);
                self.byte(fault_tag(fault.kind));
                self.text(&fault.subject);
                self.number(fault.magnitude);
            }
        }
    }

    /// The digest so far, as `fnv1a64:<16 hex digits>`.
    #[must_use]
    pub fn finish(&self) -> String {
        self.digest.finish_hex()
    }

    fn byte(&mut self, value: u8) {
        self.digest.update(&[value]);
    }

    fn number(&mut self, value: u64) {
        self.digest.update(&value.to_le_bytes());
    }

    /// Length-prefixed, so no two field splits can concatenate the same way.
    fn text(&mut self, value: &str) {
        self.number(value.len() as u64);
        self.digest.update(value.as_bytes());
    }

    fn edit(&mut self, op: EditOp) {
        match op {
            EditOp::Overwrite { offset, length } => {
                self.byte(1);
                self.number(offset);
                self.number(length);
            }
            EditOp::Insert { offset, length } => {
                self.byte(2);
                self.number(offset);
                self.number(length);
            }
            EditOp::Append { length } => {
                self.byte(3);
                self.number(length);
            }
        }
    }
}

/// Folds an item stream into a description-only digest.
pub fn plan_digest(items: impl Iterator<Item = Item>) -> String {
    let mut digest = StreamDigest::plan();
    for item in items {
        digest.update(&item);
    }
    digest.finish()
}

/// Folds an item stream into a digest that includes every generated byte.
pub fn content_digest(items: impl Iterator<Item = Item>) -> String {
    let mut digest = StreamDigest::with_content();
    for item in items {
        digest.update(&item);
    }
    digest.finish()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::corpus::plan::{ChangeSpec, ContentKind, FaultKind, FaultSpec, FileSpec};

    fn file(path: &str, bytes: u64) -> Item {
        Item::File(FileSpec {
            path: path.to_owned(),
            bytes,
            kind: ContentKind::Text,
            stream: 11,
        })
    }

    #[test]
    fn the_same_stream_digests_the_same() {
        let items = vec![file("a", 10), file("b", 20)];
        assert_eq!(
            plan_digest(items.clone().into_iter()),
            plan_digest(items.into_iter())
        );
    }

    #[test]
    fn order_is_part_of_the_digest() {
        let forward = vec![file("a", 10), file("b", 20)];
        let backward = vec![file("b", 20), file("a", 10)];
        assert_ne!(
            plan_digest(forward.into_iter()),
            plan_digest(backward.into_iter())
        );
    }

    /// The bytes an unframed fold would see for an `Access`-only stream: the
    /// variant tag, then the path, with nothing between them. The tag comes
    /// from [`Item::tag`] rather than a literal, so a lane that renumbers the
    /// variants cannot leave this helper quietly describing the old encoding.
    fn unframed_bytes(items: &[Item]) -> Vec<u8> {
        let mut bytes = Vec::new();
        for item in items {
            bytes.push(item.tag());
            match item {
                Item::Access { path } => bytes.extend_from_slice(path.as_bytes()),
                other => panic!("only Access is modelled here, not {other:?}"),
            }
        }
        bytes
    }

    /// The intent this module claims, kept because it says it well. It does not
    /// enforce it: both streams continue into the fixed-width `bytes`, `kind`
    /// and `stream` fields, which separate `"ab"`/`"c"` from `"a"`/`"bc"`
    /// whether or not a length prefix ever runs.
    /// `framing_separates_a_tag_byte_that_appears_inside_a_path` is the test
    /// that bites.
    #[test]
    fn framing_stops_adjacent_fields_from_running_together() {
        // Without a length prefix these two streams concatenate identically.
        let split_one = vec![file("ab", 1), file("c", 1)];
        let split_two = vec![file("a", 1), file("bc", 1)];
        assert_ne!(
            plan_digest(split_one.into_iter()),
            plan_digest(split_two.into_iter())
        );
    }

    /// The counterexample the framing claim actually rests on.
    ///
    /// `Item::Access` is a tag byte followed by one string and nothing else, and
    /// its tag is 2 — which is also how U+0002 encodes in UTF-8. So two accesses
    /// to `ab` and `c` present an unframed fold with the same byte string as one
    /// access to `ab\u{2}c`:
    ///
    /// ```text
    /// [2, b'a', b'b'] ++ [2, b'c']  ==  [2, b'a', b'b', 2, b'c']
    /// ```
    ///
    /// Nothing else in either stream can tell them apart, so the length prefix
    /// in [`StreamDigest::text`] is the only thing standing between two distinct
    /// workloads and one digest. Delete it and this test fails.
    #[test]
    fn framing_separates_a_tag_byte_that_appears_inside_a_path() {
        let two = vec![
            Item::Access {
                path: "ab".to_owned(),
            },
            Item::Access {
                path: "c".to_owned(),
            },
        ];
        let one = vec![Item::Access {
            path: "ab\u{2}c".to_owned(),
        }];

        assert_ne!(two, one, "a counterexample needs two distinct streams");
        assert_eq!(
            unframed_bytes(&two),
            unframed_bytes(&one),
            "the counterexample has gone stale: unframed, these two streams no \
             longer collide, so passing the assertions below proves nothing — \
             pick a pair that does collide"
        );

        assert_ne!(
            plan_digest(two.clone().into_iter()),
            plan_digest(one.clone().into_iter()),
            "two distinct item streams share a plan digest: the framing is not \
             separating fields"
        );
        assert_ne!(
            content_digest(two.into_iter()),
            content_digest(one.into_iter()),
            "two distinct item streams share a content digest: the framing is \
             not separating fields"
        );
    }

    #[test]
    fn the_variant_is_part_of_the_digest() {
        let as_access = vec![Item::Access {
            path: "x".to_owned(),
        }];
        let as_activity = vec![Item::Activity {
            name: "x".to_owned(),
        }];
        assert_ne!(
            plan_digest(as_access.into_iter()),
            plan_digest(as_activity.into_iter())
        );
    }

    #[test]
    fn a_size_change_changes_the_plan_digest() {
        assert_ne!(
            plan_digest(vec![file("a", 10)].into_iter()),
            plan_digest(vec![file("a", 11)].into_iter())
        );
    }

    #[test]
    fn the_content_digest_differs_from_the_plan_digest() {
        let items = vec![file("a", 4_096)];
        assert_ne!(
            plan_digest(items.clone().into_iter()),
            content_digest(items.into_iter())
        );
    }

    #[test]
    fn the_content_digest_is_reproducible() {
        let items = vec![file("a", 4_096), file("b", 1_024)];
        assert_eq!(
            content_digest(items.clone().into_iter()),
            content_digest(items.into_iter())
        );
    }

    #[test]
    fn a_profile_change_moves_both_digests() {
        let text = vec![file("a", 1_024)];
        let binary = vec![Item::File(FileSpec {
            path: "a".to_owned(),
            bytes: 1_024,
            kind: ContentKind::Binary,
            stream: 11,
        })];
        assert_ne!(
            plan_digest(text.clone().into_iter()),
            plan_digest(binary.clone().into_iter())
        );
        assert_ne!(
            content_digest(text.into_iter()),
            content_digest(binary.into_iter())
        );
    }

    #[test]
    fn every_variant_reaches_the_digest() {
        let variants = [
            file("a", 1),
            Item::Access {
                path: "a".to_owned(),
            },
            Item::Activity {
                name: "a".to_owned(),
            },
            Item::Change(ChangeSpec {
                actor: "actor-0000".to_owned(),
                path: "a".to_owned(),
                shared: true,
                bytes: 1,
            }),
            Item::Checkpoint(crate::corpus::plan::CheckpointSpec {
                actor: "actor-0000".to_owned(),
                covers_changes: 1,
            }),
            Item::Edit {
                path: "a".to_owned(),
                op: EditOp::Append { length: 8 },
                stream: 3,
            },
            Item::Fault(FaultSpec {
                step: 1,
                kind: FaultKind::DiskFull,
                subject: "peer-0".to_owned(),
                magnitude: 1,
            }),
        ];
        let mut digests: Vec<String> = variants
            .iter()
            .map(|item| plan_digest(std::iter::once(item.clone())))
            .collect();
        digests.sort();
        digests.dedup();
        assert_eq!(digests.len(), variants.len(), "two variants digest alike");
    }

    #[test]
    fn the_shared_flag_is_part_of_the_digest() {
        let change = |shared| {
            Item::Change(ChangeSpec {
                actor: "actor-0000".to_owned(),
                path: "a".to_owned(),
                shared,
                bytes: 1,
            })
        };
        assert_ne!(
            plan_digest(std::iter::once(change(true))),
            plan_digest(std::iter::once(change(false)))
        );
    }

    #[test]
    fn the_item_count_is_reported() {
        let mut digest = StreamDigest::plan();
        digest.update(&file("a", 1));
        digest.update(&file("b", 1));
        assert_eq!(digest.items(), 2);
    }

    #[test]
    fn an_empty_stream_still_has_a_digest() {
        assert!(plan_digest(std::iter::empty()).starts_with("fnv1a64:"));
    }
}
