//! The published wire vectors: one instance of every CWP message, with its exact bytes.
//!
//! # Why the bytes are pinned here and not only round-tripped
//!
//! A round-trip test proves this implementation agrees with itself. An external implementer —
//! `01KZC2TBX5BGTQPXXX2DATM3TY` builds one from the specification alone — needs to know whether it
//! agrees with *us*, and for that it needs bytes. The table below is those bytes.
//!
//! A change to any line here is a wire-format change. It is legitimate exactly when the message
//! set changed on purpose and `docs/protocol.md` §7.3 changed in the same commit; it is a defect
//! every other time, which is what makes the pin worth having.

mod common;

use common::{every_message, to_hex};
use mesh_sync_protocol::{decode_message, encode_message, MESSAGE_KINDS};

/// The pinned encoding of every message in `common::every_message()`, in that order.
///
/// Generated by this crate and checked by it; regenerate deliberately, never to make a test pass.
const VECTORS: [(&str, &str); 18] = [
    ("HELLO", "820184006b6d6573682d63626f722f305820111111111111111111111111111111111111111111111111111111111111111158202222222222222222222222222222222222222222222222222222222222222222"),
    ("AUTHENTICATE", "8202835820111111111111111111111111111111111111111111111111111111111111111158202222222222222222222222222222222222222222222222222222222222222222584033333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"),
    ("ADVERTISE_FRONTIER", "8203838284582011111111111111111111111111111111111111111111111111111111111111115820444444444444444444444444444444444444444444444444444444444444444403818209582055555555555555555555555555555555555555555555555555555555555555558458206666666666666666666666666666666666666666666666666666666666666666582077777777777777777777777777777777777777777777777777777777777777770180815820888888888888888888888888888888888888888888888888888888888888888802"),
    ("REQUEST_OPERATIONS", "82048458201111111111111111111111111111111111111111111111111111111111111111038258205555555555555555555555555555555555555555555555555555555555555555582099999999999999999999999999999999999999999999999999999999999999991840"),
    ("OPERATIONS_BATCH", "8205818288582004040404040404040404040404040404040404040404040404040404040404045820111111111111111111111111111111111111111111111111111111111111111104815820030303030303030303030303030303030303030303030303030303030303030358200303030303030303030303030303030303030303030303030303030303030303582004040404040404040404040404040404040404040404040404040404040404040044830102038858200505050505050505050505050505050505050505050505050505050505050505582011111111111111111111111111111111111111111111111111111111111111110581582004040404040404040404040404040404040404040404040404040404040404045820040404040404040404040404040404040404040404040404040404040404040458200505050505050505050505050505050505050505050505050505050505050505004483010203"),
    ("ACK_OPERATIONS", "820683582011111111111111111111111111111111111111111111111111111111111111110581820958205555555555555555555555555555555555555555555555555555555555555555"),
    ("ADVERTISE_MANIFESTS", "820781815820aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"),
    ("REQUEST_CHUNKS", "82088181835820bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1910001a00010000"),
    ("CHUNK_BATCH", "82098181845820bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb19100048ccccccccccccccccf5"),
    ("ACK_CHUNKS", "820a81815820bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"),
    ("UPDATE_ACTOR_HEAD", "820b83582011111111111111111111111111111111111111111111111111111111111111115820444444444444444444444444444444444444444444444444444444444444444405"),
    ("UPDATE_CANONICAL_HEAD", "820c8358208888888888888888888888888888888888888888888888888888888888888888025820dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"),
    ("PRESENCE", "820d835820111111111111111111111111111111111111111111111111111111111111111101197530"),
    ("REVIEW_BUNDLE", "820e825820eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee428100"),
    ("VALIDATION_RECEIPT", "820f8258200404040404040404040404040404040404040404040404040404040404040404428101"),
    ("APPROVAL_ENVELOPE", "8210825820dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd428102"),
    ("ANTI_ENTROPY_SUMMARY", "8211825820111111111111111111111111111111111111111111111111111111111111111182830102582029367279239ac5b4d286ae698921fc147358b69a50d5cd31243f828526ce4f2483030458206749ed671bc64d6131c21a5d1aa5a4ca78c9ac2638434ba354b4994ce93dace3"),
    ("ERROR", "8212830704782461736b65642066726f6d2039207768696c6520686f6c64696e67207468726f7567682035"),
];

#[test]
fn the_corpus_covers_every_message_exactly_once() {
    let mut seen: Vec<&str> = every_message()
        .iter()
        .map(|message| message.kind().as_str())
        .collect();
    seen.sort_unstable();
    let mut expected: Vec<&str> = MESSAGE_KINDS.iter().map(|kind| kind.as_str()).collect();
    expected.sort_unstable();
    assert_eq!(seen, expected);
}

#[test]
fn every_message_round_trips_through_the_wire() {
    for message in every_message() {
        let bytes = encode_message(&message);
        let decoded = decode_message(&bytes).unwrap_or_else(|error| {
            panic!("{} did not decode: {error}", message.kind());
        });
        assert_eq!(decoded, message, "{} did not round trip", message.kind());
        assert_eq!(
            encode_message(&decoded),
            bytes,
            "{} re-encoded to different bytes",
            message.kind()
        );
    }
}

#[test]
fn every_message_matches_its_published_vector() {
    for (message, (name, expected)) in every_message().iter().zip(VECTORS) {
        assert_eq!(
            message.kind().as_str(),
            name,
            "the vector table is out of order"
        );
        let actual = to_hex(&encode_message(message));
        let pinned: String = expected.chars().filter(|c| !c.is_whitespace()).collect();
        assert_eq!(actual, pinned, "{name} no longer encodes to its vector");
    }
}

#[test]
fn every_published_vector_decodes_to_the_message_it_names() {
    for (message, (name, expected)) in every_message().iter().zip(VECTORS) {
        let pinned: String = expected.chars().filter(|c| !c.is_whitespace()).collect();
        let bytes = from_hex(&pinned);
        let decoded = decode_message(&bytes)
            .unwrap_or_else(|error| panic!("the published {name} vector does not decode: {error}"));
        assert_eq!(&decoded, message);
    }
}

#[test]
fn every_message_in_the_corpus_satisfies_its_own_preconditions() {
    for message in every_message() {
        assert_eq!(
            message.check(),
            Ok(()),
            "{} is in the corpus but is not well formed",
            message.kind()
        );
    }
}

/// Bytes from lowercase hex. Panics on bad input, which is a broken test rather than bad data.
fn from_hex(text: &str) -> Vec<u8> {
    assert!(text.len() % 2 == 0, "a hex vector has an even length");
    (0..text.len() / 2)
        .map(|index| {
            u8::from_str_radix(&text[index * 2..index * 2 + 2], 16)
                .unwrap_or_else(|_| panic!("not hex at byte {index}"))
        })
        .collect()
}
